### ISSUE TITLE
Quality checking

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#1002]
What about add code quality checking to VM Portal, like https://codeclimate.com/quality/pricing/ for example?

WDYT? @michalskrivanek @sjd78

**Comment by sjd78** [comment]
A few initial questions:
  - For what purpose?
  - Are there any "quality checks" that you are particularly interested in running all the time?
  - What do those checks return now, and how much work would be involved to resolve those "quality issues"?

We already have eslint that enforces a bunch of style.  Test code coverage would probably be at 2%, so unless we really want to start writing A LOT of tests (across UI and redux and saga and others) I don't see a huge value.

**Comment by bond95** [comment]
@sjd78 
> For what purpose?

It shows places where code can be refactored.

> Are there any "quality checks" that you are particularly interested in running all the time?

Mostly I'm interested in duplication in code. Yeah maybe `quality check` can't right evaluate duplicates, but still it can point to places where it can be and it is unnecessary for all of them create separate issue.

> We already have eslint that enforces a bunch of style. Test code coverage would probably be at 2%, so unless we really want to start writing A LOT of tests (across UI and redux and saga and others) I don't see a huge value.

You can find it here https://codeclimate.com/github/bond95/ovirt-web-ui

**Comment by sgratch** [comment]
This is opened for a long time and therefore I'm closing this. 
As menitoned above, we do have eslint for enforcing code styling
