### ISSUE TITLE
VM's CDROM list is empty 

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#1023]
Run a VM and try Edit and change CD. The list is always empty unless you manually hit the reload button.

**Comment by michalskrivanek** [comment]
originally submitted as https://bugzilla.redhat.com/show_bug.cgi?id=1714942

**Comment by michalskrivanek** [comment]
@sjd78 addressed by #789? Even if so, this is a better issue description:)

**Comment by sjd78** [comment]
> @sjd78 addressed by #789? Even if so, this is a better issue description:)

Yes, this issue will be fixed when #789 is fixed.

This has also been logged in [BZ1687521](https://bugzilla.redhat.com/show_bug.cgi?id=1687521)

**Comment by gematik-fue** [comment]
Will it also fix the issue, the list contains images from different clusters/datacenters too?

**Comment by sjd78** [comment]
> Will it also fix the issue, the list contains images from different clusters/datacenters too?

That is a good point.

With #987, I'll make sure the ISO list on the cd-rom select box on the VM details page, and on create new VM are filtered to show only the ISOs in selected cluster's storage domains that are also permissioned to the user.

**Comment by sjd78** [comment]
> > Will it also fix the issue, the list contains images from different clusters/datacenters too?
> 
> That is a good point.
> 
> With #987, I'll make sure the ISO list on the cd-rom select box on the VM details page, and on create new VM are filtered to show only the ISOs in selected cluster's storage domains that are also permissioned to the user.

See #1040
