### ISSUE TITLE
VM Portal cannot sign in with "yarn start" 

### ISSUE THREAD

**Issue by thaorell** [oVirt/ovirt-web-ui#1024]
VM portal does not automatically sign in in development mode. Even when clicking "Sign In", the user is directed back to the same error page. 

ovirt-version: 4.4.0-0.0.master.20190522130703.git401db7f.el7

Browser and version: Chrome Version 74.0.3729.169 (

Steps to Reproduce:
```
ENGINE_URL=https://[your engine]/ovirt-engine yarn start
```

![Screenshot from 2019-05-29 15-50-11](https://user-images.githubusercontent.com/25762021/58640728-b3e8ec00-82c7-11e9-95a7-a2886f6ef459.png)

Temporary fix: 
Change the 'userSessionTimeoutInterval' in src/components/SessionActivityTracker.js

**Comment by gregsheremeta** [comment]
> Change the 'userSessionTimeoutInterval' in src/components/SessionActivityTracker.js
@thaorell  change it to what?

**Comment by thaorell** [comment]
@gregsheremeta change this.props.config.get('userSessionTimeoutInterval') to a high number, like 1000, should work

**Comment by sjd78** [comment]
When the ovirt-engine rest endpoint is close / fast, this issue doesn't tend to occur.  If there is any network delay, it always happens.
