### ISSUE TITLE
Update title and warning messages for Remove VM confirmation modal

### ISSUE THREAD

**Issue by lwrigh** [oVirt/ovirt-web-ui#1043]
Description of problem:

<img width="1440" alt="Screen Shot 2019-06-13 at 8 20 00 AM" src="https://user-images.githubusercontent.com/20227374/59432017-5323de00-8db4-11e9-87c8-0f99445b5a95.png">

The action button for the remove modal should be red since it's a destructive action. The text could also be a little more descriptive. It could say something along the lines of,

"Header: Remove VM   

Are you sure you want to remove the VM? All of the data attached to the VM will be removed as well".

**Comment by sgratch** [comment]
This is a duplication of issue #1013 and therefor I close it.

**Comment by sgratch** [comment]
@thaorell part of the work was done in #1077, but re-opening due to https://github.com/oVirt/ovirt-web-ui/pull/1060#issuecomment-523698113
