### ISSUE TITLE
accept more chars in username when connecting to VMware

### ISSUE THREAD

**Issue by steverweber** [oVirt/ovirt-web-ui#1054]
oVirt version number:
Version 4.3.4.3-1.el7

Steps to Reproduce:
1. Import Virtual Machine(s)
2. Source VMware
3. Username - include a ! like !asdfdg or _auser

Actual results:
fails because using char `!` or `_`

Expected results:
accept username... because it is /valid/ in VMware

Feature enhancement request:
should allow `!`and `_` because they are a popular prefix for privileged `bang` accounts

**Comment by steverweber** [comment]
this might be a ovirt-engine issue https://github.com/oVirt/ovirt-engine

**Comment by sjd78** [comment]
> this might be an ovirt-engine issue https://github.com/oVirt/ovirt-engine

The issue tracker for Administraion Portal and REST is over at https://bugzilla.redhat.com.  Issues here are specifically for VM Portal.
