### ISSUE TITLE
Template permission should be copy per default

### ISSUE THREAD

**Issue by TimmiORG** [oVirt/ovirt-web-ui#1090]
Description of problem:
VMs created via Userportal are not coping the assigned template permissions.
In my example I want to have a VM template available for a user group. Means everyone from this group should be able to see the newly created VMs from this template.

It is working if I create the VM through the admin portal and tick copy permissions. But there is not such options for the user portal.

VM Portal version number: 4.3.5
oVirt version number: 4.3.5
Browser and version: FF68

Steps to Reproduce:
1. Create template
2.assign specific group permissions to the template
3.login to user portal
4.create new VM

Actual results:
VM only visible in admin portal and for the user in the user portal. But not the other users in the group. Permissions are not copied.

Expected results:
VM should be available for all user in that group.  Permissions from template and the VM are the same.

Please let me know if you need more information or explanation.

Best regards
Christoph

**Comment by sjd78** [comment]
In the current create new VM, code, if a VM is being created from a template, the permission are copied:

https://github.com/oVirt/ovirt-web-ui/blob/032556bf15ef731b420d2a8c5541fcbd2a104576/src/sagas/vmChanges.js#L107-L112

This was added by https://github.com/oVirt/ovirt-web-ui/pull/987 and released in ovirt-web-ui version 1.6.1 (ovirt 4.4).

**Comment by sgratch** [comment]
Verified that group permissions are also copied by default when creating a VM via web ui.
Therefore I'm closing this issue as DONE.
