### ISSUE TITLE
send the locale to backend

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#110]
When accessing ovirt-web-ui from the ovirt landing page, a parameter ?locale=<the locale> is set.
Start sending this <the locale> as the Accept-Language header to get localized error messages from the REST API.

**Comment by mareklibra** [comment]
@jelkosz , please try.
Works for me :-)

**Comment by jelkosz** [comment]
@mareklibra this is going to work only for a subset of the errors and just for couple of languages. The translations are not maintained anymore (for couple of years) and will not get maintained any time soon.

We need to be more creative here if we want to have localized errors in 4.1 and will need to push for a maintained localizations for oVirt 4.2.

The only way how to do this now is a terrible solution of using the localized messages from the current user portal. Than, when the REST API returns some message, take the "detail", guess the key from the english file, hope it did not change since we have taken it, and use the key to translate the msg from the correct localized file.

It is a hacky/not reliable solution, not sure if we want to do this. But I would certainly not build the localization around the current deprecated API...

**Comment by mareklibra** [comment]
Blocked by missing translations in oVirt API.
Or until different approach is found.

**Comment by jelkosz** [comment]
As a by-product of a refactoring in the ovirt backend which aimed to unify the error messages across the entire backend and fronted, also the API translations has been made maintained (in particular this patch https://gerrit.ovirt.org/#/c/76216/).

Since this patches are merged and will land in oVirt 4.2, removing the "blocked" label.

Please note that the locale provided by URL to ovirt-web-ui is in form ?locale=en_US (e.g. with underscore) which has to be sent to the API in Accept-Language in form en-US (e.g. with dash).

**Comment by mareklibra** [comment]
- `locale` param is sent
- oVirt API translations are loaded
