### ISSUE TITLE
[ja_JP] The VM status and up-time text needs to be localized

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1101]
Originally opened by Bhushan Barve.

Description of problem:The VM status and the up-time text needs to be localized for ja_JP locale. I see that the VM status is localized for other locales. Please refer attached screenshot.

Version-Release number of selected component (if applicable):
RHV 4.3

How reproducible:
always

Steps to Reproduce:
1. Login to VM portal with jp locale
2. Observe the VM status and up-time for any running VM.

Actual results:
The VM status and uptime are not localized.

Expected results:
The VM status and up-time shou;d be localized.

Additional info:
https://bugzilla.redhat.com/attachment.cgi?id=1571257

**Comment by sjd78** [comment]
The VM status is translatable, and the status keys and messages exist in the **ja** translation.  They are:
```json
    "enum_VmStatus_down": "Off",
    "enum_VmStatus_image_locked": "Image locked",
    "enum_VmStatus_migrating": "Migrating",
    "enum_VmStatus_not_responding": "Not Responding",
    "enum_VmStatus_paused": "Paused",
    "enum_VmStatus_powering_down": "Powering down",
    "enum_VmStatus_powering_up": "Powering up",
    "enum_VmStatus_reboot_in_progress": "Reboot in progress",
    "enum_VmStatus_restoring_state": "Restoring state",
    "enum_VmStatus_saving_state": "Saving state",
    "enum_VmStatus_suspended": "サスペンド中",
    "enum_VmStatus_unassigned": "未割り当て",
    "enum_VmStatus_unknown": "不明",
    "enum_VmStatus_up": "Running",
    "enum_VmStatus_wait_for_launch": "Wait For Launch",
```

Screen shot of the Overview card with the dummy locale that puts arrows around all text:
![screenshot-ghost local dickerson-web com_3000-2020 08 20-22_15_08](https://user-images.githubusercontent.com/3985964/90844773-ae474e00-e332-11ea-93b3-620319c1f75a.png)

The uptime is not yet localized.

Uptime needs to handled in the following sports:
https://github.com/oVirt/ovirt-web-ui/blob/c4f55006ea7d686408ce22b87fb23d2d46188995/src/components/VmDetails/cards/OverviewCard/index.js#L276-L278

and
https://github.com/oVirt/ovirt-web-ui/blob/c4f55006ea7d686408ce22b87fb23d2d46188995/src/utils/format.js#L7-L37

based on https://github.com/oVirt/ovirt-web-ui/issues/945#issuecomment-459802105, localization of moment-duration-format will need to be adopted: https://github.com/jsmreese/moment-duration-format#localization
