### ISSUE TITLE
Can't set disks as bootable

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#1103]
Disks cannot be set/unset as bootable. 
Also the first added disk should be set as bootable

**Comment by michalskrivanek** [comment]
@yodem maybe this one is more interesting?

**Comment by yodem** [comment]
Sure I'll work on it

**Comment by yodem** [comment]
@michalskrivanek  if there is two disks, can both of the be unbootable? or the first one needs to be bootable?

**Comment by sgratch** [comment]
> @michalskrivanek if there is two disks, can both of the be unbootable? or the first one needs to be bootable?

There can be only **one** bootable disk defined for the VM. If the first disk is not bootable then the second disk can be set as one etc

**Comment by yodem** [comment]
> There can be only **one** bootable disk defined for the VM. If the first disk is not bootable then the second disk can be set as one etc

So as a user, if I want to change the bootable disk, what can I do? I'm not allowed to set other disk to bootable because only one disk can be bootable, and I can not set other disk to bootable from the same reason, so basically I can't change the bootable disk. Am I right?

**Comment by michalskrivanek** [comment]
> So as a user, if I want to change the bootable disk,

fix this bug so you'll be able to:)

**Comment by yodem** [comment]
So what do you say about letting the user to choose what disk does he want to be the bootable one?
I mean- in the edit dialog we will create a 'bootable' section, where it will be a dropdown list of all the disks and the selected one will be the bootable one?

**Comment by michalskrivanek** [comment]
I would just make that flag we show editable by clicking if that's what @lwrigh would accept

**Comment by lwrigh** [comment]
A dropdown is what of I was thinking of for showing the list of bootable disks. The second disk should probably be called "Backup disk" or something similar. I can mock something up as an example.

**Comment by yodem** [comment]
We can decide that only one will be bootable and to not allow the user make 2 disks as bootable. That way we wont have to deal with a second bootable disk

**Comment by michalskrivanek** [comment]
yes, only one (or none) can be set as bootable. That's a limitation from API. Our first(default) choice should be to make the first disk bootable in New VM flow. But we don't have it there at all...so the only relevant place now is Edit.
dropdown sounds too heavy to me. if you look at how it's represented in an Edit flow...how about a radio button/label with a possibility to have none selected? it will get the label (or move it if it's there for another disk already), clicking it on the label itself would remove "bootable". if that's not against anything in pf4 it's the most user friendly way how to handle this.

**Comment by michalskrivanek** [comment]
> Are you saying that the user should have control over whether or not a disk is bootable?

yes, they need to be able to designate exactly one (or none) disk to be bootable. With a default(good for 99% of cases) of marking the first added disk as bootable.

it's not a real property of disk(as in "this disk is bootable"), but rather a property of VM (which disk it should boot from)

**Comment by michalskrivanek** [comment]
I still think it would look better if that radio button list would allow none to be highlighted.

no, no other attributes

**Comment by yodem** [comment]
So what do you want to do in the edit disk dialog?

**Comment by sgratch** [comment]
@yodem @lwrigh For Edit disks dialog - we will have a checkbox only for the disk that we currently add (if it's the 1st disk then the default will be bootable. If it's not the 1st disk and there is other bootable disk already existed then the bootable option will be disabled).

**Comment by sgratch** [comment]
Adding/editing disks for an existing VM  - can be handled here.
Regarding setting a bootable disk for a new VM wizard (issue #923)- please open a new issue.

**Comment by lwrigh** [comment]
A checkbox for making a disk bootable makes sense to me. Is there a current screenshot of it?
