### ISSUE TITLE
template with same name

### ISSUE THREAD

**Issue by vmindru** [oVirt/ovirt-web-ui#1112]
For automation purposes I have the need of simplification, the goal is to have same template name in all DC's and all Clusters. Currently, there is a problem with this approach, I can not open details of the template because template name is used in URI request.  

`https://OVIRT-ENGINE/ovirt-engine/webadmin/?locale=en_US#templates-general;name=centos7-base-0.2`

VM Portal version number:  Software Version:4.3.5.5-1.el7

Browser and version:  Google Chrome | 75.0.3770.142

Steps to Reproduce:

https://imgur.com/4f24ENV 

1. Create Template name A
2. Create Template name A
3. try to access template in Browser 

Actual results:
only one template can be visualized 

Expected results:
all templates can be accessed

**Comment by sjd78** [comment]
@vmindru - You're describing a problem with Administration Portal (webadmin).  This project is for VM Portal (web-ui).  You need to open a BZ at http://bugzilla.redhat.com.

**Comment by sgratch** [comment]
> @vmindru - You're describing a problem with Administration Portal (webadmin). This project is for VM Portal (web-ui). You need to open a BZ at http://bugzilla.redhat.com.

@vmindru Template name is unique per DC, so you can only handle this cross DCs, but anyway can you please open a relevant BZ for this? Closing this issue.
