### ISSUE TITLE
ovirt-web-ui search active directory user problem

### ISSUE THREAD

**Issue by YongJunShan** [oVirt/ovirt-web-ui#1129]
Ovirt version 4.3, active directory windows 2012r2; after adding domain authentication through ovirt engine extension AAA LDAP setup, when adding domain users through management interface configuration - > system permissions, select Search: domain, namespace: *. The following go button is gray and cannot be searched. It is normal to search through ovirt engine extensions tool test. How can I solve this problem?

**Comment by sjd78** [comment]
@YongJunShan - Looks like your issue is with the Administration Portal.  Issues here are for the VM Portal.  I suggest you either email the user list (users@ovirt.org) or open a ticket in bugzilla against the administration portal (also called webadmin).

See https://www.ovirt.org/community/
