### ISSUE TITLE
Typo in pool allocated VMs tooltip message content

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#1133]
Description of problem:
The popover tooltip next to the Allocated VMs text in the status of VM Pool has a typo. The sentence currently is: "The maximum number of VMs that you can be allocated from this pool is 1." Instead it should be either "...number of VMs that you can allocate..." or "....number of VMs that can be allocated..." (or a completely different sentence).

![Screenshot_2019-11-04 VM Portal](https://user-images.githubusercontent.com/39263962/68146470-5a50b180-ff38-11e9-8f56-1e9154ed1e82.png)

VM Portal version number:
ovirt-web-ui-1.6.1-0.20191101.git527af5b.el7.noarch

oVirt version number:
ovirt-engine-4.4.0-0.0.master.20191010144856.git1bdc0f9.el7.noarch

Browser and version:
firefox-70.0-1.fc30.x86_64

Steps to Reproduce:
1. Have a VM Pool in VM portal 
2. Open VM portal
3. Click on the tooltip button next to the Allocated VMs text in VM Pool status

Actual results:
Sentence does not make sense due to a typo.

Expected results:

Additional info:

**Comment by michalskrivanek** [comment]
@sjd78 isn't this still a valid english?:) maybe the nuances are different...scott, any preference?

**Comment by doron-fediuck** [comment]
"you can be allocated" is not English.
It should be something like "that you can allocate" or "that can be allocated"

**Comment by michalskrivanek** [comment]
you are allocated VMs by the system - the system allocates you a VM. 
IMHO that matches https://www.ldoceonline.com/dictionary/allocate 

but it surely can be rephrased in any case...

**Comment by sjd78** [comment]
The original message is a bit awkward.

Probably better: "A maximum of {number} VMs from this pool may be allocated for your use."
