### ISSUE TITLE
Replaced local VncConsole by patternfly VncConsole

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1134]
We had VncConsole in repository because PF3 console didn't had needed functionality, but now PF3 VncConsole have everything that needed, so we can remove component in our repository and replace it by component from PF3.

**Comment by sgratch** [comment]
https://github.com/oVirt/ovirt-web-ui/pull/1091

**Comment by lwrigh** [comment]
For a PF4 console, there is not a specific component designed or built for it yet so I think we might have to use individual components like dropdowns and modals to create our own PF4 console.
