### ISSUE TITLE
Support renaming existing snapshots

### ISSUE THREAD

**Issue by toby1984** [oVirt/ovirt-web-ui#1135]
Hi,

We have a lot of VMs that need to have their snapshots renamed and re-creating all those snapshots seems a bit overkill ... would be nice if this was possible through the web UI!

**Comment by sgratch** [comment]
@toby1984  This ability is currently not supported and therefore this is a wrong tracker since it  should be opened as ovirt-engine RFE at Bugzilla: https://bugzilla.redhat.com

**Comment by sgratch** [comment]
@toby1984 I'm closing this issue since it should be opened on Bugzilla
