### ISSUE TITLE
The 'Console' operation is not disabled for a headless VM

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1139]
In case of a running headless VM (i.e. a VM configured to run without a graphical console device), the "Console" button in VM dashboard is not disabled/greyed out although clicking on it does nothing.

![image](https://user-images.githubusercontent.com/18169498/69342680-c0e20900-0c74-11ea-8df1-4660a2a35da2.png)

**Comment by michalskrivanek** [comment]
would you maybe try to take a look at this one too, @mouracamila?
