### ISSUE TITLE
Go To HTTPS Button

### ISSUE THREAD

**Issue by rmkraus** [oVirt/ovirt-web-ui#1155]
Feature enhancement request:

I have a use case where I would like for administrators to make virtual machine resources available to internal customers on-demand. RHV Virtual Machine pools are perfect for that. The only catch is that the hosted VMs provide an HTTPS service on port 443. Currently, the user would have to expand their browser to the correct size so that the FQDN is not ellipsized and copy/paste that into another browser window. It would be great if an HTTPS button was in the toolbar that would generically route to whatever HTTPS/443 service the VM is hosting. That would make for a much more cloud like experience for most use cases.

Essentially change this:

![Screenshot from 2020-01-21 14-06-39](https://user-images.githubusercontent.com/4956442/72834656-45daa600-3c57-11ea-9eeb-7f953570ef19.png)

To look like this:

![after](https://user-images.githubusercontent.com/4956442/72836126-06fa1f80-3c5a-11ea-9fde-c1dd443b02fc.png)

I'm pretty open on this idea, but I think adding this capability to oVirt would open it up to a lot more use cases by allowing administrators to make a cloud-lite self-service experience without provisioning OpenStack.

**Comment by rmkraus** [comment]
Now that I'm looking at the picture, it would probably be better to put the HTTPS button to the right of the Console dropdown, but the general idea is there.

**Comment by michalskrivanek** [comment]
Thanks for contribution!
It's hard to justify as a general case, but it should be possible to add via some conditional code.
How about showing that button only when a VM has certain custom property? That should work, when you define one it is returned as part of the /vms endpoint so it's available on the main page, and you can use that to determine whether to show the button or not, and maybe even customize the text&port:)

if you're unfamiliar with that, see https://www.ovirt.org/documentation/admin-guide/appe-VDSM_and_Hooks.html "Defining Custom Properties", once defined it shows up in webadmin and can be set to whatever you allow, and then it will be visible under api/vms/[vmid] as 
<custom_properties>
<custom_property>
<name>my_fancy_property</name>
<value>whatever</value>
</custom_property>
</custom_properties>

**Comment by rmkraus** [comment]
I really like that idea. Let me take a look into that. Thanks!

**Comment by rmkraus** [comment]
@michalskrivanek 

Thanks so much for your suggestion. I took it and ran with it. Let me know what you think.

I am now using three custom VM Properties: service_port, service_proto, service_name
A button will be created displaying the manually specified name that will connect to the VM using the specific protocol and port. This keeps it very generic.

The newest code is in my PR (#1156).

Thanks!
