### ISSUE TITLE
Allocating a VM from a VmPool results in <UNKNOWN> tags

### ISSUE THREAD

**Issue by nkovacne** [oVirt/ovirt-web-ui#1161]
Description of problem [include screenshots and browser console logs]:

When a user attachs a VM from a VmPool, a tooltip is shown with <UNKNOWN> tags instead of actual data.

![Captura de pantalla de 2020-02-10 09-40-23](https://user-images.githubusercontent.com/10921680/74138889-4927d880-4bea-11ea-8de3-eacd16c686f4.png)

VM Portal version number: 4.3.8.2

oVirt version number: 4.3.8.2

Browser and version: Google Chrome 79.0.3945.130-1

Steps to Reproduce:
1. Open the Admin Portal
2. Wait for a user to attach a VM from a VmPool

Actual results:

The tooltip above is shown

Expected results:

The <UNKNOWN> marks should be replaced with actual info.

Additional info:

The actual info is interpolated correctly in the Event list, though.

> User aXXX successfully attached to VM DSI-49 in VM Pool DSI.

**Comment by sgratch** [comment]
@nkovacne Hi, this tracker is for the VM Portal and this is an Admin Portal issue. 
The tracker for that is https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine (Component = Frontend.Webadmin)

Would you mind opening this there? Thank you!
