### ISSUE TITLE
External Service Button URI

### ISSUE THREAD

**Issue by rmkraus** [oVirt/ovirt-web-ui#1168]
Feature enhancement request:
I would like to expand on #1156. I am planning on adding a fourth field to the external service record to specify a URI on the host where the service can be reached. I would also like to change the field separator so as to not conflict with the / in the URI field. The external service field format would then be: 

> NAME|PROTOCOL|PORT|URI, ...

Does this sound alright?

**Comment by michalskrivanek** [comment]
sure. maybe "," is good enough as a separator?

**Comment by michalskrivanek** [comment]
eh, or you want to define more of these and those make sense to separate by ,:) either way it's absolutely fine with me
