### ISSUE TITLE
add support for "runs on host" for VM detail

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#117]
This could be an integration point between the cockpit-machines(-ovirt-provider) and ovirt-web-ui. 

The flow could be like this:
- When opening the VM detail, checking if the user can see also the host on which the VM is running on (not sure how, maybe need to check the permissions of the user, maybe could be understood from the REST response of the GET /vms/<vm id>.
- If the user does have permission to see it, add a new field "runs on host" to the VM detail
- next to the value, there should be a link or button saying "go to host" which would redirect to that host's cockpit

**Comment by mareklibra** [comment]
For longer host name:
![01_longername](https://user-images.githubusercontent.com/17194943/27470169-e9cabe54-57f2-11e7-90b0-0908e66d8da8.png)

and narrow screen:
![02_narrowscreen](https://user-images.githubusercontent.com/17194943/27470170-e9cd6d70-57f2-11e7-85a6-6e08ce16361c.png)

What about rendering the `(on [HOST_NAME])` separately as a first entry of the second column (right above the `Consoles`).
Sort of `Runs on:      [LINK_TO_HOST]`
