### ISSUE TITLE
Open a VM console is failing for all console types

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1181]
Trying to open a VM console (for either SPICE, VNC or NoVNC) is always failing with an error:

![image](https://user-images.githubusercontent.com/18169498/78679727-43512980-78f3-11ea-86ad-e928a84d32c4.png)

This is a regression reproduced with ovirt-web-ui version  1.6.1-1

A d/s bug was opened as well: https://bugzilla.redhat.com/show_bug.cgi?id=1826454

**Comment by sgratch** [comment]
@hstastna We should still refer to this problem; https://github.com/oVirt/ovirt-web-ui/pull/1192#issuecomment-626409649 and see if it's a bug or settings issue. in case of a bug, please open a separate new PR.

**Comment by hstastna** [comment]
Just a note that SPICE, VNC are working now (fixed by PR https://github.com/oVirt/ovirt-web-ui/pull/1192) but we still have problems with noVNC and it seems to be a bug, not a settings issue.

**Comment by hstastna** [comment]
Here's the patch for fixing the VNC Browser console issue: https://gerrit.ovirt.org/#/c/109214/

**Comment by sgratch** [comment]
> Here's the patch for fixing the VNC Browser console issue: https://gerrit.ovirt.org/#/c/109214/

The patch on gerrit is now merged, so we can mark this issue as closed since there is also a bug opened on this for QE to verify: https://bugzilla.redhat.com/1826454
