### ISSUE TITLE
Maximizing the Notifications drawer causes it's disappearance

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1182]
After trying to maximize the Notifications drawer by clicking the toggle expand button

![image](https://user-images.githubusercontent.com/18169498/78681526-86ac9780-78f5-11ea-9c20-761aa6a34a55.png)

then from now on the drawer is disappeared until next browser refresh Clicking on bell button of navbar doesn't display it anymore as well.

It's reproduced with ovirt-web-ui version 1.6.1-1

**Comment by hstastna** [comment]
I also tried to click on VM Portal's _Refresh_ button to "fix" the Notifications drawer, it didn't help. It has to be browser refresh as mentioned in the description of the issue above.

**Comment by hstastna** [comment]
Just a note that after trying to expand the Notification drawer, the drawer disappears and "something" extra appears:
![expand_after](https://user-images.githubusercontent.com/13417815/80373996-41490d80-8896-11ea-900f-0fc735835c02.png)
