### ISSUE TITLE
Messages view needs scrollbars

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#119]
... both horizontal and vertical. 

* "Clear messages" button has to be always accessible.
* Long messages should be wrapped.

see screenshot http://i.imgur.com/TZl04OY.png

**Comment by mareklibra** [comment]
Feel free to attach screenshots directly to the issue/pull requests, they become visible without additional clicking :-)

**Comment by jniederm** [comment]
Good tip, thanks
