### ISSUE TITLE
Create VM Wizard - basic settings should be reset to baseline default when changing provision source

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1197]
On the "Create Virtual Machine" new dialog->Basic Settings step:  when changing the "Provision Source" field value from "Template" to "ISO" source or vice versa, the VM's basic settings field values (OS, memory, cpu, optimized for, cloud-init) should be reset back to baseline defaults.

**Comment by sjd78** [comment]
The initial state is currently configured here (well in the `steps` keys at least):

https://github.com/oVirt/ovirt-web-ui/blob/e45b22ea762489a02821e8fb5483dcfe2882dbe6/src/components/CreateVmWizard/CreateVmWizard.js#L18-L41

The basic value could probably just be derived from the default template just as easily.

@sgratch, @michalskrivanek - Any preference for leaving the default values hard coded like this verses pulling them from the default template?

**Comment by michalskrivanek** [comment]
you need to keep some of them, like startOnCreation which is specific to ovirt-web-ui only. But most are mimicking Blank template and it should be using it directly instead. We do allow its customization in webadmin so the defaults can be different.
I.e. you'd be always usiing a Template for getting these, just by default you use the one named "Blank". Works the same in webadmin really.
