### ISSUE TITLE
Create VM Wizard - VM time zone format should be compatible with VM OS and also displayed on the review report step

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1198]
This includes two parts for handling the VM timezone:

1. Apply the fix done for previous create VM  #1118, on existing create VM flow: 
If template's time zone format or VM's time zone format is not compatible with VM OS then it should change time zone to default. For Windows default time zone if: GMT Standard Time, for other OSs: Etc/GMT

2. Consider displaying current timezone in the review report step (not just for windows but for all OS types) so that the user will know which timezone was actually set.

**Comment by hstastna** [comment]
Just a note that this is because Windows and Linux use different time zone names and the (default or otherwise) template time zone could be in the wrong format.

**Comment by hstastna** [comment]
@sgratch What time zone should I choose when user sets ISO as a Provision Source? I would not set any time zone and let the backend to choose. Creating VM works fine when I don't choose any time zone in this case.

**Comment by sgratch** [comment]
> @sgratch What time zone should I choose when user sets ISO as a Provision Source? I would not set any time zone and let the backend to choose. Creating VM works fine when I don't choose any time zone in this case.

You should choose the default based on the OS, as done on current 1220 PR fix.
