### ISSUE TITLE
Create VM Wizard - Validate add/edit NIC fields on row save action

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1205]
On the "Create Virtual Machine" wizard -> "Networking" step, when adding/editing a NIC by clicking the checkmark box, need to validate all fields before saving and avoid saving in case of invalid values. Specifically need to make sure that the NIC name is unique and valid.
Consider display an error in case of a validation failure.

**Comment by bamsalem** [comment]
In this dialog there is no error handling yet, so I can't use existing notification/ error message component so we need to add a new error message. I tried to add the error message but it looks bad:

![pasted image 0](https://user-images.githubusercontent.com/64131213/82205283-54b72980-98d4-11ea-9369-d33b2ab39807.png)

There is one error message for now, the error is about the NIC's name, something like: "the NIC's name should be unique with maximum X  characters and contains only A-Z...."

For now I can add "bubble message" or tooltip with the error message and color the field in a red color, but in a broad view I guess that in the future we will add more validations (disks' name field, etc...), so maybe we need to consider adding infrastructure for error handling messages which will serve us in the next validations.
there are no validation which uses a dedicated message box (like in the image above - but designed in a better way), dedicated error message box will create uniformity in handling errors in this dialog.

What would be the best solution for the error message component?

@lwrigh I would like to hear you opinion about that...

**Comment by sgratch** [comment]
@lwrigh @bamsalem I guess we will use Patternfly 4 guidelines for that, right? It will be used for all steps so we need a general design for fields validation of displaying an error on current dialog step while disabling moving to next step as long as that error occurs. WDYT?
