### ISSUE TITLE
GET https://engine0.lab/favicon.ico 404 (Not Found)

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-web-ui#1206]
Description of problem: 
console shows "GET https://engine0.lab/favicon.ico 404 (Not Found)"

VM Portal version number: ovirt-web-ui-1.6.1-1.el8.noarch

oVirt version number: 4.4.0 RC1

Browser and version: Google Chrome 81.0.4044.138

Steps to Reproduce:
1. Open the web ui
2. look at the console
3.

Actual results:
 "GET https://engine0.lab/favicon.ico 404 (Not Found)"

Expected results:
favicon.ico is found

Additional info:

**Comment by sgratch** [comment]
@sjd78 Maybe this is due to removing the following line from branding's `Makefile`?:
"ln -sf "$(PKG_BRANDING_DIR)/images" "$(DESTDIR)$(WEB_UI_BRANDING_DIR)/images"

**Comment by sjd78** [comment]
> @sjd78 Maybe this is due to removing the following line from branding's `Makefile`?:
> "ln -sf "$(PKG_BRANDING_DIR)/images" "$(DESTDIR)$(WEB_UI_BRANDING_DIR)/images"

Unlikely.  This issue happens on both upstream and downstream.

In absence of a `<link rel="shortcut icon" href="/.../favicon.ico">` style tag in the index html file, the browser automatically attempts to fetch one from `server-root/favicon.ico`.  The error described in this issue seems to have always been this way.

A proper fix will be to put the correct favicon path in a `link` tag on the server side (in prod the index.jsp, in dev something similar).  Once the react app is loaded, a `link` tag with the correct favicon.ico file path is injected on the page.  So the user visible side of the issue is only briefly noticeable.

**Comment by sgratch** [comment]
> Unlikely. This issue happens on both upstream and downstream.

@sjd78 In addition to the mentioned 404 error, the tab icon is not shown for 4.4 d/s VM portal (while it is shown for 4.4 u/s and for 4.3.9 as well). So I guess we did broke that for d/s only.
If it's turn out to be a branding issue after all as well, then I'll open a separate branding bug for that.

**Comment by sjd78** [comment]
> > Unlikely. This issue happens on both upstream and downstream.
> 
> @sjd78 In addition to the mentioned 404 error, the tab icon is not shown for 4.4 d/s VM portal (while it is shown for 4.4 u/s and for 4.3.9 as well). So I guess we did broke that for d/s only.
> If it's turn out to be a branding issue after all as well, then I'll open a separate branding bug for that.

On upstream web-ui master branch running installed to a dev engine, the favicon is loaded ok, just after the normal browser favicon fetch fails with a 404:
![VM Portal - Google Chrome_029](https://user-images.githubusercontent.com/3985964/83173290-cbc79b80-a0e6-11ea-85ae-65df4744b301.png)

After installing downstream branding to my dev engine, and doing a hard reload, the favicon from d/s is loaded ok with the same 404 error (as expected):
![VM Portal - Google Chrome_030](https://user-images.githubusercontent.com/3985964/83173696-4a243d80-a0e7-11ea-9ced-ab2c86182fc4.png)

@sgratch - favicon is not broken in u/s branding or d/s branding, but this initial 404 error stands.  The only real solution is to have ovirt-web-ui.war inject the proper favicon link tag when the root index.jsp is served.  That is how ovirt-engine branding does it.

**Comment by sgratch** [comment]
> @sgratch - favicon is not broken in u/s branding or d/s branding, but this initial 404 error stands. The only real solution is to have ovirt-web-ui.war inject the proper favicon link tag when the root index.jsp is served. That is how ovirt-engine branding does it.

After investigating it more deeply, we found out that there is a separate d/s branding issue which causes images (including favicon.ico) to be missing on a d/s installation. A dedicated bug will be filed for it on BZ.

So this issue should only handle the u/s 404 original error, as mentioned above.
