### ISSUE TITLE
Shutdown confirmation widget UX issues

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#121]
* It gets wider when clicked. This can break layout of parent element - "pause" icon is wrapped to the next line.
* It doesn't work much as a prevention of accidental clicks. Significant area of original  'power symbol' is shared with confirmation button "Shut down?". So accidental double click actually can turn the VM off.

Both problems can be solved by applying approach used by https://ethaizone.github.io/Bootstrap-Confirmation/ or similar projects: Show a popup that doesn't interfere with current layout and one needs to move the mouse cursor to confirm it.

Screemshots: http://imgur.com/a/hiW3g

**Comment by mareklibra** [comment]
The https://ethaizone.github.io/Bootstrap-Confirmation/ looks great!

@bond95 , what do you think about using it for https://github.com/oVirt/ovirt-web-ui/pull/106 ?

**Comment by mareklibra** [comment]
Will be fixed within https://github.com/oVirt/ovirt-web-ui/issues/16 by new confirmation component
