### ISSUE TITLE
Create VM Wizard - disk size units on a new disk row are not displayed before saving

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1216]
On the "Create Virtual Machine" wizard -> "Storage" step, when adding/editing a disk by clicking the checkmark box, the disk size units are not displayed. How the user will know which value to set without knowing the units. 

It worth changing the column title to include units, and use GiB instead of TiB, the same as done for create new disk on VM's card. 
Please consider adding the tooltip for size extending as well.

The create new disk on VM's card:
![image](https://user-images.githubusercontent.com/18169498/82305289-1ef26d80-99c6-11ea-8827-76e4d62521a7.png)

**Comment by bamsalem** [comment]
Hi @sgratch I want to draw your attention, it seems like this issue related to  issue #1214  and the units covered by the "Storage Domain" field.
do you still want the changes requested above?
if the units will be shown after the changes which fix issue #1214 will be merged we can consider just add `FieldLevelHelp`.
I think changing the column title is not necessary after fixing issue #1214.
what do you think?

**Comment by sgratch** [comment]
@bamsalem @lwrigh I agree. So the question is if to add a tooltip and where to locate it (column title or field itself).

**Comment by lwrigh** [comment]
I would suggest if the units are going to be changed and moved outside of the label or the dropdown field that they are consistent across the board. Both the unit of measurement and the placement of the unit of measurement in the field.

**Comment by sgratch** [comment]
@lwrigh Not sure I understand, do you suggest moving both units ("GiB") and the tooltip (as mentioned on the description above) to the "Size" column title or leave it as is in the field?

Current appearance (without the tooltip):
![image](https://user-images.githubusercontent.com/18169498/83426542-fba0d700-a437-11ea-9736-3cbe2be2f7b4.png)

**Comment by lwrigh** [comment]
I would keep it at the field level and not hide it in the info tip if I'm understanding the question correctly.

**Comment by sgratch** [comment]
> I would keep it at the field level and not hide it in the info tip if I'm understanding the question correctly.

@lwrigh My question was where to add the tooltip for the Size field of: "After you create a disk, you may only extend his size when you make edits". I guess, based on your previous answer, that it should be kept as a tooltip at the field level as well
