### ISSUE TITLE
Suspended VM cannot be shut down 

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#1227]
Description of problem:
If a VM is suspended (run VM -> suspend -> wait until the status is Suspended), the only action available for the VM is to run it unlike in Admin Portal where you can also shut it down.

VM Portal version number:
ovirt-web-ui-1.6.2-1.el8ev.noarch

oVirt version number:
ovirt-engine-4.4.1-0.1.el8ev.noarch

Browser and version:
firefox-76.0.1-1.fc31.x86_64

Steps to Reproduce:
1. Run VM, suspend it and wait until the state is Suspended
2. Check available actions in main grid
3. Check available actions in VM detail

Actual results:
Only run actions is available.

Expected results:
Both shutdown and run actions are available

Additional info:
According to the tests, the shutdown action used to be working for suspended VMs in previous versions.

**Comment by hstastna** [comment]
Just a note that this is a UI issue. I think I have a fix, I just need to make sure about it.
