### ISSUE TITLE
Create VM Wizard - validate the disk's storage domain for the current user

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1230]
On the "Create Virtual Machine" wizard -> "Storage" step, for both template's and new disks we need to make sure that the disk’s storage domain is a valid domain for the current user.  If it isn’t, force selection of another storage domain.

**Comment by bamsalem** [comment]
I started to work on a solution for this issue,
I want to ask you what do you think about its look:
![image](https://user-images.githubusercontent.com/64131213/84258860-a32ba280-aae5-11ea-8d9d-698be059f22a.png)
In case that the storage domain is not valid for the current user the disk row will appear with an "UNKNOWN" storage domain, in my solution that case will be handled as shown in the screenshot above, the user won't be able to proceed to the next step till he choose storage domain from the dropdown list, and then the "Next" button will be enabled.
 what do you think?
