### ISSUE TITLE
Create Hosted Engine Wizard -> Storage Settings -> Fibre Channel -> Storage options disabled when space is still available

### ISSUE THREAD

**Issue by HunterGerlach** [oVirt/ovirt-web-ui#1254]
VM Portal version number: 

oVirt version number: 4.4.1

Browser and version: Firefox 68.10.0esr (64-bit)

Steps to Reproduce:
1. Create a Hosted Engine
2. Get to the storage options step and select Fibre Channel
3. Once a few LUNs have been discovered, increase the Disk Size (under Advanced) to something like 100GiB
4. Notice that the options are disabled even though they have enough disk space

Actual results:
- Radio options to select luns are disabled
Expected results:
- Radio buttons should be enabled until requested disk size is greater than the available size on the luns
Additional info:
Work around is available - Open developer tools and remove "disabled" from radio button and select the preferred luns

Screenshot shows selected luns *after* workaround implemented

![Screenshot from 2020-07-16 10-01-11](https://user-images.githubusercontent.com/5001050/87681214-6a1dc800-c74c-11ea-9d20-047bbced5cde.png)

**Comment by sgratch** [comment]
@HunterGerlach hi, thanks for filing this issue but it seems like you used a wrong tracker. This ovirt-web-ui repository deals only with VM Portal issues while this issue is related to Hosted Engine wizard and therefore should be opened via Bugzilla: https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine (Component set to BLL.hostedEngine).
Can you please file a bug so that we can close this? Thanks

**Comment by sgratch** [comment]
> @HunterGerlach hi, thanks for filing this issue but it seems like you used a wrong tracker. This ovirt-web-ui repository deals only with VM Portal issues while this issue is related to Hosted Engine wizard and therefore should be opened via Bugzilla: https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine (Component set to BLL.hostedEngine).
> Can you please file a bug so that we can close this? Thanks

@sandrobonazzola are you aware of that or should we open a bug?
Meanwhile, I'm closing this issue since not relevant to web-ui
