### ISSUE TITLE
Create Hosted Engine Wizard Crash at "Add HE disks" step - Ooops!

### ISSUE THREAD

**Issue by HunterGerlach** [oVirt/ovirt-web-ui#1255]
VM Portal version number:

oVirt version number: 4.4.1/4.4.0
occurs on oVirt Node and Centos
Browser and version: Firefox 68 / Chrome latest

Steps to Reproduce:
1. Use the Create Hosted Engine wizard in cockpit to define a hosted engine and add storage...
2. After running the last step of selecting the storage, the Ansible scripts time out at the "Add HE disks" step
3. This timeout throws an error and causes the web gui to crash with an "Ooops!" error

Actual results:
- Wizard crash
Expected results:
- Graceful handling of Ansible timeout error
Additional info:
Attached is what appears after clicking the "Oops!" button and then being directed to view Developer tools in the browser.

I have run the hosted engine setup manually and I am receiving a timeout error at the "Add HE disks" step as well, which lets me know these are related issues (no yet filed).

![ovirt-web-crash](https://user-images.githubusercontent.com/5001050/87686983-2e3a3100-c753-11ea-8ae4-49fcea34fae2.png)

**Comment by sgratch** [comment]
@HunterGerlach hi, thanks for filing this issue but it seems like you used a wrong tracker. This ovirt-web-ui repository deals only with VM Portal issues while this issue is related to Hosted Engine wizard and therefore should be opened via Bugzilla: https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine (Component set to BLL.hostedEngine).
Can you please file a bug so that we can close this? Thanks

**Comment by sgratch** [comment]
> @HunterGerlach hi, thanks for filing this issue but it seems like you used a wrong tracker. This ovirt-web-ui repository deals only with VM Portal issues while this issue is related to Hosted Engine wizard and therefore should be opened via Bugzilla: https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine (Component set to BLL.hostedEngine).
> Can you please file a bug so that we can close this? Thanks

@sandrobonazzola are you aware of that or should we open a bug?
Meanwhile, I'm closing this issue since not relevant to web-ui
