### ISSUE TITLE
Export object option in oVirt Engine console 

### ISSUE THREAD

**Issue by vinodthecoder** [oVirt/ovirt-web-ui#1259]
[ Thank you for submitting an issue to the VM Portal issue tracker. Please read these instructions and delete this section before submitting your issue. ]

[ If this is a bug report, use this section and delete the other one: ]

Description of problem [include screenshots and browser console logs]:

VM Portal version number:

oVirt version number:

Browser and version:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:

[ If this is a request for a feature or enhancement, use this section and delete the other one: ]

Feature enhancement request:
[ Describe the feature or enhancement you would like. Be as detailed as possible, including screenshots or links to design documents. ]

It would be a great help if we get option to export objects to csv in oVirt Engine console. For example 
Virtual Machine Tab, give an option to export all or selected VMs with selected columns to csv format.
Same for Hosts in a cluster and Data domains in a datacenter.  
This will really help admins and managers to generate reports quickly.  
![oVirt Open Virtualization Manager](https://user-images.githubusercontent.com/29625895/88266511-f6039700-ccec-11ea-88e8-1834129c3e39.png)

**Comment by sjd78** [comment]
Hi @vinodthecoder, the screen shot you included is for webadmin / Admin Portal, not the ovirt-web-ui / VM Portal.

Please create a BZ ticket over at https://bugzilla.redhat.com under oVirt, product: ovirt-engine, component: Frontend.WebAdmin.

**Comment by sgratch** [comment]
> Please create a BZ ticket over at https://bugzilla.redhat.com under oVirt, product: ovirt-engine, component: Frontend.WebAdmin.
@vinodthecoder I'm closing this issue since this is the wrong tracker for webadmin issues, please open a BZ ticket as mentioned above.
