### ISSUE TITLE
Create VM Wizard - support advanced CPU topology setting on "Basic Settings" step

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1264]
Currently the user can only update advanced CPU topology (i.e. Virtual Sockets, Virtual Cores, Virtual Threads) for an existing VM via the Details VM card.
This should be also supported for a new VM creation.

We can consider adding that as a hidden "Advanced Options" section within the  "Basic Settings" step, the same as appears on the Details VM card.

**Comment by hstastna** [comment]
From the design point of view, I can see more possibilities, how to implement this feature in the Create VM Wizard. Two of them look like this:

1)
![adv_options1a](https://user-images.githubusercontent.com/13417815/89775357-e9ae7500-db07-11ea-9f02-8c678ce54eb5.png)
![adv_options1b](https://user-images.githubusercontent.com/13417815/89775363-ec10cf00-db07-11ea-997b-bf62b6fd0562.png)
With this design above we would achieve consistency with the appropriate options already in the VM details page. However, I think it does not look very well in the wizard.

2)
![adv_options2a](https://user-images.githubusercontent.com/13417815/89775367-f03cec80-db07-11ea-8694-f86f06500130.png)
![adv_options2b](https://user-images.githubusercontent.com/13417815/89775373-f29f4680-db07-11ea-90ea-699d8d2e4c81.png)

@yfrimanm WDYT? IMHO, the second of my suggestions is more consistent with other extra options in the _Basic step_ of the wizard. But maybe we want some combination of those two options above.. ? Thanks!

**Comment by yfrimanm** [comment]
Hi @hstastna@redhat.com,
IMHO the 1st option is much better because 'Advanced options' are
usually shown in a collapse/expand mode as you suggest there.
The 2nd option of showing it in a checkbox is kind of odd because a
checkbox is not a CTA (call to action|).
Yifat

**Comment by hstastna** [comment]
@yfrimanm Thanks very much, Yifat, for the reply. 

However the 1st option is better and a CTA, I think it's not very nice. Maybe some changes regarding aligning text or the size of the drop downs? To make it look more consistent with the rest of the settings. I would like to know your opinion. Thanks a lot!

**Comment by yfrimanm** [comment]
Hi  @Hilda Stastna <hstastna@redhat.com>
I think that if you will keep the text alignment to the right, as shown in
the first part of the form, it will make it look better.
Yifat

**Comment by matthewcarleton** [comment]
+1 to what @yfrimanm has said. I'm not familiar with RHV design conventions but in OpenShift this is exactly how we'd do it for this type of dropdown.
We've also seen a step added for advanced options as well. I'm not sure if that's the right approach here though.

**Comment by hstastna** [comment]
@yfrimanm @matthewcarleton And WDYT about this?
![adv](https://user-images.githubusercontent.com/13417815/90455726-17db1880-e0f7-11ea-8aa8-bbd62b472640.png)

So after expanding the _Advanced Options_, we could see the labels and drop downs nicely aligned, the same way as the options above the adv. options + we can have there some subsections like _VCPU Topology_, similarly as when enabling _Cloud-init/Sysprep_:
![sysp](https://user-images.githubusercontent.com/13417815/90455964-c8e1b300-e0f7-11ea-8920-790a51042a5e.png)

However, as you can see in the picture above, the options (_Hostname_ etc.), displayed after the checkbox _Enable Cloud-init/Sysprep_ is checked, are aligned differently than the basic options above them. So I'm still not sure which style to choose. Yes, I am trying to add the same advanced options as we already have in the VM details, but there's different style, too, different text aligning etc.:
![vcpu](https://user-images.githubusercontent.com/13417815/90456425-3e01b800-e0f9-11ea-8268-d858b053d3b0.png)

So I can see 3 different extra options' styles and I am even more confused :D Thanks very much in advanced!

**Comment by matthewcarleton** [comment]
@hstastna I think the only other way would be to have the checkbox options aligned left to the labels of the fields above so when the cloud init options are shown they align properly. I don't think they should be further to the left than the checkbox that toggles them though. 
One other thought would be to put these options in the advanced section and have them always shown there and not require the checkbox to show them.

**Comment by yfrimanm** [comment]
+1 to what @Matthew Carleton <mcarleto@redhat.com> said and I think that a
little bit of an extra space will also help to separate these 2 and make it
clearer.
*Current design:*
[image: image.png]

*Suggested design: (added a little space between the 2 topics: Boot order
and VCPU Topology)*

[image: image.png]

**Comment by hstastna** [comment]
@yfrimanm @matthewcarleton I cannot see any of your suggested designs. The images are not displayed. Also note that this issue is primary about "Advanced Options" of the Create VM Wizard. But of course, other suggestions to improve other screens (like. VM details) are welcome! :)

**Comment by yfrimanm** [comment]
I was suggesting to increase the spacing between sections a bit. Something like this:
![space](https://user-images.githubusercontent.com/44577420/90637127-43afe880-e234-11ea-9941-c368364e9e29.png)

**Comment by hstastna** [comment]
@yfrimanm @matthewcarleton Hi folks, I need your look at the next approaches that were formed while working on this issue:

_Approach 1:_
To align the _Advanced CPU Topology Options_ expand/collapse section under the checkboxes like this:
![option1](https://user-images.githubusercontent.com/13417815/93789253-e98ab480-fc31-11ea-9c22-77dc1d3f5ae5.png)

_Approach 2:_
Or to align the section according to other options above, with the possibility to move the options with the checkboxes (Enable cloud-init and Start VM on creation) into the expand/collapse section, too (and to rename it to more general _Advanced Options_).
![option2](https://user-images.githubusercontent.com/13417815/93789270-ee4f6880-fc31-11ea-8d05-660524fe3687.png)

I prefer the approach 2 because it makes more sense to me and looks better. Also because I see no reason to place those two checkbox options under the _Optimized for_ drop down like how they are now, because they are not very related to the Optimized for option. However, if we wanted to change the width of those CPU Topology related drop downs, it might be problematic, as the width is styled according to the rest of the drop downs above and because of placing those drop downs in the expand/collapse section. But maybe the width of those drop downs is not a problem. I'm not sure. WDYT?

**Comment by matthewcarleton** [comment]
+1 to the second option. I agree with what you are saying in general -  I'd hope that the developer can make this change regardless of the layout issues. Should be a possible customization.

**Comment by yfrimanm** [comment]
I would definitely vote for the 2nd option and for renaming this section to
a more generic and shorter title such as 'Advanced'. Regarding the width of
the drop downs - TMO, ideally they should be consistent throughout the
whole form.
