### ISSUE TITLE
VM details card -> advanced options ->timezone value should be set correctly in case of null value

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1276]
This was raised here: https://github.com/oVirt/ovirt-web-ui/pull/1253#issuecomment-675833457

There is no default value consistency on UI while comparing to webadmin for sysprep timezone null value displayed on the VM details card -> advanced options ->timezone field value:
in case no value is set (null), the default value should be displayed as unset (greyed out) with a default of "(GMT) Greenwich Standard Time" value. Another option for fixing is to display it as an empty value (without suggesting any default).

**Comment by hstastna** [comment]
The solution I am finishing should be very similar to the behavior in Admin Portal (together with the proper TZ in the VM Details card after creating the VM): 
![configure_tz](https://user-images.githubusercontent.com/13417815/92153098-06e31480-ee24-11ea-8227-82fbbd5d7051.png)
![configure_tz2](https://user-images.githubusercontent.com/13417815/92153107-09456e80-ee24-11ea-9992-260849eb000d.png)
