### ISSUE TITLE
Keep dialogs consistent with webadmin by locating the primary action button to the left of the secondary action button

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1280]
Description of problem:
This was raised here: https://github.com/oVirt/ovirt-web-ui/pull/1239#issuecomment-676416329

A general design rule is that the primary action button (e.g. "OK") should located to the left of the secondary action button (e.g. "Cancel"). In other words, the 'OK' button is located on the left and the 'Cancel' will be on the right side.
This is a general design rule that is also used on GWT.

But on all web-ui dialogs, the buttons switched sides such that the primary action button (e.g. "OK") are located to the right of the secondary action button (e.g. "Cancel").
This should be fixed by replacing button sides for all web-ui dialogs.

**Comment by sjd78** [comment]
I disagree with this ask.

PF4 has Modal buttons to the left, and the primary action button left most: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal

PF3 has Modal buttons to the right, and the primary action button right most: https://www.patternfly.org/v3/pattern-library/forms-and-controls/modal-overlay/#design

Interesting to note that both PF3 & PF4 have the primary action button on the "outside", or closest to the edge. At least that is consistent.

So with web-ui being mostly PF3 at the moment, the pendulum should probably swing to the PF3 style, right aligned, primary to the right-most / outside.

**Comment by sgratch** [comment]
@sjd78 OK, I agree with that. 
Since the VM portal is a stand alone UI and we are currently not planning to migrate to PF4 then we can leave with that for now.

(Note that we'll still need to fix this issue for ui-extensions project (see bug https://bugzilla.redhat.com/show_bug.cgi?id=1870718) since both PF3 and PF4 dialogs are using the primary action button right most and since it's used together with GWT then it should be fixed for keeping the persistency).

**Comment by sgratch** [comment]
Since we decided to migrate web-ui to PF4 https://github.com/oVirt/ovirt-web-ui/labels/PF4, then this issue will be addressed as part of PF4 conventions.
Therefore I'm closing this issue.
