### ISSUE TITLE
The virt-viewer console file for SPICE is downloaded as a temp long file name and without the .vv extension

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1284]
This bug is a followup of bug https://bugzilla.redhat.com/show_bug.cgi?id=1638217 for handling the gap as mentioned on https://bugzilla.redhat.com/show_bug.cgi?id=1638217#c24.

The downloaded file, when trying to open the spice console via web-ui, includes a temp name and miss the .vv extension.
Check the attachment:
https://bugzilla.redhat.com/attachment.cgi?id=1713354&action=edit

Based on comment https://github.com/oVirt/ovirt-web-ui/pull/1243#pullrequestreview-445790046 we assumed that it's ok to download the file with a generated temp name (not sure since it's a bit ugly and long - so need to see how complicated it is to fix)  but with the .vv extension (not working and needed to be fix for sure).

**Comment by hstastna** [comment]
I cannot reproduce the issue with the missing .vv extension on both Firefox 80.1 and Chromium Version 85.0.4183.83 (Fedora 31). It works for me. After clicking on `Save` button in the dialog window (if opening in Virt/Remote viewer is not set as automatic for the used browser):
![vvv](https://user-images.githubusercontent.com/13417815/95104146-cbdf4400-0735-11eb-9dce-1c324a6aedb7.png)

**Comment by hstastna** [comment]
The problem with the .vv extension is present only for Firefox ESR (Version 78.3.1esr (64 bit) and also probably older) and for Firefox 80.0.1. For the newer Firefox 81, the problem does not occur. So it seems that the only remaining thing for fixing is the long temp file name.

**Comment by sgratch** [comment]
> The problem with the .vv extension is present only for Firefox ESR (Version 78.3.1esr (64 bit) and also probably older) and for Firefox 80.0.1. For the newer Firefox 81, the problem does not occur. So it seems that the only remaining thing for fixing is the long temp file name.

Officially, we need to support Firefox ESR version for RHEL and latest browsers versions for other OS:
https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/planning_and_prerequisites_guide/rhv_requirements#browser-requirements_RHV_planning

Is it too complicated to make it work for FF ESR?
