### ISSUE TITLE
Create VM Wizard Networking step user can't save new vnic

### ISSUE THREAD

**Issue by bamsalem** [oVirt/ovirt-web-ui#1299]
In Create VM Wizard in Networking step user can't save new vnic, it seems like an error that caused by PR #1219.
When the user Trying to save new Vnic nothing happens and in the console we can see that error thrown.
Screenshot:
![image](https://user-images.githubusercontent.com/64131213/94672044-62b69580-031d-11eb-9f28-06a36bf22725.png)
Steps to reproduce:
1. Navigate to create Vm wizard to networking step.
2. create new valid nic.
3. hit the save button.
The error appears in the console

**Comment by hstastna** [comment]
Reproduced 👍🏽 
IMHO, it wasn't caused by the PR you've mentioned. I think the cause is combination of more changes.
