### ISSUE TITLE
Create VM Wizard - on basic settings step the cluster pull down should include only clusters with at least one assigned host

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1313]
When creating a new VM on basic settings step, the options for the Cluster menu field are only those clusters that include at least one host (host status is not relevant). The VM can't run on a cluster without any host assigned, so those clusters should be blocked for vms creation..

Currently all existed clusters are displayed.

**Comment by hstastna** [comment]
I think this issue is part of the https://github.com/oVirt/ovirt-web-ui/issues/1307
