### ISSUE TITLE
Create VM Wizard - VM Name field validation failure on basic settings step is missing an info text

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1321]
In case of setting an invalid VM name on Create VM Wizard->basic settings step, the field is marked in red and next step button is disabled but there is no indication for the reason of the validation failure and what should be fixed. 
We need to add a tooltip or an info text next to the field.

This was the behaviour on old user portal as well:
![image](https://user-images.githubusercontent.com/18169498/97906446-570b2400-1d4c-11eb-8180-bb147c13cc7f.png)

**Comment by hstastna** [comment]
I think such messages to inform the user would be useful not only for the _Name_ field but all other fields in the Basic settings step, and not only when the field validation fails. Related comment: https://github.com/oVirt/ovirt-web-ui/pull/1318#pullrequestreview-521653103

**Comment by sgratch** [comment]
> I think such messages to inform the user would be useful not only for the _Name_ field but all other fields in the Basic settings step, and not only when the field validation fails. Related comment: [#1318 (review)](https://github.com/oVirt/ovirt-web-ui/pull/1318#pullrequestreview-521653103)

I won't add too many validations if not important since we already have that logic on backed and webadmin frontend so we don't want to duplicate this validation code too much. 
I would add it only when necessarily important for the user flow. For other flows, let it fail on backend. Anyway I agree with adding it for #1318.

**Comment by isaranova** [comment]
LGTM
