### ISSUE TITLE
VM Portal crash when refreshing data or performing a VM action (SyntaxError: JSON.parse)

### ISSUE THREAD

**Issue by pnovotny** [oVirt/ovirt-web-ui#1336]
Description of problem
VM Portal crashes when trying to refresh the VM data manually or when trying to perform a VM action (run/suspend/shutdown or go to VM detail).

VM Portal version number:
ovirt-web-ui-1.6.6-0.20201126.git909add4.el8.noarch

oVirt version number:
ovirt-engine-4.4.4.2-0.1.el8ev.noarch

Browser and version:
Firefox 83
Chromium 87

Steps to Reproduce:
1. Log into  VM Portal (tried with UserRole and SuperUser).
2. Wait for VMs to load.
3. Click the refresh icon in VM Portal 
  or go to a VM detail. 
  or try to run/suspend/shutdown a VM.

Actual results:
VM Portal crash:
[Firefox] `Uncaught saga error (store.js):  SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` 
[Chromium] `Uncaught saga error (store.js):  SyntaxError: Unexpected token u in JSON at position 0`

Expected results:
No crash.

Additional info:
screenshot (Firefox)
![web-ui-refresh-crash](https://user-images.githubusercontent.com/314377/100857149-a435ff00-348c-11eb-835a-563718d4c24d.png)

**Comment by hstastna** [comment]
I tried to reproduce this issue but it works as expected.
