### ISSUE TITLE
Edit VM available clusters list includes clusters with different architecture

### ISSUE THREAD

**Issue by bamsalem** [oVirt/ovirt-web-ui#1350]
The cluster list in Edit VM dialog includes clusters with different architecture,
The VM cannot migrate to cluster with a different architecture.

**Actual results:**
![image](https://user-images.githubusercontent.com/64131213/102199047-cd628080-3ecb-11eb-975a-48ea1d32392f.png)

**Expected result:** 
Filter clusters that have different architectures from the current cluster.

**Comment by sgratch** [comment]
@bamsalem wasn't that fixed by https://github.com/oVirt/ovirt-web-ui/pull/1351 already?

**Comment by bamsalem** [comment]
Yes, it's already fixed by #1351
