### ISSUE TITLE
Create VM Wizard- create disks storage domain issues

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1366]
This is a follow up issue for an already merged PR #1323 regarding storage domains management during a creation of a VM with disks (original commect: https://github.com/oVirt/ovirt-web-ui/pull/1323#issuecomment-775954746):

**1.** When creating a VM based on a template while the template includes more than 1 disk and is optimized to "server" or a clone is required due to SD permissions then the following error still occurs:
"CREATE_VM failed [Cannot add VM. One or more provided storage domains are either not in active status or of an illegal type for the requested operation.]"

This was already mentioned above on issue 3 of https://github.com/oVirt/ovirt-web-ui/pull/1323#issuecomment-728239827 and claimed to be fixed:
>  3.       When trying to create a VM based on a "server" template with two disks OR when trying to create a VM based on a template with no permissions for the template's two disks SD, then for both cases the VM creation failed on backend with the following error (I guess the issue is due to the two disks that needed to be cloned at once, while image is locked or something like that):
> 
> Fixed! There was an error in the way multiple disk changes were being merged to the new VM request. Creation of VMs from multi-disk templates cloning the disk to a new storage domain works just fine now.

**2.** when there are no permissions for all SDs , both previous and next buttons are disabled:
![image](https://user-images.githubusercontent.com/18169498/107372053-aac89e80-6aed-11eb-96e2-c970527a0494.png)

**3.** when there are no permissions for a template disks SD and the user can choose a different SD, the previous button is disabled till all SD are selected. This is wrong:
![image](https://user-images.githubusercontent.com/18169498/107372326-f5e2b180-6aed-11eb-9d57-6768e2a142c4.png)

**4.** when the user tries to create a disk not based on  a template and there are no permissions for current SDs, the SD field is marked as red and buttons are disabled, but no message is displayed:
![image](https://user-images.githubusercontent.com/18169498/107373293-0e070080-6aef-11eb-84ea-1d24f252d166.png)

**Comment by sjd78** [comment]
> This is a follow up issue for an already merged PR #1323 regarding storage domains management during a creation of a VM with disks (original commect: [#1323 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1323#issuecomment-775954746)):
> 
> **1.** When creating a VM based on a template while the template includes more than 1 disk and is optimized to "server" or a clone is required due to SD permissions then the following error still occurs:
> "CREATE_VM failed [Cannot add VM. One or more provided storage domains are either not in active status or of an illegal type for the requested operation.]"
> 
> This was already mentioned above on issue 3 of [#1323 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1323#issuecomment-728239827) and claimed to be fixed:

This ends up being a bug on the REST api where it required ALL disks to be specified on the create request, not just disks that needed modification.  I've addressed this, along with a bit of missing business logic, in [patch 114092](https://gerrit.ovirt.org/c/ovirt-engine/+/114092) for ovirt-engine's rest api.

**Comment by sjd78** [comment]
> > This is a follow up issue for an already merged PR #1323 regarding storage domains management during a creation of a VM with disks (original commect: [#1323 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1323#issuecomment-775954746)):
> > **1.** When creating a VM based on a template while the template includes more than 1 disk and is optimized to "server" or a clone is required due to SD permissions then the following error still occurs:
> > "CREATE_VM failed [Cannot add VM. One or more provided storage domains are either not in active status or of an illegal type for the requested operation.]"
> > This was already mentioned above on issue 3 of [#1323 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1323#issuecomment-728239827) and claimed to be fixed:
> 
> This ends up being a bug on the REST api where it required ALL disks to be specified on the create request, not just disks that needed modification. I've addressed this, along with a bit of missing business logic, in [patch 114092](https://gerrit.ovirt.org/c/ovirt-engine/+/114092) for ovirt-engine's rest api.

PR #1400 should solve bullet point 1.
