### ISSUE TITLE
Create VM Wizard- disk type of new disks based on a 'server/HP' template should be based on the template's disk allocation policy

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1371]
This is a follow up issue for an already merged PR #1323 :
As mentioned on https://github.com/oVirt/ovirt-web-ui/pull/1218#issuecomment-640753874 and on https://www.mail-archive.com/users@ovirt.org/msg65180.html then we need to fix current behavior so that disks allocation policy (disk type) of new cloned disks based on a 'server/High Performance' template should be the same as the template's disk and not always set to preallocated.

**Comment by sjd78** [comment]
To see the reported behavior, the "Optimized For" field must be "Server".  Doesn't matter if the template is set as Server by default or if it is selected on the basic details step.  The current code automatically forces "Preallocated" for all template defined disks when optimized for is "Server".

When "Optimized For" is "Desktop", the template disk types are set as defined in the template.

**Comment by sjd78** [comment]
Further, in webadmin:

If the new VM optimized for is **Server** (template or user selected):
  - Storage allocation defaults to **Clone**
  - Disk types (labeled as "Format" on the disk allocation table on the resource allocation tab) defaults to the type selected in the temlpate itself
  - Disk types are editable

If the new VM optimized for is **Desktop** (template or user selected):
  - Storage allocation defaults to **Thin**
  - Disk types (labeled as "Format") are defaulted to "QCOW2" (Raw == "Preallocated", QCOW2 == "Thin Provision")
  - Disk types are not editable

Current web-ui behavior:
  - Storage allocation equates to setting the "clone" attribute true when creating the VM.  This setting is consistent with the default storage allocation webadmin selects based on the optimized for field.
  - Disk types are never editable for template defined disks
  - Disk types selected for template defined disks are not consistent with webadmin.  Desktop keeps the template defined disk type, which is backward from webadmin.  Server forces the template defined disk type to "Preallocated", which is also backward from webadmin.

Changes to be made to be consistent with webadmin and address the issue report on the mail list:
  - For **Desktop**, have the disk type forced to "Thin Provisioned" for all template defined disks.
  - For **Server**, have the disk type use the template definition.
 
@sgratch , @rszwajko , @hstastna - Thoughts?

**Comment by hstastna** [comment]
I think setting the disk types should be consistent with how it works in webadmin. I don't see any reason to do it differently in web-ui.

> For Desktop, have the disk type forced to "Thin Provisioned" for all template defined disks.

I agree with that.

> For Server, have the disk type use the template definition.

In webadmin, the default disk types are based on the selected template but still editable. To make the web-ui behavior 100% same as in webadmin, we should implement this, too. But I don't consider this as important as the other changes mentioned by @sjd78 in the comment above and I'm not sure if it worth.

**Comment by sjd78** [comment]
See comment https://github.com/oVirt/ovirt-web-ui/pull/1400#issuecomment-825812371 in PR #1400 for a list of test cases for creating VMs from a Template via webadmin for comparision to how web-ui will create them once this issue is solved.

**Comment by isaranova** [comment]
LGTM
