### ISSUE TITLE
user settings - reset option back to default/installation settings is missing

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1390]
Original User Settings design is available here ->https://docs.google.com/document/d/1apA6E4zT21JSJgeO2V3Q_LhK9xq4SOwNeD-gIsG5pNY/edit?pli=1#heading=h.mkd1w7uwr9hs

For more details, check https://github.com/oVirt/ovirt-web-ui/pull/1088#issuecomment-734439359 (issue 12)

**Comment by rszwajko** [comment]
**Original design**

https://marvelapp.com/prototype/94h0g56/screen/59286966

IMHO we can skip the message next to the button ("Default settings applied") and just disable the button if there is nothing to reset (defaults are used).
Adding the label explaining the state might be required  when/if the settings hierarchy would get complex but right now it seem not necessary.
