### ISSUE TITLE
user settings - notification settings are not persisted

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1391]
Notification settings are not persisted. this is not saved on engine db or at all (neither on local storage). For 5 mins disabling it's OK but for an hour and more - it's not. This is user settings so it should be persistent for the user.
For more details, check https://github.com/oVirt/ovirt-web-ui/pull/1088#issuecomment-734439359 (issue 11)

**Comment by rszwajko** [comment]
@sgratch 
> But it worth adding this information as an alert info field displayed within the dialog,
>

PatternFly 4 recommends [hint component](https://www.patternfly.org/v4/components/hint/design-guidelines) in similar scenario.
See #1580 for screenshots.

**Comment by sgratch** [comment]
> @sgratch
> 
> > But it worth adding this information as an alert info field displayed within the dialog,
> 
> PatternFly 4 recommends [hint component](https://www.patternfly.org/v4/components/hint/design-guidelines) in similar scenario. See #1580 for screenshots.

The hint component is not used on other web-ui dialogs where the `alert - info` component is used (e.g. snapshots creation as mentioned above and "pending configurations" info as mentioned below), so this adds inconsistency to the "pre PF4 massive upgrade" ui. 

![image](https://user-images.githubusercontent.com/18169498/163992207-b135d703-d44f-4576-9f74-e5d079102f1e.png)

@rszwajko worth fixing now or is it part of PF4 upgrade pr?

**Comment by rszwajko** [comment]
> The hint component is not used on other web-ui dialogs where the `alert - info` component is used (e.g. snapshots creation as mentioned above and "pending configurations" info as mentioned below), so this adds inconsistency to the "pre PF4 massive upgrade" ui.
>

The hint component will be used instead of info alert after migration to PF4 check screenshots in https://github.com/oVirt/ovirt-web-ui/pull/1540
