### ISSUE TITLE
user settings - consider enable/disable option for persisted locales

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1393]
Since "landing page" locales and "user settings" for web-ui locales integration is partially supported, consider enable/disable persisted locale as mentioned on "issue 5" of previous comment https://github.com/oVirt/ovirt-web-ui/pull/1372#issuecomment-791576420

**Comment by rszwajko** [comment]
**Background**

We have 3 storage options right now:
1.    server-side - persisted as part of user profile i.e. refresh interval
2.    client side - persisted in local storage i.e. locale or legacy console settings
3.    Redux store (in-memory) - i.e. notifications

Those options are not mutually exclusive - all options are in Redux store and locale is both server and client side(currently).

**Basic use case**

Some user might depend on passing the locales via URL (from landing page) and might not want to have this option persisted on the server. Currently this is the only item we want to support.

**Generic use case**

In the future we can expect more options that  need opt-out feature. IMHO the first candidate are (global) console settings.
Adding multiple "opt-out" check boxes or switches would make the UI unreadable so my idea was to group such options under a dedicated section.
There are few naming and layout options (to be decided which fits the best):
1. section: simply "Storage" or "Persistence" or similar
2. storage modes :
    1. on/off (via switch  or checkbox) - "on" means that option is saved on the server
    2.  server-side/local/in-memory (via dropdown) - the most flexibility

**Simple mockup**

![storage_options](https://user-images.githubusercontent.com/64194103/116229728-2504d880-a757-11eb-9fba-9c6ebcae936b.png)

**Comment by rszwajko** [comment]
Original User Settings design is available here -> https://marvelapp.com/prototype/94h0g56/screen/59286965
