### ISSUE TITLE
Upgrade noVnc version 

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1395]
This is required to me compatible with engine upgrade, check bug: https://bugzilla.redhat.com/show_bug.cgi?id=1931367 targeted to 4.4.6.
current supported version is novnc-1.1.0.

**Comment by rszwajko** [comment]
@sgratch the bug above was closed as WONTFIX. Should we follow?

**Comment by sgratch** [comment]
> @sgratch the bug above was closed as WONTFIX. Should we follow?

Yes, I'll close this as WONTFIX as well. Thanks
