### ISSUE TITLE
A new build error appears after adding the semver package dependency

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1418]
The following build error started to appear after merging https://github.com/oVirt/ovirt-web-ui/pull/1384:

The previous build log contains no such messages.
FAILED 	Build Log 	Python syntax errors during compilation seen in noarch build log:
    400  Error in static/js/main.676df22d.js from UglifyJs
    401  SyntaxError: Unexpected token punc «,», expected punc «:» [./~/semver/internal/constants.js:13,0]

E.g. check https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-on-ghpush/301/consoleFull#L1,962

**Comment by rszwajko** [comment]
Our UglifyJs version seems also to have problems with other libraries.
Example of build error from #1427 
```
Error in static/js/main.de12d06c.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/@patternfly/react-icons/dist/js/createIcon.js:13,0]
```

**Comment by sjd78** [comment]
Note: This should go away once #1359 is merged.

**Comment by sgratch** [comment]
> Note: This should go away once #1359 is merged.
True, those build errors don't exist anymore after merging #1359.
Therefore, closing this issue as DONE.
