### ISSUE TITLE
user settings - need to inform the user that all sections/tabs actions (save/cancel/reset) are applied to all tabs

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1440]
This is a follow up issue for https://github.com/oVirt/ovirt-web-ui/pull/1427#issuecomment-851608502
It is not clear for the user to understand that all user settings dialog actions (save/Cancel/Reset settings) are applied to all tabs in once and not only the current user settings tab.
Maybe it worth just mentioning it within a tooltip/confirmation dialog so that the user will be aware of that.

**Comment by rszwajko** [comment]
Partially addressed in #1446 - confirmation dialog shows section titles.
