### ISSUE TITLE
Review docker container build (locally, via make, via CI on std-ci or travisci)

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#1442]
We need to review the usefulness and validity of the container build of ovirt-web-ui.

There are a few items to consider:
 1. Do we still need the container build?
 2. Should the container be running the webpack dev server or use another build/deploy mechanism that does not require compiling every time it runs?
 3. Is docker hub the best place to continue publishing the container?  Maybe quay.io or something else RH provides?
 4. Should the CI build scripts login to the target container registry to avoid rate limiting etc?
 5. ~~Should travisci still be used to build the container or can that be ported to std-ci?~~ travis-ci.org is shutdown as of June 15, so the container build will need to be ported to another ci build environment (travis-ci.com or std-ci).
 6. Should we migrate from docker to podman/buildah?

Currently, the build via travisci is frequently failing.  For example see https://travis-ci.org/github/oVirt/ovirt-web-ui/builds/773732433#L351.  Additionally, travis-ci.org is due to shutdown in favor of travis-ci.com.  We may need to migrate anyway.

**Comment by sjd78** [comment]
@michalskrivanek , @sgratch , @rszwajko , @hstastna - Thoughts and comments?

**Comment by michalskrivanek** [comment]
IMHO it's not widely used, if ever. So it's certainly something we can consider to ditch. Otherwise we would have to fix and improve 2-6...probably not worth it

**Comment by sjd78** [comment]
Good article about dockerizing react app https://mherman.org/blog/dockerizing-a-react-app/

It isn't 100% applicable (missing the user login from ENV vars, missing the api proxy), but would be a good base.

**Comment by sjd78** [comment]
**Note**: travis-ci.org is shutdown as of June 15.
