### ISSUE TITLE
User settings dialog

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#145]
User can customize application behavior.
Data persisted to local storage and/or database, depending on the setting.

Designs:
https://docs.google.com/document/d/1apA6E4zT21JSJgeO2V3Q_LhK9xq4SOwNeD-gIsG5pNY/edit

Ideas for settings we'd need:

- "Filter: false" for admins (check box) (Greg: still needed or relevant?)
- refresh interval (recently 1 minute) (Greg: admins might not like this)
- open your favorite VM's console automatically after login to VM Portal
- don't confirm when user tries to force power off VM
- don't confirm when XYZ
- toast notification settings (disable, maybe move their location)
- locale
- user info (typically centralized, though)
- session time out (might want only admins to be able to set)
- screen mode (full screen - see https://bugzilla.redhat.com/show_bug.cgi?id=1667517)

**Comment by michalskrivanek** [comment]
it's good as a start.
As for "do not show this again" warning dialogs - we can also have a single "reset all warnings" option here to avoid enumerating them all

**Comment by mykaul** [comment]
Can you add a screenshot?

**Comment by mareklibra** [comment]
@mykaul , so far we are just planing, implementation has not yet started.

**Comment by jelkosz** [comment]
@mykaul btw is there something else you always wanted to have configurable on frontend and it just was not there?

**Comment by mykaul** [comment]
- UX timeout per user (or global)
- Default tab per user.
- Default search (bookmark) - I remember we used to have it or something in the past?

It would be nice to have a UI for engine-config of course, but that's an overkill.

**Comment by michalskrivanek** [comment]
this is worth scoping further

**Comment by gregsheremeta** [comment]
I'll bring this up in redesign, but it's probably out of scope

**Comment by gregsheremeta** [comment]
* setting for asking user about Single Sign On dialog warning

**Comment by lwrigh** [comment]
Feel free to add any ideas you have about user settings in VM portal into the design doc that's featured in the issue description.
