### ISSUE TITLE
Created VM has incorrect number of CPUs

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#1473]
Description of problem:
VM is created with incorrect number of CPUs that does not match the one in VM Wizard.

VM Portal version number:
ovirt-web-ui-1.7.1-0.20210706.gite5aa3f3.el8.noarch

oVirt version number:
ovirt-engine-4.4.8-0.0.master.20210706164306.git8e41812880d.el8.noarch

Browser and version:
firefox-82.0.2-1.fc31.x86_64

Steps:
1) Create VM with maximum number of CPUs (384 for my cluster)

![Screenshot_2021-07-07 VM Portal(3)](https://user-images.githubusercontent.com/39263962/124767783-67f1e200-df38-11eb-812b-d25f10915169.png)

3) Go to the VMs details and check the number of CPUs
The number of CPUs is only 1:

![Screenshot_2021-07-07 VM Portal(4)](https://user-images.githubusercontent.com/39263962/124767870-793aee80-df38-11eb-951e-7728fa6f4a26.png)

Actual results:
Wrong number of CPUs.

Expected results:
Correct number of CPUs or an error message.

Additional info:
On the previous version of webui, there was an error message, that such number of CPUs was not possible. However, the VM could still be created with that number, if user went back to the first step and clicked on the up arrow for the CPUs number (the number itself didn't change, stayed the maximum).

**Comment by sjd78** [comment]
Very strange, if you type in 384 (the max vCPUs on a 4.4 compat version cluster), the topology fields are correct.  Therefore the CPU count will be saved properly.

If you then up arrow to try to go to 385, the change is prevented.  HOWEVER, the topology is broken.  The topology calc at the edge of the  range is not doing the right thing.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/3985964/124795045-a75f0500-df1d-11eb-81ee-759bd3537fef.gif)

**Comment by sgratch** [comment]
This seems somehow related to https://github.com/oVirt/ovirt-web-ui/issues/1431
Assigning to Hilda for checking this as well.
