### ISSUE TITLE
no sound on vdi  windows 8 

### ISSUE THREAD

**Issue by kevinm9** [oVirt/ovirt-web-ui#1480]
[ Thank you for submitting an issue to the VM Portal issue tracker. Please read these instructions and delete this section before submitting your issue. ]

[ If this is a bug report, use this section and delete the other one: ]

Description of problem [include screenshots and browser console logs]:

VM Portal version number:

oVirt version number:

Browser and version:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

Additional info:

[ If this is a request for a feature or enhancement, use this section and delete the other one: ]

Feature enhancement request:
[ Describe the feature or enhancement you would like. Be as detailed as possible, including screenshots or links to design documents. ]

**Comment by sgratch** [comment]
@kevinm9 there is no content inside this issue description so closing.
Please open a new one if needed.
