### ISSUE TITLE
Network interfaces edit mode cancel button does not undo the changes

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#1492]
Description of problem:
When you go to the edit mode (create NIC, edit/delete NICs appears), there are two buttons (cancel and save according to the HTML code), however, both work exactly the same, the cancel does not undo the changes made, and is basically the same as the save button.

VM Portal version number:
ovirt-web-ui-1.7.0-1.el8ev.noarch

oVirt version number:
ovirt-engine-4.4.8.1-0.9.el8ev.noarch

Browser and version:
firefox-82.0.2-1.fc31.x86_64

Steps to Reproduce:
1. Log in to VM Portal (with roles/permissions that allow the user to edit network interfaces on VM)
2. Go to VM details
3. Click on the edit icon in the Network interfaces card
4. Edit/create/delete NICs
5. Click on the cancel button

Actual results:
Changes are still present, the button works just like the save button.

Expected results:
Either only one button for leaving the edit mode is present, or the cancel button actually reverts the changes made. In my opinion, the snapshots card without the edit icon is easier to use and the same pattern could be used for the network interfaces and disks card as well.

**Comment by sgratch** [comment]
I totally agree with that. This was part of the original design AFAIK but I never understood why we need those 2 buttons save and cancel if they do the same thing. I think it was added just for keeping the UI unified with details and overview cards.
@sjd78 any thoughts on this?

**Comment by hstastna** [comment]
I remember we were talking about that about a year ago and found that it is a part of the design. And the 2 buttons are there for consistency with rest of the UI and the Patternfly style.

**Comment by sgratch** [comment]
> I remember we were talking about that about a year ago and found that it is a part of the design. And the 2 buttons are there for consistency with rest of the UI and the Patternfly style.

Right, I remember the same. But from UX POV I agree with Ivana that it's very confusing to edit/create a disk/Nic without the ability to revert it with the Cancel button. For all other cards the Cancel button does have a meaning while for Nics/Disks/Snapshots the action was already operated before clicking the buttons so it's a problem to revert.
We can consider changing it to look like the snapshots card.

**Comment by sgratch** [comment]
Since it is part of the original design and no real functionality is missing then let's keep that as is.
