### ISSUE TITLE
add a "communicating with server" or similar

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#153]
Sometimes the server call can take a long time to process (for example when opening a console) and it is not obvious if the server call did not finish yet or something failed or what happened.

It would be nice to have something similar than the "Loading..." in gmail to indicate that now the FE is actually waiting for a response from server - it did not fail yet and did not finish yet.

**Comment by mareklibra** [comment]
When the app is starting, there's spinner with following message:

    Data are being loaded ...

Later on, when an action is issued, it's icon becomes disabled until it's finished (means response from server is received, resp.).

What about replacing the action's icon by a spinner in that case?

So the 'disabled" icon state would be reserved just for situation where "something is not met" to run the action (ie. the VM is not running to shut it down).

I was further thinking about a spinner on the page header or even the "Loading ..." patternfly allert.

**Comment by mykaul** [comment]
It should be at least 'Data is being loaded'.

**Comment by jelkosz** [comment]
> What about replacing the action's icon by a spinner in that case?

Im afraid it would be pretty hard to get this right in a way that it actually looks good.

> I was further thinking about a spinner on the page header or even the "Loading ..." patternfly allert.

I think the simple "Loading ..." on top of the screen is enough to start with.
