### ISSUE TITLE
GitHub web hooks for docker.com not working anymore

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-web-ui#1530]
Description of problem:
GitHub Web hooks for docker.com are currently in failed state for a long while.

We should either fix the integration with docker or drop them

**Comment by sjd78** [comment]
Required #1442

**Comment by michalskrivanek** [comment]
+1 on dropping

**Comment by sjd78** [comment]
Along with merging #1630, the webhooks can be removed at any time.

**Comment by sjd78** [comment]
@sgratch, @michalskrivanek - With PR #1630 removing broken docker support, any webhooks on this repo configured to docker or dockerhub should be removed.

**Comment by michalskrivanek** [comment]
docker hooks dropped, as well as two old jenkins hooks, hopefully no one is going to miss them...
