### ISSUE TITLE
packaging: ovirt-engine-nodejs-modules is needed for running configure

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-web-ui#1531]
I'm trying to build ovirt-web-ui within copr but I can't provide a package which is not included in Fedora 34 for building the src.rpm.
As a result, I'm currently stuck at `configure` time when it fails due to missing `yarn` executable requiring to install ovirt-engine-nodejs-modules for providing it.

**Comment by sjd78** [comment]
Resolved by #1534

With copr, as long as ovirt-engine-nodejs-modules is present in the same project, and has an appropriate build, it should be able to be installed by the chroot.  So should be all good to go now that nodejs-modules is building properly in copr.
