### ISSUE TITLE
Wrong disk utilization

### ISSUE THREAD

**Issue by ahadas** [oVirt/ovirt-web-ui#1553]
Description of problem [include screenshots and browser console logs]:
Wrong percentage for disk utilization
![image](https://user-images.githubusercontent.com/6020068/148349109-dc43468e-a9eb-4441-8479-cc6a0fb1f8ec.png)

oVirt version number:
4.4.9.5

Actual results:
Disk2 looks OK but Mouse over Percent is wrong (see attached Screenshot)

Expected results:
Percentage should be correct

Additional info:
See https://bugzilla.redhat.com/show_bug.cgi?id=2036947

**Comment by sgratch** [comment]
This is a duplicate issue for #1535 (handled by #1541) and therefore closing as DUPLICATE.
