### ISSUE TITLE
:exclamation: EL9 build fails (nodejs 16 and openssl 3.x)

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#1568]
PR #1563 adds a CI build on EL9 / CentOS Stream 9.  The EL9 test jobs will fail until the project is upgraded to at least webpack v5.61.0.  See https://github.com/webpack/webpack/issues/14532 for details, specifically my comment: https://github.com/webpack/webpack/issues/14532#issuecomment-1027158606.

I chatted with a few other people and did some tests looking at building webpack on el9.  The root cause looks to be the openssl version installed.  The openssl 1.x line (on el8) with nodejs <17 works well.  The openssl 3.x line (on el9) with nodejs >=16 fails.  I found no difference between the dnf repo rpm package vs the direct download of nodejs (which is what openshift console does in its build container).  Both of them fail in the same way.

Net result: upgrading webpack to at least 5.61.0 is the only reasonable way to support building the project on EL9.

**Comment by sgratch** [comment]
This depends on migrating Patternfly 3 to Patternfly 4 first: https://github.com/oVirt/ovirt-web-ui/pulls?q=is%3Apr++label%3APF4+

**Comment by sgratch** [comment]
@sjd78 this can be closed now as DONE, right?

**Comment by sjd78** [comment]
> @sjd78 this can be closed now as DONE, right?

Yes.  This Issue is solved and DONE.
