### ISSUE TITLE
Pools data label colors are all use the same color for all pools while before for each pool there was a different color 

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1621]
Before migrating to PF4, the pools data label for each pool (displaying pool name/pool vm name) was in a different color as part of the design and as an easy way to distinguish between pool vms and pool entity of a pool. 
Now all such labels use the same green color.
Worth fixing.

Before PF4 migration:
![image](https://user-images.githubusercontent.com/18169498/180484323-487072dc-32a7-4c7a-80cb-d225f0ed6ee1.png)

Now:
![image](https://user-images.githubusercontent.com/18169498/180484150-b861e981-eebe-4330-8abc-28b29213cc57.png)

VM Portal version number:
1.9.1-0

**Comment by rszwajko** [comment]
@sgratch  
The colors worked correctly for me - tested on version 1.9.1-1.
Note that [the algorithm](https://github.com/oVirt/ovirt-web-ui/blob/d51d4f337a21e4584709843f4ca1d64c122dd030/src/ovirtapi/transform.js#L108) behind color calculations does not guarantee unique color for each pool.

**Comment by sgratch** [comment]
@rszwajko It is not reproduced to me anymore on latest version 1.9.1-1 as well. It might be accidentally reproduced or something else but since it's not reproduced then closing this as WORKSFORME
