### ISSUE TITLE
Add 'Create VM from Template'

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#17]
Basic Add/Edit functionality provided by ~~https://github.com/oVirt/ovirt-web-ui/pull/161~~.

For follow-ups:

 [x] update yarn.lock
 [x] The "Description" property
 [x] Render template version
 [x] Fix form update after template change
 [x] Confirm dialog Cancel if changes
 [x] Refactoring of remaining reducers
 [x] Use existing UserMessages instead of specific vmDialogReducer
 [x] Add [help](https://www.patternfly.org/pattern-library/forms-and-controls/field-level-help)

**Comment by mareklibra** [comment]
https://github.com/oVirt/ovirt-web-ui/pull/98

**Comment by mareklibra** [comment]
Closed by mistake, not yet finished

**Comment by mareklibra** [comment]
![01](https://cloud.githubusercontent.com/assets/17194943/25433996/e0569770-2a8a-11e7-806a-916b00b19ba5.png)
![02](https://cloud.githubusercontent.com/assets/17194943/25433999/e05810be-2a8a-11e7-9212-ca7cd2008ae5.png)
![03](https://cloud.githubusercontent.com/assets/17194943/25434001/e059069a-2a8a-11e7-911d-85b2a5a36130.png)
![04](https://cloud.githubusercontent.com/assets/17194943/25433997/e056eacc-2a8a-11e7-8cc3-ea8e72cf8df4.png)
![05](https://cloud.githubusercontent.com/assets/17194943/25434000/e0580560-2a8a-11e7-97ed-190c5f6a8aff.png)
![06](https://cloud.githubusercontent.com/assets/17194943/25433998/e0575fca-2a8a-11e7-8524-c9b88e76600e.png)

**Comment by mykaul** [comment]
@mareklibra  : Vm -> VM

**Comment by mareklibra** [comment]
done
