### ISSUE TITLE
Unify VM status icons

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#173]
I'd find more visually pleasant and self-explanatory to use same set of icons to express VM state as we currently use for actions like start a VM:

* ▶  running vm (in green)
* ⏸ suspended vm
* ■ stopped vm

instead of current circled icons.

![screenshot](https://cloud.githubusercontent.com/assets/5278760/25448604/48805f42-2ab9-11e7-9c33-2423075f3f37.png)

---
Fixed by: 
 - https://github.com/oVirt/ovirt-ui-components/pull/39
 - https://github.com/oVirt/ovirt-web-ui/pull/177

**Comment by mareklibra** [comment]
For running and Down VMs:

![runninganddown](https://cloud.githubusercontent.com/assets/17194943/25475550/66c8ffe4-2b37-11e7-8540-f19d876b57d5.png)

I prefer more the former fa-power-off over this fa-square, what others think? @matobet , @jelkosz

**Comment by mareklibra** [comment]
For VM being rebooted:
![vmbeingrebooted](https://cloud.githubusercontent.com/assets/17194943/25475629/a76937da-2b37-11e7-843e-d9c33ff900aa.png)

**Comment by jniederm** [comment]
https://github.com/oVirt/ovirt-web-ui/issues/173#issuecomment-297653875 looks great. The square really doesn't feel self-explanatory enough. Maybe it can be rearranged like for example

* start
* suspend
* stop
* reboot
* console
* edit

to group "player control symbols" together. But fa-power-off is also good.

**Comment by mareklibra** [comment]
rearranging makes sense
+  fa-power-off

**Comment by mareklibra** [comment]
So, after recent changes:
![actionsrearanged](https://cloud.githubusercontent.com/assets/17194943/25527352/ba73548c-2c18-11e7-9735-ca193d10c677.png)
