### ISSUE TITLE
when trying to copy the error message from messages, the dialog gets closed

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#189]
the flow is this:
- have some action which fails on backend (e.g. run a VM which can not be ran)
- open messages in top right corner
- highlight using mouse the error message
- the dialog gets closed (should stay opened)
- open the dialog again and the msg is highlighted (well, not sure if bug or feature, but strange :) )

**Comment by mareklibra** [comment]
Fixed.
The component stays rendered unless the user clicks again either on the "Messages" or newly added "close" link.

Please reopen if still not fine.
