### ISSUE TITLE
visual issues with connect automatically

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#193]
- The "connect automatically" has a different font than the rest of the labels in the dialog.
- there is a large vertical space under the "connect automatically" button and the rest of the dialog (disks)

![differentfont](https://cloud.githubusercontent.com/assets/701107/26156139/b45a4a5e-3b15-11e7-9306-7ffeedbe3df9.png)

**Comment by jelkosz** [comment]
also it would be nice to have a question mark next to the "connect automatically" explaining what does it actually do since it is a very unintuitive feature.

**Comment by mareklibra** [comment]
Fixed by https://github.com/oVirt/ovirt-web-ui/issues/31
