### ISSUE TITLE
Redesign > Pools

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#195]
In the current basic user portal the approach of showing the VMs and pools is to show them in one screen in a way that from user perspective they are as much indistinguishable as possible. 
The reason for this is:
- If Im a user and want to use a VM, I should not care if the VM is part of a pool or a normal VM, it should be hidden as an "implementation detail" done by administrator
- If I have the right to take a VM from a pool, I see the same cube as for VM. If I click run, it turns into a VM and I should not even notice the difference.

There are some disadvantages to this approach:
- this design has been invented when one user could have only one VM from the pool, but since ~4 years ago the user can have more VMs from one pool. This behavior became a bit confusing because while clicking run on the pool cube, the pool cube which looks like a VM cube suddenly splits of to two cubes and without knowing that this was a VM taken from pool, it does not make sense (e.g. the "implementation detail" has to leak in order the behaviour to make sense)
- there might be pool specific actions on the pool (for example mass actions on it's VMs - e.g. restart or return all) or things like delete the pool including it's VMs.
- the user does not know how many VMs can he still take from the pool

So I think now it is a good time to rethink the way how do we present the pools. After an offline discussion with @michalskrivanek @matobet and @bond95 we came to something I will try to summarize here:
- do not split the presentation of VMs and Pools into two subtabs because they are still way too related
- the differentiation will be done by some visual indication in the pool cube (e.g. different border? different background colour? overlay image over the OS Type image?)
- the pool cube will not disappear even if you have taken all the VMs from it
- the pool cube will have a label showing how many VMs can you take from this pool. (for example: "3 more VMs available from this pool")
- bonus points: find a visual indication how to show on the page where you see all cubes that this VMs are related together and are all from that particular pool. Anyone any idea?

@gregsheremeta @mykaul @jniederm @mareklibra what you guys think?

---
[GS: edits]

Final design doc: https://docs.google.com/document/d/1G8ROKv_Talwh3c_drDglxM03zdOWoW-cAWt2-2zVqqk/edit

![selection_264](https://user-images.githubusercontent.com/2248293/50360743-0eb73400-052f-11e9-8ae8-eb7bf6c05c82.png)

**Comment by mareklibra** [comment]
Makes sense for me.

Regarding the "visual indication", I would "multi-line" the border, like "there's stack of cards". This will indicate at the first glance, there's "something multiplied". But it might be tricky to implement.

Plus card's tooltip might show something like "This is a pool of virtual machines."

There's still a lot of white space on recent cards. I think we can put sort of "Available: [Number]" to the top-right corner, probably using smaller font.

Regarding the "visual grouping" for VMs from a single pool - we can change background color for a pool-VM (not the pool).
When sorted by name, these VMs are listed along the pool-card.

In addition, we can render "from [name] pool" text (smaller font, the [name] is a hyperlink to the pool's detail)
- either beneath the VM name
- or in the top-right corner (same position as the "Available: [number]"

**Comment by jelkosz** [comment]
> Regarding the "visual indication", I would "multi-line" the border, like "there's stack of cards". This will indicate at the first glance, there's "something multiplied". But it might be tricky to implement.

the multi line border sounds good to me

> Plus card's tooltip might show something like "This is a pool of virtual machines."

this would only work on a non-touchscreen devices. Maybe a visual indication as mentioned above and than in the details screen tell that this is a pool.

> There's still a lot of white space on recent cards. I think we can put sort of "Available: [Number]" to the top-right corner, probably using smaller font.

yeah, that sounds good

> Regarding the "visual grouping" for VMs from a single pool - we can change background color for a pool-VM (not the pool).

we would have to be double careful about the way we generate colours not to generate something ugly :) But if this can be done in some automated way, why not. @jniederm you for sure know about some algorithm how to generate the colours in a way they are distinct and not ugly, right? :)

> When sorted by name, these VMs are listed along the pool-card.

not necessarily. Since I think 3.6 you can rename the VMs in a pool so you don't have this poolName-number pattern anymore. Maybe the sorting could have also an option to sort by belonging to the same group...

> In addition, we can render "from [name] pool" text (smaller font, the [name] is a hyperlink to the pool's detail)

>    either beneath the VM name
>    or in the top-right corner (same position as the "Available: [number]"

not necessarily in the card, but in the VM detail it would be good.

**Comment by leistnerova** [comment]
Also showing errors on starting a VM from pool should be resolved. Now it doesn't show anything on the pool box only message in top menu is generated and there is not obvious which VM it was.

Other issue is when VM can't start because the hosts do not satisfy scheduling constraint, error text in Messages could be very long repeating the same error. I assume that the pool tries to start every free VM and all could fail from the same reason.

Tested in ovirt-web-ui-1.3.4-1.el7ev.noarch

**Comment by gregsheremeta** [comment]
we'll discuss in next redesign meeting. cc @lizsurette @lwrigh

**Comment by sjd78** [comment]
@gregsheremeta - this for the pool design doc and #680 etc

**Comment by gregsheremeta** [comment]
final design doc: https://docs.google.com/document/d/1G8ROKv_Talwh3c_drDglxM03zdOWoW-cAWt2-2zVqqk/edit
