### ISSUE TITLE
Round reported memory size

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#226]
maybe 3 or 4 [significant figures][1] of memory size is enough

version: commit 252b932, components commit c00b232

![memory-size-screenshot](https://user-images.githubusercontent.com/5278760/27037707-09a45e8c-4f89-11e7-8139-4bd150a81089.png)

[1]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision

**Comment by mareklibra** [comment]
With recent fix, the number is rounded to 1 significant digit
