### ISSUE TITLE
Show/Hide for disks doesn't work

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#227]
It can be only shown, not hid back.

![image](https://user-images.githubusercontent.com/5278760/27045428-176f1990-4fa1-11e7-813a-0525dd172447.png)

version: commit 252b932, components commit c00b232

**Comment by mareklibra** [comment]
Works fine with https://github.com/oVirt/ovirt-ui-components/pull/46.

Will be fixed with next ui-components release and corresponding version update in web-ui.
