### ISSUE TITLE
Showing list of VM disks

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#228]
I suggest to:
* remove hide/show switch
* always show at least two disks
* if there are more than let's say 2 disks show "more (#)" on next line to show remaining disks, where '#' is number of remaining disks.
* add some handling of no disks, e.g. "no disks" in grey

**Comment by mareklibra** [comment]
Fixed within https://github.com/oVirt/ovirt-web-ui/pull/221
