### ISSUE TITLE
Test on large VM count

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#23]
The application lists VMs filtered on the current user.
Expected count of VMs is <100.

Anyway, the application should perform well even for 1000 VMs.
In addition, related entities (like hosts or templates) are retrieved which count might be even >1000.

Within this issue, sort of performance test should be executed and potential bottlenecks resolved.

**Comment by mareklibra** [comment]
Paging will need to be added for REST API calls.

**Comment by jelkosz** [comment]
requires some investigation on the ovirt side how it can be paginated and if the current support is sufficient or we need to open a bug on ovirt side.

**Comment by jelkosz** [comment]
ok, after a bit of investigation the ovirt API actually does support pagination using the search query. 
Looks like this: /ovirt-engine/api/vms/;max=100?search=SORTBY NAME ASC  page 2

This is supported since 3.6 also for Filter: true, so we can use it.
