### ISSUE TITLE
Ability to switch among VMs from VM detail

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#231]
Webadmin and extended userportal allow users to check VM details (in subtabs) while quickly switching among VMs. This feature should bring similar ability to web-ui.

Add list of VM to VM detail. The list will be hideable and hidden by default. Visibility state will be controlled by pin icon and stored in local storage.

![mockup](https://user-images.githubusercontent.com/5278760/27088833-11a5ab88-5059-11e7-8f44-9c70f4602ca5.png)

Please comment/suggest.
@jelkosz , @vojtechszocs , @gregsheremeta , @mareklibra  , @matobet , @bond95

**Comment by jelkosz** [comment]
👍

**Comment by mareklibra** [comment]
👍
