### ISSUE TITLE
form selectbox has wrong formating

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#242]
selectbox formating in VM differs from the one in weadmin portal

webadmin portal:
![webadmin portal](https://user-images.githubusercontent.com/29575480/27336879-281524e8-55d1-11e7-977d-1e8660ba3b17.png)
vm portal:
![vm portal](https://user-images.githubusercontent.com/29575480/27336913-42628728-55d1-11e7-995c-585ff13ba0e0.png)

**Comment by jelkosz** [comment]
@bond95 please check if it is already ok in the current master

**Comment by leistnerova** [comment]
no it is still not in ovirt-engine-4.2.0-0.0.master.20170723141021.git463826a.el7.centos.noarch
