### ISSUE TITLE
error box displayed under the selectbox

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#243]
and is over the selectbox label

![screenshot from 2017-06-20 16-01-45](https://user-images.githubusercontent.com/29575480/27337124-d3dd3c0c-55d1-11e7-8b19-12ffbdf37ffc.png)

**Comment by mareklibra** [comment]
This seems to be fixed by redesign in 1.1.0.
Please reopen otherwise.

![errorbox](https://user-images.githubusercontent.com/17194943/27431065-64f73be6-574b-11e7-910c-cd45e994f08d.png)
