### ISSUE TITLE
put disks in VM detail below the label

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#245]
Disks in VM detail start on the same row like label with the hiding link. It will look better to show them below the label (same as checkbox button below the console label). And it will be then much better responsive in small browser window.

**Comment by mareklibra** [comment]
This might be fixed in 1.1.0, please see later screenshots in https://github.com/oVirt/ovirt-web-ui/pull/221

**Comment by mareklibra** [comment]
Please reopen if not properly fixed in newer version.
