### ISSUE TITLE
top menu breaks in very small window

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#246]
It goes to more 3 lines and hides the buttons bellow.
![screenshot from 2017-06-21 12-26-44](https://user-images.githubusercontent.com/29575480/27379858-38d6f8c2-567d-11e7-9c74-c7bb6da22334.png)

**Comment by jniederm** [comment]
Top bar will be [replaced][1] by Masterhead component as part of #311.

[1]: https://github.com/oVirt/ovirt-web-ui/issues/311#issuecomment-330824597
