### ISSUE TITLE
VM in pause state doesn't have any icon with tooltip

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#247]
also in detail is only 'paused' with no icon

![screenshot from 2017-06-21 12-46-21](https://user-images.githubusercontent.com/29575480/27380508-b30a4912-567f-11e7-9699-5d037c1d5345.png)

**Comment by michalskrivanek** [comment]
can we also display the pause reason in a tooltip? IO/user/no space

**Comment by mareklibra** [comment]
@michalskrivanek , within https://github.com/oVirt/ovirt-web-ui/pull/250 the `status_detail` is added, see screenshot there.
