### ISSUE TITLE
VM list scrolling

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#249]
* When main content is scrolled down, there is blank space above the list.
* There is no scrollbar to handle many VMs

![image](https://user-images.githubusercontent.com/5278760/27427541-a62a0fbe-573f-11e7-837c-68cb9f3034b4.png)

Version: commit 8516302

**Comment by michalskrivanek** [comment]
@jniederm fixed?

**Comment by jelkosz** [comment]
@michalskrivanek almost there: https://github.com/oVirt/ovirt-web-ui/pull/256
