### ISSUE TITLE
templates should be filtered by user permission on New and Edit VM pages

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#258]
There is a chance that the user is allowed to see a template from a cluster but is not allowed to create a VM based on it. This templates should be marked somehow or not shown in the new VM dialog at all.

[GS: edit] Also, on the Edit dashboard, if there are templates a user doesn't have permissions to apply, they should be hidden.

**Comment by michalskrivanek** [comment]
@mareklibra still targeted to 1.3? doesnt' seem realistic

**Comment by mareklibra** [comment]
No, I see "Future release". Might be moved to 1.4 within next planing

**Comment by doron-fediuck** [comment]
@sgratch still relevant? If so it should be prioritized (and we need a bz).

**Comment by michalskrivanek** [comment]
The only tracker for ovirt-web-ui is the github issue tracker

**Comment by doron-fediuck** [comment]
> The only tracker for ovirt-web-ui is the github issue tracker

Which makes it hard to track as a part of the overall picture.

**Comment by isaranova** [comment]
ci build please
