### ISSUE TITLE
strange behaviour with setting console Connect automatically

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#260]
It somehow remembers for which VMs I had set the connection and mess them up. See video.
I'm using Firefox 53.0.3 

[Screencast from 06-29-2017 02:48:28 PM.webm.zip](https://github.com/oVirt/ovirt-web-ui/files/1112083/Screencast.from.06-29-2017.02.48.28.PM.webm.zip)

**Comment by mykaul** [comment]
Can you please share the issue on the oVirt users mailing list? (users@ovirt.org) ?

**Comment by leistnerova** [comment]
done, waiting for approval

**Comment by mareklibra** [comment]
Fixed by https://github.com/oVirt/ovirt-web-ui/issues/265
