### ISSUE TITLE
Make left navigation bar responsive

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#269]
Left vertical bar should adapt to narrow document viewports.

Current situation (commit ba7828d) - navigation bar remains same even in narrow browser viewport.
![image](https://user-images.githubusercontent.com/5278760/28030108-a602d086-65a2-11e7-9d2c-1651d8bd292b.png)

Webadmin hides the left bar completely if page width < 768px.
![image](https://user-images.githubusercontent.com/5278760/28030183-f981b8a8-65a2-11e7-87de-9185b8cde86b.png)

Cockpit shrinks the bar if the page width < 768px (similar to webadmin).
![image](https://user-images.githubusercontent.com/5278760/28030301-795dae9c-65a3-11e7-8f1a-9824a4917038.png)

What solution do you prefer? Or what other solution do you suggest?  
@jelkosz @mareklibra @bond95 

I like find cockpit solution more user friendly and aesthetic. However if most users are expected to see only one option ("Virtual Machines") it might be a waste of space.

**Comment by bond95** [comment]
For me best solution is second one, burgermenu is good cause it give more space for some important information on small displays.

**Comment by mareklibra** [comment]
The user shall have access to the menu even on smaller displays. So it leads to the 2nd option.

Or: For narrow displays, the left-side menu can shrink to ~1em dark vertical bar with an `open`/`close` icon (like `>>`). By default, the vertical menu is collapsed. When navigation occurs, it's collapsed again.
The `open`/`close` action is always-visible (consider scrolling).

What do you think?

**Comment by mareklibra** [comment]
Related to https://github.com/oVirt/ovirt-web-ui/issues/246

**Comment by michalskrivanek** [comment]
#312 will perhaps remove/hide it

**Comment by jniederm** [comment]
Navigation bar hidden by #342.
