### ISSUE TITLE
make WAN SPICE related properties configurable

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#274]
- wan color depth
- wan disable effects

currently, they are configured in the engine in vdc_options (WANDisableEffects and WANColorDepth) and the fact if those will be exposed or not is questionable. Thus, setting as blocked for now. 

We may consider to add this to ovirt-web-ui specific config file.

**Comment by mareklibra** [comment]
vdc_options are already exposed in oVirt REST API, removing `blocked`

**Comment by michalskrivanek** [comment]
that's a gap from teh old UP, isn't it?

**Comment by sgratch** [comment]
It doesn't seem like being exposed on webadmin as well and since no user complained about this missing configuration for more than 3 years then closing as WONTFIX.
