### ISSUE TITLE
consider adding the ovirt dashboard as one of the side tabs

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#275]
As reviewing the patch removing the old user portal (https://gerrit.ovirt.org/#/c/78847/) Im opening issues here to cower the gaps. 
This particular issue is just a material for discussion, Im really not sure if we want to cower this gap.

Argument for adding:
- the extended user portal has some kind of a dashboard already so if we don't want to drop this functionality, we need one. And rather than implement one from scratch, why not integrate the one already provided for ovirt?
- for someone who has admin permissions it might provide valuable overview and for digging into details there might be links to hosts' cockpit

Argument against:
- it contains lots of advanced admin stuff and not sure if they belong to user portal like use case (so would have to be shown only for someone with admin permissions)
- not sure if anyone was actually using the dashboard from user portal (but it might have been due to that particular dashboard itself and maybe a good dashboard would be happily used...)

All in all, Im not sure.
@mareklibra @jniederm @vojtechszocs @gregsheremeta what do you guys think?

**Comment by mareklibra** [comment]
I like the idea of showing the dashboard for `admin` users.
Anyway, it can't be the default landing page as done in webadmin.

From design perspective, the integration might be feasible without complex changes.

I have not considered the technical part of integration yet. But I believe it might be feasible, in worst case as an iframe. @vojtechszocs , what do you think?

**Comment by vojtechszocs** [comment]
> I like the idea of showing the dashboard for `admin` users.

+1

> Anyway, it can't be the default landing page as done in webadmin.

oVirt Dashboard was designed as UI plugin for WebAdmin, but it could be modified to allow its use in other contexts, such as VM Portal.

Its React component hierarchy looks like this:

```
<DashboardDataProvider> <!-- fetch data & apply it via `data` prop to child component -->
  <GlobalDashboard /> <!-- brings all the UI together -->
</DashboardDataProvider>
```
Check out `GlobalDashboard.propTypes` to see the expected shape of data. Smaller components, such as `<AggregateStatusCard>`, work with subsets of the whole data.

The only issue with using `<GlobalDashboard>` component as-is are embedded calls to WebAdmin UI plugin API, for example:

```
<AggregateStatusCard
  ...
  data={inventory.dc} // the `inventory` is a subset of the whole `data`
  onTotalCountClick={() => {
    getPluginApi().revealPlace(webadminPlaces.dc) // call to UI plugin API
    ...
  }}
  ...
  }} />
```

Therefore, the best (and most flexible) approach is to just pick the components you want and create a higher-order component that brings all the dashboard UI together, like `<AdminDashboard>`.

Note that oVirt Dashboard components currently rely on jQuery, D3 and C3 libraries, we should probably improve that.

> From design perspective, the integration might be feasible without complex changes.

You can pick the parts you want and use them in VM Portal.

Currently, oVirt Dashboard gets its (JSON) data from Engine via `DashboardDataServlet` that queries both Engine and DWH databases. You could try to reuse that servlet for VM Portal's dashboard.

> in worst case as an iframe

`<iframe>` can be used to isolate the context (DOM, JavaScript, CSS) of the embedded content.

In this case, I don't think you need that at all 😄

**Comment by oourfali** [comment]
I'm worried permission-wise, as it indeed shows you data an admin can see, but not everyone.
In order to scope the data, you need to further extend the backend side of the dashboard, and take permissions into consideration.

As the current backend design isn't optimal, and was planned as something that will not get extended much, I'd advise you to go with another approach.
Use the widgets you're interested in, and use regular REST-API calls in order to fill in the data.
That assumes you won't need data from DWH, but only regular inventory data such as number of hosts/vms/disks/etc.

**Comment by michalskrivanek** [comment]
not sure it's within the scope of ovirt-web-ui....

**Comment by jniederm** [comment]
> not sure it's within the scope of ovirt-web-ui....

+1

**Comment by gregsheremeta** [comment]
I feel confident that we should not add the admin dashboard to VM Portal

**Comment by mareklibra** [comment]
Thanks for the comments
