### ISSUE TITLE
Menu should be aligned to the left

### ISSUE THREAD

**Issue by KwisatzHaderach** [oVirt/ovirt-web-ui#289]
Description of problem:
Menu on top of VM detail is not in convenient place, most people would expect it to be on the left. So aligning it to the right is not really good since on higher resolution displays it is pretty far. To be fair I have to literally move my head to look at the menu.

Steps to Reproduce:
1. open VM detail in web-ui

Actual results:
menu with start|stop... is aligned to the right

Expected results:
menu should be aligned to the left

Screenshot:
https://www.dropbox.com/s/qv20o6hdkp5mxgb/screenshot-8864-1500482600.png?dl=0

**Comment by mareklibra** [comment]
So far we follow Patternfly recommendation in this matter.

For more info, see https://bugzilla.redhat.com/show_bug.cgi?id=1472959
