### ISSUE TITLE
add manually change of VM icon

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#306]
Add the possibility to change VM icon. I suggest to add it directly to edit form similar like in the image.

![screenshot from 2017-08-03 16-28-14](https://user-images.githubusercontent.com/29575480/28927143-1766e17a-786a-11e7-9d08-a7aeadcfb3ab.png)

**Comment by leistnerova** [comment]
@mareklibra

**Comment by jelkosz** [comment]
An another option would be giving the picture some overlay picture showing that it can be changed (some pen in one of the corners or whatever) and if clicked than showing two small buttons (upload/reset to default)?

@mareklibra @jniederm what you guys think?

**Comment by mareklibra** [comment]
or two small icons/symbols rendered without any margin right under the picture? One with "pen" - like we already have for VM Edit and another one with something denoting "default"

**Comment by jniederm** [comment]
Edit page uses small version of the icon and it really is quite small so I'd be more for @mareklibra's suggestion. Or we can go the standard way like:

![image](https://user-images.githubusercontent.com/5278760/28968797-0f8b93f2-7922-11e7-9e5a-d55ea3cad3c9.png)

**Comment by mareklibra** [comment]
We are talking about pictures, so let's be creative and skip the standard way :-)

**Comment by mareklibra** [comment]
Implemented.
