### ISSUE TITLE
ovirt has new branding colors

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#311]
Ovirt ovirt-engine-webadmin-portal-4.2.0-0.0.master.20170808202742.git7c42951.el7.centos.noarch
has changed colors from green to blue and some other stuff. VM portal uses still the old colors.

![screenshot from 2017-08-09 12-17-25](https://user-images.githubusercontent.com/29575480/29117390-4eb993be-7cfe-11e7-8327-f5fb94a8e761.png)

![screenshot from 2017-08-09 12-21-23](https://user-images.githubusercontent.com/29575480/29117402-559b05c8-7cfe-11e7-96db-7213876e09e5.png)

**Comment by gregsheremeta** [comment]
I can do this

**Comment by mareklibra** [comment]
@gregsheremeta , v1.3.0 is planed for oVirt 4.2 (but not necessarily for early builds). Do you think resolving of this issue is feasible in this time frame?

**Comment by jniederm** [comment]
Hi @gregsheremeta, do you plan to switch from short to tall [Masthead][1] as part of this issue as it was done in webadmin?

[1]: http://www.patternfly.org/pattern-library/application-framework/masthead/

**Comment by gregsheremeta** [comment]
> do you plan to switch from short to tall Masthead

Yes

![selection_148](https://user-images.githubusercontent.com/2248293/31592471-851a39e0-b1f6-11e7-97b1-3ad388d702c5.png)

![selection_147](https://user-images.githubusercontent.com/2248293/31592472-87d751e0-b1f6-11e7-9480-c5a3d5e0250b.png)
