### ISSUE TITLE
Add AuditLog component

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#32]

**Comment by michalskrivanek** [comment]
@mareklibra can you provide more details what is it about?

**Comment by mareklibra** [comment]
The idea was about rendering audit log messages from oVirt

**Comment by michalskrivanek** [comment]
which logs though? users are not administrators

**Comment by mareklibra** [comment]
Right, it would be rendered for admins only.
But this is just nice-to-have.

**Comment by mareklibra** [comment]
It's just an idea, planed for "Future release"

**Comment by gregsheremeta** [comment]
I don't think this fits the scope of the product. Closing
