### ISSUE TITLE
Remove button on cluster page is hidden under 3-dotted menu

### ISSUE THREAD

**Issue by Eressiel** [oVirt/ovirt-web-ui#325]
In Administration portal the Remove button on cluster page is placed under the 3-dotted options menu, but on all other pages (Datacenters, Hosts, etc.), Remove button comes after Edit.

To keep the layout consistent, the Remove button on clusters page should be placed next to Edit button.

Version 4.2.0

**Comment by jniederm** [comment]
@Eressiel we appreciate the bug report. This github project is for ovirt-web-ui only ([screenshot](doc/screenshots/v1.0.0_2017-Jun/01_vmsList.png)). Please file bugs regarding Administration portal (a.k.a. webadmin) at https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine, Component=Frontend.WebAdmin, oVirt Team=UX.
