### ISSUE TITLE
unify the way how to switch between VMs quickly between webadmin and ovirt-web-ui

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#351]
Only transfered the BZ from: https://bugzilla.redhat.com/show_bug.cgi?id=1492396

**Comment by michalskrivanek** [comment]
I'd say the webadmin side should change, in which case this is blocked on that

**Comment by jniederm** [comment]
Benefits of web-ui solution compared to webadmin solution: it saves 50% of clicks and requires no extra mouse moves.

**Comment by michalskrivanek** [comment]
I do not see a reason to cripple a better working functionality here
