### ISSUE TITLE
Remove small icon from edit page

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#355]
Let's consider removing small icon from edit VM page and replacing it by the large one.

Reasons:
* There is enough room to show the large one.
* Smaller icons are more difficult to recognize.
* It is the last usage of the small icon in oVirt in general. So by abandoning using it here we can eventually remove small icons from engine.
* There is a bug resetting default small icons:
  1. Let's have a VM with custom icon
  2. Open the VM detail page
  3. Click the "curcular arrow" button to reset the icon to default.  
      Icon (the large one) is immediately updated
  4. Click "Edit" button  
      The small icon in edit page is still the old one.

![image](https://user-images.githubusercontent.com/5278760/31733756-e4e9bfe2-b43c-11e7-941d-c9255a20f645.png)

**Comment by mareklibra** [comment]
> * Smaller icons are more difficult to recognize.
> * It is the last usage of the small icon in oVirt in general. So by abandoning using it here we can eventually remove small icons from engine.

Sounds good to me.

**Comment by mareklibra** [comment]
Will be implemented along #356
