### ISSUE TITLE
Move icon editing from VM detail page to VM edit page

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#356]
Let's consider moving edit icon controls to edit VM page. I can see following issues of current solution:

* It's a bit inconsistent - everything else is edited on different page
* I can look confusing with icons that has while area in bottom part (see screenshot below). "Circular icon" can be mistaken for "restart VM" or "refresh" button. 
![image](https://user-images.githubusercontent.com/5278760/31734451-0a372c1a-b43f-11e7-98fe-d5a8a47f39da.png)

I'd like to resuggest something like
![image](https://user-images.githubusercontent.com/5278760/31734170-2239274c-b43e-11e7-85cb-3f353e2d5817.png)

What do you guys think? @mareklibra @jelkosz @suomiy @bond95 

Original bug: #306

**Comment by mareklibra** [comment]
In recent state, I would be for moving it to the Edit page.
The buttons looks strange there anyway, can we figure out something better?

Maybe an text input box for picture's local filename followed by two icons - one denoting the upload (i.e. http://fontawesome.io/icon/upload/ or any beter) and second one for the default.
If default is pressed, text like `[default]` is set in the text field.

The actual change happens not before the dialog is confirmed.

**Comment by mareklibra** [comment]
Second idea: what about aligning with the approach recently used in Cockpit? I mean inline-editing.
There would be no general-purpose Edit VM Dialog. 
Editable VM properties would be changed step-by-step by clicking on its value (like the `1` for CPU), a specialized dialog would appear to change just the single value.

This approach might become overwhelming when performing complex tasks, but this is probably not the case of VM Portal.

From usability perceptive, it's closer to basic human perception: `I want to change this`.

**Comment by bond95** [comment]
I like second idea. Or we can just add buttons for `Edit` and `Default` under icon, and make it more in materialize style. Something like that:
![screenshot from 2017-10-19 15-46-45](https://user-images.githubusercontent.com/3332176/31774004-c9875234-b4e4-11e7-919d-3a4f2e6615c6.png)

**Comment by jniederm** [comment]
> In recent state, I would be for moving it to the Edit page.

+1

> text input box for picture's local filename followed by two icons

* Provided the icon selected to upload will immediately replace the original icon (in "preview", unsaved mode) `<input type="file">` widget much useful.
* I feel like it's not always 'A picture is worth a thousand words'. I find text labels often more descriptive.

>  inline-editing

It can work provided the whole dialog would work like that (or if we at least decide to rework the VM editing into inline fashion in very near future). Combination of current approach and "inline editing" could be confusing.

**Comment by leistnerova** [comment]
Little notice, when you use the edit/reload icons that are now in VM portal, don't forget to change cursor type when hovering over them. Now it doesn't change.
