### ISSUE TITLE
add possibility to enter 8G/g/GB/gb to Defined memory in VM edit form

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#366]
As it is in admin portal. On iPad there are not the arrows to increase/decrease by 1GB, so it's not much user friendly to change memory.

**Comment by gregsheremeta** [comment]
@sjd78 @lizsurette @lwrigh let's chat about this one in the next meeting

**Comment by gregsheremeta** [comment]
old edit form is leaving soon, closing
