### ISSUE TITLE
mobile: VMs in grid view are not all visible on mobile device

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#367]
Tested on iPad with Safari. Only first page is displayed and even the last VMs are cut. Scrolling doesn't do anything.

**Comment by mareklibra** [comment]
@leistnerova , can you please re-test on recent 1.3.9 or 1.4.0-pre (brq-dev) ?

**Comment by gregsheremeta** [comment]
@bond95 let's make sure this works in the new main page

**Comment by bond95** [comment]
Seems everything works fine, but design can be more responsive for mobile, as you can see on images logo has low quality, breadcrumb with toolbar occupy a lot of space, and actions in header just disappear. Tested in Chrome 68.0.3440.91 and Firefox 61.0, on Huawei P10.

@gregsheremeta @lizsurette what do you think?

![photo_2018-08-09_11-44-50](https://user-images.githubusercontent.com/3332176/43891485-b18de626-9bc9-11e8-8a43-cbbd5714d352.jpg)
![photo_2018-08-09_11-44-47](https://user-images.githubusercontent.com/3332176/43891486-b1abe3d8-9bc9-11e8-9f48-6a8f84b37164.jpg)
![photo_2018-08-09_11-44-44](https://user-images.githubusercontent.com/3332176/43891487-b1cde4a6-9bc9-11e8-8a39-a155d04c4420.jpg)

**Comment by gregsheremeta** [comment]
it definitely needs more work. I'll move this one out to 1.4.3 or 1.4.4.

**Comment by bond95** [comment]
@gregsheremeta I think need to create new issue, because this one was about visibility of VMs.

**Comment by gregsheremeta** [comment]
@bond95 ah, my bad. So are they all visible now? If so I guess we submit PR :)

**Comment by bond95** [comment]
@gregsheremeta there is no PR for this issue, because I tried it on redesigned main page. =)

**Comment by gregsheremeta** [comment]
alright. we can attach this to that one then.

**Comment by gregsheremeta** [comment]
so there is still work to do, but the VMs are now all visible on mobile
