### ISSUE TITLE
Direct access to /vm/add shows misleading 'Please log in ...' message

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#372]
Version: commit cfa1c33, tag ovirt-web-ui-1.3.0-1

Steps to reproduce:
1. load `<web-ui-prefix>/vm/add`

![web-ui-add-page](https://user-images.githubusercontent.com/5278760/32222778-ecf41a0e-be3a-11e7-9c8d-54912617a158.png)

Note: tried in dev mode

**Comment by mareklibra** [comment]
Does not work on prod env either
