### ISSUE TITLE
Check if new VM name already exists

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#381]
... before pressing 'Create VM' button and mark the 'Name' field in case of error.

version: commit e438214

![image](https://user-images.githubusercontent.com/5278760/32277368-88415332-bf12-11e7-8d93-71f3b6f5b8ba.png)

**Comment by gregsheremeta** [comment]
cc @lizsurette consider for redesign. Perhaps out of scope

**Comment by michalskrivanek** [comment]
yeah, sounds too "nice to have" and I do not find that particularly useful. You either know what you want to create or not, and when you do not and create a VM twice you just get a concise error. And it's not like a backend webadmin validation which discards all content and it's super annoying to fill everything again, here you still have all data -  sounds good enough to me and I would close this....
