### ISSUE TITLE
Add typeahed for 'Template' field in New/Edit VM pages

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#383]
version: commit e438214

![image](https://user-images.githubusercontent.com/5278760/32277783-d42ccfbe-bf13-11e7-9f54-5efb07956722.png)

**Comment by gregsheremeta** [comment]
cc @lizsurette for new vm flow

**Comment by gregsheremeta** [comment]
edit is leaving soon, and new vm will be a wizard which will consider this. closing.
