### ISSUE TITLE
Make heading a link leading to main page

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#384]
version: commit e438214

![image](https://user-images.githubusercontent.com/5278760/32277941-5f7aa0dc-bf14-11e7-9205-c2067fa3dd99.png)

**Comment by mareklibra** [comment]
A follow-up PR needs to be provided to fix this, since original author can't be reached.

**Comment by leistnerova** [comment]
LGTM, so this issue can be closed.

**Comment by jelkosz** [comment]
thank you, closing
