### ISSUE TITLE
Error message partially overlapped

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#395]
Error message "Authorization expired. The page is going to be reloaded to re-login." is partially overlapped.

Steps to reproduce:
1. Open web-ui
2. Restart connected engine to invalidate current authorization

![image](https://user-images.githubusercontent.com/5278760/32553620-b32b883a-c497-11e7-9168-5be0e5777625.png)

version: commit 3db3a19

**Comment by michalskrivanek** [comment]
I suppose it wont' happen now when session doesnt' expire since #388?

**Comment by mareklibra** [comment]
I think the issue remains for the steps described above.
To fix this issue:
- whole the message shall be visible
- the token shall be invalidated within ovirt-web-ui (its most probably already done)
- the user shall be able to reload the page to pass oVirt SSO login form once again (i.e. render `reload` within the error message

**Comment by mareklibra** [comment]
Might be ralated: #452, #434
