### ISSUE TITLE
Sort operating systems

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#409]
In Edit VM details card, sort operating systems alphabetically.

**Comment by jniederm** [comment]
I'd suggest to use something like [alphanum-sort][1] package to get *... Windows 8, Windows 10, ...* and not then alphabetical version which is the other way around.

[1]: https://www.npmjs.com/package/alphanum-sort

**Comment by gregsheremeta** [comment]
sorted well enough, closing
