### ISSUE TITLE
VM grid scrollbars are "breathing"

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#412]
version: commit 9dccbfd

In Firefox the scrollbar moves solely by itself, it chrome it "only" moves when mouse is moving.

Firefox:
![breathing-scrollbar2](https://user-images.githubusercontent.com/5278760/32801504-8f5796c0-c97d-11e7-854c-0c9fa66628a8.gif)

Chrome:
![breathing-scrollbar-chrome](https://user-images.githubusercontent.com/5278760/32801515-9a03c56c-c97d-11e7-8a5a-18658e095c96.gif)

**Comment by gregsheremeta** [comment]
obsoleted by redesign, closing
