### ISSUE TITLE
VM boxes have different height

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#414]
VM boxes in grid view have different height.

![screenshot from 2017-11-15 14-31-06](https://user-images.githubusercontent.com/29575480/32838765-66a0a434-ca12-11e7-8373-934e753f0224.png)

And on iPad then can appear blank space.

![screenshot from 2017-11-15 14-31-45](https://user-images.githubusercontent.com/29575480/32838832-8ec356c8-ca12-11e7-9b0c-930559348582.png)

**Comment by jniederm** [comment]
It's caused by non-standard dimensions of cake icon. We should specify set dimensions of containing element.

**Comment by leistnerova** [comment]
also when there is no OS (e.g. pool)

![screenshot from 2017-12-04 16-28-32](https://user-images.githubusercontent.com/29575480/33560540-52f1008e-d910-11e7-890c-cfd4e5075767.png)
