### ISSUE TITLE
no cake as VM icon

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#415]
There still appears cake icon by the VM. It should not.

![screenshot from 2017-11-15 14-42-12](https://user-images.githubusercontent.com/29575480/32839018-3d2be644-ca13-11e7-8d66-a7f5c79f5398.png)

**Comment by jniederm** [comment]
* Cake icons seem to appear for VMs with custom VM icons
* Tip to reproduce: start with empty FIrefox profile
