### ISSUE TITLE
ScrollPositionHistory not working

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#416]
When getting back from VM page to grid listing, scroll position is not restored.

At this occasion I'd like to suggest to use memory instead of session storage to store scroll offset since
* there is on need to preserve scroll position during whole browser session. It's ok if scroll is shifted to the top after page reload.
* doesn't play well with multiple tabs.

version: commit 9dccbfd

**Comment by jniederm** [comment]
Relates to #417

**Comment by mykaul** [comment]
@jniederm  - there's no severity or target milestone label on this.

**Comment by mareklibra** [comment]
@jniederm , can you please check if this is already fixed?

**Comment by jniederm** [comment]
it's still there in commit d1c3a43, current master

**Comment by gregsheremeta** [comment]
@bond95 Bohdan, can you check this after you rebase the new main page? If it's still an issue, it sounds easy and I targeted to 1.4.2 (August 10)

**Comment by bond95** [comment]
Yes, this is still issue.

**Comment by gregsheremeta** [comment]
@bond95 ok, thanks for verifying. Does this sound like something you can fix in a day or two?

**Comment by bond95** [comment]
@gregsheremeta yes, of course.
