### ISSUE TITLE
Grid listing is shifted to to the top each time next VMs are loaded

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#417]
It looks like `<RenderComponent>` in `src/components/PageRoute.js` is remounted each time the redux store is changed.

version: commit 9dccbfd

**Comment by mykaul** [comment]
@jniederm  - there's no severity or target milestone label on this.

**Comment by mareklibra** [comment]
@jniederm , is this still valid?

**Comment by jniederm** [comment]
it's fixed in commit  d1c3a43
