### ISSUE TITLE
Popup descriptions hidden in edit page

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#422]
version: commit 5e7eb03

Steps to reproduce:
1. Go to edit VM page
2. Click at "Cluster" label

Actual result:
Only small arrow is shown instead of whole tootlip bubble.

![image](https://user-images.githubusercontent.com/5278760/32981295-fd417d78-cc74-11e7-8cd2-6fefd7a95884.png)

**Comment by mareklibra** [comment]
Fixed by #603
