### ISSUE TITLE
change sorting in Messages

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#431]
First should be the newest.

![screenshot from 2017-11-21 15-33-46](https://user-images.githubusercontent.com/29575480/33077944-78c8722c-ced1-11e7-88c1-1d5fa988a48f.png)

**Comment by mykaul** [comment]
@mareklibra - there's no severity or target milestone label on this.

**Comment by michalskrivanek** [comment]
isn't it just the way it's returned from API?

**Comment by gregsheremeta** [comment]
obsoleted by redesign, closing
