### ISSUE TITLE
error message in the VMs detail stays visible

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#433]
When some error appears in the VMs detail, it stays visible until is cleaned from top Message menu. It should disappear at least when user leaves the detail or could be hidden by the user.

![screenshot from 2017-11-21 15-51-37](https://user-images.githubusercontent.com/29575480/33078743-e882a18a-ced3-11e7-893e-23eaafb85667.png)

**Comment by mareklibra** [comment]
I suggest to add a "cross" icon in the top-right corner to hide it from the detail but keep listing the message within `Messages`. In other words, it will mark the single error message so react component will skip rendering it.

Nice to have: add similar "cross" even to the `Messages`. This action will remove the error from redux completely.

**Comment by mykaul** [comment]
@mareklibra - there's no severity or target milestone label on this.

**Comment by gregsheremeta** [comment]
obsoleted by redesign, closing
