### ISSUE TITLE
Top line of tooltip not visible

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-web-ui#434]
RHV 4.2.1 VM Portal > VM details > Console tooltip

Top line of tooltip is not visible. Scrolling or resizing window does not help.

![image](https://user-images.githubusercontent.com/31725355/33080437-c2bb6ce0-cee0-11e7-8fd3-578e8e25e63a.png)

**Comment by mykaul** [comment]
@mareklibra  - there's no severity or target milestone label on this.

**Comment by bond95** [comment]
Already exists issue for that https://github.com/oVirt/ovirt-web-ui/issues/568
