### ISSUE TITLE
VM Creation error message is incorrect

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-web-ui#442]
If you try to create a VM in the VM Portal with a non-working template, the error message refers to the Boot Option sub-tab and the 'Run Once' command, which are only found in the Administration Portal.
![vmnodiskerror](https://user-images.githubusercontent.com/31725355/33370917-b7d17424-d501-11e7-99aa-dfe894fb1fdc.png)

**Comment by michalskrivanek** [comment]
this is a message from ovirt-engine backend. You need to raise a bug against ovirt-engine to improve that message

**Comment by jelkosz** [comment]
well, it surfaces in web ui as a problem so it makes sense to track it here. But I don't particularly mind where is it going to be tracked, considering it is one place only. Now we have this and https://bugzilla.redhat.com/show_bug.cgi?id=1518618
So, randomly closing this one :)
