### ISSUE TITLE
when pool is removed, the vm portal still shows the deleted VMs from it

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#446]
When pool is removed with all its VMs and user is logged in VM portal, they stay there. Refresh button doesn't help, other VMs are refreshed but the removed VM are still visible.
When I go to detail, it goes immediately back to grid and the one VM is removed.

tested in ovirt-web-ui-1.3.4-1.fc26.noarch.rpm

**Comment by mareklibra** [comment]
Hint: verify, that any deleted VM via webadmin is reflected to the list in VM Portal. This might be broken in the course of last changes.

**Comment by mareklibra** [comment]
If so, this is urgent, otherwise this can be considered as less critical
