### ISSUE TITLE
grid view get stuck by changing VM state

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#447]
When I request run or shutdown of VM and the process still in progress, going to VMs detail doesn't work properly and grid view (or simetimes blank space) stays instead of the detail, but headers changes.

Tested in ovirt-web-ui-1.3.4-1.fc26.noarch.rpm

![screenshot from 2017-12-05 12-31-52](https://user-images.githubusercontent.com/29575480/33605167-cc0b37e8-d9b8-11e7-863e-6a1c7ccaf0bb.png)

**Comment by mareklibra** [comment]
Maybe related from console log:
Reducing action:  {"type":"GET_BY_PAGE","payload":{"shallowFetch":true,"page":2}}  main.eecd3f44.js:1:12664
uncaught at a b@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:1:10917
m@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:20:11947
_constructComponentWithoutOwner@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:34:15488
_constructComponent@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:34:15337
mountComponent@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:34:14502
mountComponent@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:8:24765
performInitialMount@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:34:16295
mountComponent@https://10-37-138-5.rhev.lab.eng.brq.redhat.com/ovirt-engine/web-ui/static/js/main.eecd3f44.js:34:15178
mountComponent@https://10-37-138-5.rhev.lab.eng.b[…]

**Comment by mareklibra** [comment]
Idea: there are already many actions queued causing saga to postpone processing of the user's click

**Comment by gregsheremeta** [comment]
we'll retest this after edit page redesign is complete

**Comment by gregsheremeta** [comment]
@leistnerova would be good to try on 1.5

**Comment by gregsheremeta** [comment]
This pages have been heavily redone. This is highly unlikely to still be an issue, closing.
