### ISSUE TITLE
entered SSH key is still in Options form even after the dialog is closed

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#448]
Go to user -> Options. Enter something to SSH key textarea. Close the dialog (with Close button or X). Go again to Options. Entered SSH key is still there. 
By opening Options dialog it should load value that is saved.

**Comment by michalskrivanek** [comment]
is it just a display issue? which value does it actually use?

**Comment by leistnerova** [comment]
Only display, the entered value is not saved.

**Comment by leistnerova** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1525386

**Comment by michalskrivanek** [comment]
@leistnerova, does it work for you in 1.3.6?

**Comment by leistnerova** [comment]
Yes it works, in 1.3.6 entered key doesn't stay in the form.

**Comment by michalskrivanek** [comment]
thanks!
