### ISSUE TITLE
improve handling of unexpected API responses

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#449]
If a pool has no `vm` assigned, the `poolToInternal()` method fails on `undefined`.

Data retrieval must be more robust, no matter how corrupted data are retrieved from server.

Subsequent flows in React must be revised to verify even for the case of no assigned VM to the pool.

**Comment by mareklibra** [comment]
Since the data from engine seems to be corrupted due to nonstandard flow of ovirt installation, this issue can wait till 1.4

**Comment by michalskrivanek** [comment]
@mareklibra, what do you mean by "data seems to be corrupted"? that's not a reassuring sentence to defer with;-)

**Comment by mareklibra** [comment]
ah :-) the `pool` resource is expected to be associated with a `vm`. 

The original reporter of this bug was facing multiple issues during his oVirt setup and subsequent test data load. Anyway, the environment became up and running. When connected to VM portal, the data provided by API was inconsistent, like no `vm` within a `pool`.

Severity is low in this case, but it's good to improve handling of unexpected API response.

**Comment by mareklibra** [comment]
I think this should go along with https://github.com/oVirt/ovirt-web-ui/issues/450

**Comment by mareklibra** [comment]
In general, the `vmToInternal` and similar translation functions should be made more robust to
- expect certain structure from API (as they do)
- do not assume the structure is really returned (as in any other distributed system, it's good to assume whatever crap as a response)

**Comment by bond95** [comment]
@gregsheremeta GlobalErrorBoundary already implemented, can we close this issue?

**Comment by gregsheremeta** [comment]
closing  with the caveat that the app just fails to an error state now
