### ISSUE TITLE
VM header bar overlaps breadcrumbs

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-web-ui#451]
Header bar overlaps the top half of breadcrumbs.

![breadcrumbs](https://user-images.githubusercontent.com/31725355/34377722-f3334150-eafa-11e7-8893-5b4a3e990a5a.jpg)

**Comment by michalskrivanek** [comment]
@jniederm looks like the branding is broken again?

**Comment by jniederm** [comment]
Tracked on downstream as [BZ#1530599](https://bugzilla.redhat.com/show_bug.cgi?id=1530599)
