### ISSUE TITLE
Toobar overlaps tooltip

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-web-ui#452]
![pendingchangestt](https://user-images.githubusercontent.com/31725355/34379016-8283524a-eb01-11e7-8c3e-37d4a74a7670.jpg)

Possibly related to Issue #434

**Comment by sjd78** [comment]
Same problem as #434 but in a different location.

**Comment by bond95** [comment]
Already exists issue for that https://github.com/oVirt/ovirt-web-ui/issues/568
