### ISSUE TITLE
Buttons overlap when closing Edit VM window

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-web-ui#453]
![buttonsoverlap](https://user-images.githubusercontent.com/31725355/34379167-7b336d80-eb02-11e7-9aa1-e52f928f8c19.png)

Logged in as user with UserVMManager role

I clicked "Close" to leave the "Edit VM" screen and the buttons remained on the toolbar.

Also, the screen details did not change (Edit fields appeared), but the toolbar was from the VM pane.
No buttons worked. Only way out of this screen was to log out and log back in.

**Comment by jelkosz** [comment]
@apinnick can you please attach the frontend logs from javascript console (ctrl+shift+k in firefox). Also, does this happen regularly or did you have to do something special? also please provide the exact version of the web-ui. Thank you

**Comment by apinnick** [comment]
[buttonsLog.txt](https://github.com/oVirt/ovirt-web-ui/files/1591322/buttonsLog.txt)
Log attached.

I'm not sure what causes it. I thought it might have something to do with clicking the "Update VM" button twice before clicking "Close," but that doesn't seem to be it. Maybe the log will help. If I figure out how to reproduce the error consistently, I'll let you know. I was seeing it frequently this morning. About 6x.

**Comment by mareklibra** [comment]
found in the log:
```
TypeError: ae[n] is not a function
```
or maybe other error.

I've suspicion that an unrelated error caused saga to crash. If so, this will be fixed within #450

**Comment by mareklibra** [comment]
Will be addressed within #596

**Comment by gregsheremeta** [comment]
obsoleted by redesign, closing
