### ISSUE TITLE
unable to update

### ISSUE THREAD

**Issue by Austin6986** [oVirt/ovirt-web-ui#455]
unable to update via engine-setup version 4.2.0

[austin@ovirt ~]$ sudo engine-setup
[ INFO  ] Stage: Initializing
[ INFO  ] Stage: Environment setup
          Configuration files: ['/etc/ovirt-engine-setup.conf.d/10-packaging-jboss.conf', '/etc/ovirt-engine-setup.conf.d/10-packaging.conf', '/etc/ovirt-engine-setup.conf.d/20-setup-ovirt-post.conf']
          Log file: /var/log/ovirt-engine/setup/ovirt-engine-setup-20171227145711-6v6try.log
          Version: otopi-1.7.6_master (otopi-1.7.6-0.0.master.20171204131110.gitd5016f6.el7.centos)
[ INFO  ] Stage: Environment packages setup
[ INFO  ] Stage: Programs detection
[ INFO  ] Stage: Environment setup
[ INFO  ] Stage: Environment customization
         
          --== PRODUCT OPTIONS ==--
         
         
          --== PACKAGES ==--
         
[ INFO  ] ovirt-provider-ovn already installed, skipping.
[ INFO  ] Checking for product updates...
[ ERROR ] Yum [u'ovirt-engine-backend-4.2.1-0.0.master.20171226162249.git6e7cc87.el7.centos.noarch requires novnc < 0.6.0']
[ INFO  ] Yum Performing yum transaction rollback
[ ERROR ] Failed to execute stage 'Environment customization': [u'ovirt-engine-backend-4.2.1-0.0.master.20171226162249.git6e7cc87.el7.centos.noarch requires novnc < 0.6.0']
[ INFO  ] Stage: Clean up
          Log file is located at /var/log/ovirt-engine/setup/ovirt-engine-setup-20171227145711-6v6try.log
[ INFO  ] Generating answer file '/var/lib/ovirt-engine/setup/answers/20171227145731-setup.conf'
[ INFO  ] Stage: Pre-termination
[ INFO  ] Stage: Termination
[ ERROR ] Execution of setup failed

**Comment by michalskrivanek** [comment]
Hi, this error is from upgrading oVirt, this project is only about ovirt-web-ui (the VM Portal sub-application). Please file a bug i bugzilla against ovirt-engine (Integration team) and/or raise it on users@ovirt.org
Thanks
