### ISSUE TITLE
16 users limit in vm pool

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#456]
Moving here from BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1529258 to track it - copying the description:

Description of problem:
It is not possible to correctly assign a VM in the pool if the total number of assigned VMs in pools is greater than 16. After the 16th, the assigned VMs cease to appear in the vm portal
And if you create a pool Z-xx-pool in an empty cluster and start assigning a VM then after 16 the VM will no longer be displayed in the portal, but if you create another Y-xx-pool, you can assign 16 more VMs, etc., and they will be visible , but only for 16 users, the previous assigned VMs disappear from the portal.
Sense of sampling based on an alphabetical list of VMs with a limit of up to 16 users.

How reproducible:
always

Steps to Reproduce:
1. on clean install oVirt 4.2 create stateful pool with 1 VM per user
2. add active directory auth
2. assign permissions to pool for ad group
3. from users start running VMs

Actual results:
In vm portal not see assigned VM

Expected results:
abilities run VM without this limit

Additional info:

**Comment by jelkosz** [comment]
possibly related to https://github.com/oVirt/ovirt-web-ui/issues/457

**Comment by michalskrivanek** [comment]
@leistnerova, you've tried pools too, right? can you confirm it works now?

**Comment by leistnerova** [comment]
Yes I started VMs from pool on 1.3.6 with success, but not so many VMs and not so many users. I'll try it.
