### ISSUE TITLE
user with UserRole does not see VM started from pool

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#457]
User has only UserRole for a pool (5 VMs attached) and starts a VM from it. The started VM is not visible in the VM portal.
The user has UserRole on the started VM. I see that in admin portal.

Tested in ovirt-web-ui-1.3.4-1.el7ev.noarch

**Comment by mareklibra** [comment]
Ideas:
- refresh with paging does not reflect that
- engine does not report the VM (less probably)

**Comment by leistnerova** [comment]
I updated engine to ovirt-engine-4.2.1-0.2.el7.noarch with ovirt-web-ui-1.3.4-1.el7ev.noarch
and it works fine now.
