### ISSUE TITLE
VM with UserRole not displayed

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#460]
copied from https://bugzilla.redhat.com/show_bug.cgi?id=1532186

**Comment by michalskrivanek** [comment]
@leistnerova, what did you change in #457 that it suddenly works? the ovirt-web-ui version is the same in both of your comments

**Comment by c516a** [comment]
Hi,

I have Version 4.2.0.2-1.el7.centos and I can't see my vms in our Vm portal.

This is the affected packages:
ovirt-engine-4.2.0.2-1.el7.centos.noarch
ovirt-web-ui-1.2.1-1.el7.centos.noarch

Best Regards,
Cs

**Comment by leistnerova** [comment]
I updated engine to ovirt-engine-4.2.1-0.2.el7.noarch and that seems to resolve the problem.

**Comment by mareklibra** [comment]
@c516a , is it working with new version? Recent ovirt-web-ui is 1.3.4.

**Comment by c516a** [comment]
Thank you,
How can I install this update?

engine-setup dosen't updated, this package.
Shpul I use the yum update?

Best Regards,
Cs

**Comment by c516a** [comment]
Hi

This my webui:


ovirt-web-ui-1.3.4-1.el7.centos.noarch

And this is my ovirt-engine:

ovirt-engine-4.2.0.2-1.el7.centos.noarch

How can I do update my 4.2.0.2-1 to ovirt-engine-4.2.1-0.2 engine?

Thank you!
Version 4.2.0.2-1.el7.centos

**Comment by jelkosz** [comment]
@c516a can you please paste here the content of your ovirt repo files (e.g. the files in /etc/yum.repos.d/ovirt-*).

Thank you.

**Comment by c516a** [comment]
Hi Jelkosz

[ovirt-4.0-epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=0
includepkgs=epel-release,python-uinput,puppet,python-lockfile,python-cpopen,python-ordereddict,python-pthreading,python-inotify,python-argparse,novnc,python-ply,python-kitchen,python-daemon,python-websockify,livecd-tools,spice-html5,mom,python-IPy,python-ioprocess,ioprocess,safelease,python-paramiko,python2-paramiko,python2-crypto,libtomcrypt,libtommath,python-cheetah,python-ecdsa,python2-ecdsa,python-markdown,rubygem-rgen,ovirt-guest-agent*,userspace-rcu,protobuf-java,objenesis,python34*
gpgcheck=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

[ovirt-4.0-centos-gluster37]
name=CentOS-7 - Gluster 3.7
baseurl=http://mirror.centos.org/centos/7/storage/$basearch/gluster-3.7/
gpgcheck=1
enabled=0
gpgkey=https://raw.githubusercontent.com/CentOS-Storage-SIG/centos-release-storage-common/master/RPM-GPG-KEY-CentOS-SIG-Storage

[ovirt-4.0-patternfly1-noarch-epel]
name=Copr repo for patternfly1 owned by patternfly
baseurl=http://copr-be.cloud.fedoraproject.org/results/patternfly/patternfly1/epel-7-$basearch/
enabled=0
skip_if_unavailable=1
gpgcheck=0

[virtio-win-stable]
name=virtio-win builds roughly matching what was shipped in latest RHEL
baseurl=http://fedorapeople.org/groups/virt/virtio-win/repo/stable
enabled=0
skip_if_unavailable=1
gpgcheck=0

[centos-ovirt40-release]
name=CentOS-7 - oVirt 4.0
baseurl=http://mirror.centos.org/centos/7/virt/$basearch/ovirt-4.0/
gpgcheck=0
enabled=0

[ovirt-4.0]
name=Latest oVirt 4.0 Release
#baseurl=http://resources.ovirt.org/pub/ovirt-4.0/rpm/el$releasever/
mirrorlist=http://resources.ovirt.org/pub/yum-repo/mirrorlist-ovirt-4.0-el$releasever
enabled=0
skip_if_unavailable=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-ovirt-4.0
[ovirt-4.1-epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=1
includepkgs=epel-release,python-uinput,puppet,python-lockfile,python-cpopen,python-ordereddict,python-pthreading,python-inotify,python-argparse,novnc,python-ply,python-kitchen,python-daemon,python-websockify,livecd-tools,spice-html5,mom,python-IPy,python-ioprocess,ioprocess,safelease,python-paramiko,python2-paramiko,python2-crypto,libtomcrypt,libtommath,python-cheetah,python-ecdsa,python2-ecdsa,python-markdown,rubygem-rgen,ovirt-guest-agent*,userspace-rcu,protobuf-java,objenesis,python34*,hystrix-core,archaius-core,rxjava,jctools,hystrix-metrics-event-stream,jackson-core,python-simplejson
gpgcheck=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

[ovirt-4.1-centos-gluster38]
name=CentOS-7 - Gluster 3.8
baseurl=http://mirror.centos.org/centos/7/storage/$basearch/gluster-3.8/
gpgcheck=1
enabled=1
gpgkey=https://raw.githubusercontent.com/CentOS-Storage-SIG/centos-release-storage-common/master/RPM-GPG-KEY-CentOS-SIG-Storage

[ovirt-4.1-patternfly1-noarch-epel]
name=Copr repo for patternfly1 owned by patternfly
baseurl=http://copr-be.cloud.fedoraproject.org/results/patternfly/patternfly1/epel-7-$basearch/
enabled=1
skip_if_unavailable=1
gpgcheck=0

[virtio-win-stable]
name=virtio-win builds roughly matching what was shipped in latest RHEL
baseurl=http://fedorapeople.org/groups/virt/virtio-win/repo/stable
enabled=1
skip_if_unavailable=1
gpgcheck=0

[ovirt-centos-ovirt41]
name=CentOS-7 - oVirt 4.1
baseurl=http://mirror.centos.org/centos/7/virt/$basearch/ovirt-4.1/
gpgcheck=0
enabled=1

[centos-opstools-release]
name=CentOS-7 - OpsTools - release
baseurl=http://mirror.centos.org/centos/7/opstools/$basearch/
gpgcheck=0
enabled=1
skip_if_unavailable=1

[sac-gdeploy]
name=Copr repo for gdeploy owned by sac
baseurl=https://copr-be.cloud.fedoraproject.org/results/sac/gdeploy/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/sac/gdeploy/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
[ovirt-4.1]
name=Latest oVirt 4.1 Release
#baseurl=http://resources.ovirt.org/pub/ovirt-4.1/rpm/el$releasever/
mirrorlist=http://resources.ovirt.org/pub/yum-repo/mirrorlist-ovirt-4.1-el$releasever
enabled=1
skip_if_unavailable=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-ovirt-4.1
[ovirt-4.2-epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=1
includepkgs=
 epel-release,
 ioprocess,
 libtomcrypt,
 libtommath,
 ovirt-guest-agent*,
 puppet,
 python2-crypto,
 python2-ecdsa,
 python2-paramiko,
 python34*,
 python-argparse,
 python-ecdsa,
 python-ioprocess,
 python-ordereddict,
 python-paramiko,
 python-ply,
 rubygem-rgen

gpgcheck=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

[ovirt-4.2-centos-gluster312]
name=CentOS-7 - Gluster 3.12
baseurl=http://mirror.centos.org/centos/7/storage/$basearch/gluster-3.12/
gpgcheck=1
enabled=1
gpgkey=https://raw.githubusercontent.com/CentOS-Storage-SIG/centos-release-storage-common/master/RPM-GPG-KEY-CentOS-SIG-Storage


[ovirt-4.2-virtio-win-latest]
name=virtio-win builds roughly matching what will be shipped in upcoming RHEL
baseurl=http://fedorapeople.org/groups/virt/virtio-win/repo/latest
enabled=1
skip_if_unavailable=1
gpgcheck=0

[ovirt-4.2-centos-qemu-ev]
name=CentOS-7 - QEMU EV
baseurl=http://mirror.centos.org/centos/7/virt/$basearch/kvm-common/
gpgcheck=1
enabled=1
gpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Virtualization

[ovirt-4.2-centos-opstools]
name=CentOS-7 - OpsTools - release
baseurl=http://mirror.centos.org/centos/7/opstools/$basearch/
gpgcheck=1
enabled=1
gpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-OpsTools

[centos-sclo-rh-release]
name=CentOS-7 - SCLo rh
baseurl=http://mirror.centos.org/centos/7/sclo/$basearch/rh/
gpgcheck=1
enabled=1
gpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-SCLo

[ovirt-4.2-centos-ovirt42]
name=CentOS-7 - oVirt 4.2
baseurl=http://mirror.centos.org/centos/7/virt/$basearch/ovirt-4.2/
gpgcheck=1
enabled=1
gpgkey=https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Virtualization
[ovirt-4.2]
name=Latest oVirt 4.2 Release
#baseurl=http://resources.ovirt.org/pub/ovirt-4.2/rpm/el$releasever/
mirrorlist=http://resources.ovirt.org/pub/yum-repo/mirrorlist-ovirt-4.2-el$releasever
enabled=1
skip_if_unavailable=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-ovirt-4.2


Thank you

**Comment by jelkosz** [comment]
OK, so the thing is that you have the stable version of oVirt and 4.2.1 has not yet been released, so you need to wait for about a week or so to get it there.
If you dont want to to wait, than you can try to install the nightly build - details here: https://ovirt.org/download/ - but I would not do this for production setup.

**Comment by jniederm** [comment]
Possible cause https://bugzilla.redhat.com/show_bug.cgi?id=1534607

**Comment by c516a** [comment]
Dear jelkosz,

Thank you we are winting to the 4.2.1.

Best Regards,
Cs

**Comment by jniederm** [comment]
> Dear jelkosz,
>
> Thank you we are winting to the 4.2.1.
>
> Best Regards,
Cs

The fix probably depends on https://bugzilla.redhat.com/show_bug.cgi?id=1534607. Which means update to 4.2.1 most likely won't help.

**Comment by c516a** [comment]
Dear jniederm,

What Should I do? :(
Cs

**Comment by jelkosz** [comment]
> What Should I do? :(

well, you have two options:
1: wait until the 4.2.2 is out which will contain the fix for this issue
2: there is a nasty workaround to this issue. The thing is that the bug is in filtering the VMs the user has permissions to. You could workaround it by making sure the user can see all the vms which are in a system (either by giving him some admin permission or assigning user role on the whole system). If you do this, the filtering of the permissions will not get into way and your user will see all the vms. The downside is that he will see all the vms...

I understand that none of this two options is good. Sorry about that :(

**Comment by rcprior** [comment]
There is another, even nastier option, in case you really need users to see only their VMs.
The issue appears to be that filtering is done by the application (server-side), but pagination is passed to the database, the default being max. 8 results per page. This means that if a user does not have permissions for any of the first 8 VMs in the system (as alphabetically sorted), (s)he will see no VMs.
A dirty temporary solution (until 4.2.2 is released) is to edit the javascript file under /usr/share/ovirt-web-ui/ovirt-web-ui.war/static/js/  and change the string "vms/;max=" to "vms/;max=9". This way, the user only needs to have permissions on one VM among the first 98 to be able to see it (use a larger number if necessary).

**Comment by michalskrivanek** [comment]
this should now work with 4.2.2 candidate builds

**Comment by c516a** [comment]
Dear Michal,

Thank you very much.

Cs

**Comment by michalskrivanek** [comment]
@leistnerova verified with 4.2.2 and ovirt-web-ui 1.3.6
