### ISSUE TITLE
branding - missing files should produce 404

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#461]
When branding.jsp cannot find a file, it should send a 404. Currently it sends 200 and an empty response.

![selection_415](https://user-images.githubusercontent.com/2248293/34905587-0f6e1c82-f82a-11e7-98b4-a4ec8b37502b.png)

![selection_414](https://user-images.githubusercontent.com/2248293/34905588-11c1fb3e-f82a-11e7-8140-d91bdc1b934b.png)

From the code, it's clearly supposed to send a 404, but something's broken.

**Comment by sgratch** [comment]
An old issue and since no one complain till now then closing
