### ISSUE TITLE
cloud-init and VM Portal - unable to pass VM name to cloud-init to be set as hostname

### ISSUE THREAD

**Issue by mvrgotiks** [oVirt/ovirt-web-ui#468]
Created a VM template which configures all but hostname, using cloud-init.
Since the fastest way for user to access VM is to use Address (only FQDN shown) hostname needs to be set.
In order to be able to create VMs and just use them, it would be good to configure so that the VM Name entered to be passed as hostname to cloud-init.

Expected/wanted behavior:

1. Create a VM: In the Name field "vmguest02.example.com"
![screen shot 2018-01-25 at 14 14 04](https://user-images.githubusercontent.com/17527581/35390006-3370c0da-01da-11e8-8606-e463db1a8229.png)
2. The cloud-init completes the hostname (passed from Name filed) / user / timezone / ssh key / network / custom scripts defined
3. The VM is created and this is how it looks in the VM details:
![vm created with wanted hostname](https://user-images.githubusercontent.com/17527581/35390335-528ac76c-01db-11e8-8b48-e34a41c96fcf.png)

Currently, Address filed remains empty, and user needs to download console.vv , parse file, login, set hostname.

If more information is needed, I will gladly provide.

**Comment by mvrgotiks** [comment]
Hi all,
What is priority on this one? With current state, VM Portal is pretty much "useless" for regular users.
I had to solve this by creating Trimmed Admin access for my Users, so that they can spawn VMs.

Thank you.

**Comment by michalskrivanek** [comment]
there's no cloud-init support in ovirt-web-ui yet. We want to add a limited one in #486 

For your use case above, can't you set the hostname using DHCP?

**Comment by mvrgotiks** [comment]
Dear Michal,

That is an option I am considering it, but atm  I am not in hurry with it.

My current Users group is mostly Operations and they need features, which are not available in VM Portal, so they use limited Admin login.

However, it will be required to solve ovirt-web-ui part, once I start onboarding developers and trainees onto the platform.

In the meantime, I will follow progress of the #486<https://github.com/oVirt/ovirt-web-ui/issues/486> . Btw. Thank you for accepting my suggestion #468.

Best regards,
Marko Vrgotic
