### ISSUE TITLE
ovirt-4.1 cannot import the appliance image

### ISSUE THREAD

**Issue by chenqifeng28** [oVirt/ovirt-web-ui#472]
I download a appliance from manageiq.org/download，now i have uploaded the appliance by using the administration portal, next i want  import it as a template and create a virtual machine.
But,i found i cannot upload the appliance to the export storage domain,
![import2](https://user-images.githubusercontent.com/32876594/35685576-13964fe8-07a5-11e8-8661-179112857d6d.JPG)

another problem , 
"Click the Storage tab, then select the export storage domain you uploaded the image to.
From the details pane, click the Template Import tab, and select the image (newimagename) you uploaded." the Template Import tab cannot click
![import1](https://user-images.githubusercontent.com/32876594/35685672-4f9aef3a-07a5-11e8-8187-00f0262c4bb2.JPG)
The same situation also appears in the VM Import tab
![import3](https://user-images.githubusercontent.com/32876594/35685928-01931a32-07a6-11e8-997f-05312eb0bd76.JPG)

thx.

**Comment by michalskrivanek** [comment]
sorry, this is not the right project for your issue
webadmin issues are tracked as part of "ovirt-engine" product at bugzilla.redhat.com.

as for your issues - it would be best to consult users@ovirt.org first

Thanks,
michal
