### ISSUE TITLE
wrong behavior of console option for ctrl+alt+del

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#476]
* Switch in Userportal console options works reversely. 
* Help message is trimmed.

Version-Release number of selected component (if applicable):
ovirt-web-ui-1.3.5-1.el7ev.noarch
rhev-4.2.1.5-0.1.el7

How reproducible:
always

Steps to Reproduce:
1.Go to 'VM Portal' and choose some VM guest
2.Click to open next to console to open its properties
3.Switch 'Use Ctrl+Alt+Del' option 'ON'  - so in this case (it is 'ON') this shortcut should be used
4. click to 'Console' button open vv file in text editor

Actual results:
* Label 'Use Ctrl+Alt+Del' does not correspond the result in vv file: It contains line 'secure-attention=ctrl+alt+end'

Expected results:
* file contains line 'secure-attention=ctrl+alt+del'

Important remarks:
* If I invoke help message by mouse clicking on 'Use ctrl+alt+del' label, it reads: 'Del keyboard shortcut to Ctrl+Alt+End'. I inspected the userportal webpage and found that proper message should be 'Map Ctrl+Alt+Del keyboard shortcut to Ctrl+Alt+End' - so if this is the right meaning of the switch, its behaviour is not reversed. Then would be enough to enlarge window with help message and rename the label to 'Use Ctrl+Alt+End'.

**Comment by rdkdd** [comment]
![screenshot from 2018-02-06 10-52-55](https://user-images.githubusercontent.com/18483085/35915679-1ba60266-0c08-11e8-8444-00cde40bd48f.png)

**Comment by bond95** [comment]
@rdkdd Fix of this problem already here https://github.com/oVirt/ovirt-web-ui/pull/469
