### ISSUE TITLE
More Edit VM options

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#478]
More rich Edit VM functionality, namely
* Console type (VNC, SPICE...)
* Add disks
* Add NIC interfaces
* Modify the boot sequence
* Attach a CD-ROM iso

reference: http://lists.ovirt.org/pipermail/users/2018-February/086761.html

**Comment by michalskrivanek** [comment]
Disks and NICs are likely possible only for attaching existing ones, otherwise bit too complex.

Patches welcome

**Comment by nkovacne** [comment]
The CD-ROM part is already implemented. However, a basic operation like changing the console type from Native to noVNC is not...

I think we could make a basic template with the hardware settings so students can deploy a basic machine (with nics and disks) so they would install only the OS, but without the console options we can't upgrade. We will stick to the 4.1.9 version until then.

**Comment by michalskrivanek** [comment]
"changing the console type from Native to noVNC is not." - that has nothing to do with VM configuration. That's a client-side choice of which console client to use to connect.

There's a related work on console component (https://trello.com/c/mbOJfPQb) which would make sense to use in ovirt-web-ui eventually.

**Comment by praburaj1985** [comment]
Hi,
 please provide the above mentioned issue for me also

**Comment by mykaul** [comment]
@michalskrivanek  - please split it to specific issues.

**Comment by michalskrivanek** [comment]
Will separate into
- add/remove disk
- add/remove NIC
- use cloud-init with root ssh key and hostname
- enable boot menu

**Comment by nkovacne** [comment]
Should we open another one for adding the console interface (native, noVNC...) on the VM portal?

**Comment by michalskrivanek** [comment]
see previous comment, that is not a VM property. That's a client-side behavior. How would you want it to behave?

**Comment by nkovacne** [comment]
I understand that, but the user should be able to choose whether they want to use VNC as Native or noVNC from the User portal. Right now there's no choice, User Portal assumes the user will use Native client and there's no way to change that.

**Comment by michalskrivanek** [comment]
yep, because there's no "novnc" in the project. That's part of that component I mentioned, though UI-wise it's going to be different. I opened #490
