### ISSUE TITLE
"empty" place in VMs list

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#479]
Description of problem:

VM portal shows an empty place in vm list when having many vms. It seems no predictable after how many vms this place appears.

see screenshot

Version-Release number of selected component (if applicable):
ovirt-web-ui-1.3.5-1.el7ev.noarch

How reproducible:
100%

Steps to Reproduce:
1. have many vms, open vm portal
2.
3.

Actual results:
see how vm list is rendered

Expected results:
from time to time there's empty space instead of a vm in vm list

screenshot https://bugzilla.redhat.com/attachment.cgi?id=1392728

**Comment by mareklibra** [comment]
No matter I'm logged in bugzilla, the screenshot link shows be "Access Denied"

**Comment by michalskrivanek** [comment]
yeah, seems it's not working:/

**Comment by bond95** [comment]
Original Issue: https://github.com/oVirt/ovirt-web-ui/issues/414
Bug fix: https://github.com/oVirt/ovirt-web-ui/pull/475
