### ISSUE TITLE
tooltip boxes too thin in VM options

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#480]
Description of problem:

[VM portal] tooltip boxes too thin in VM options, see screenshot.

Version-Release number of selected component (if applicable):
ovirt-web-ui-1.3.5-1.el7ev.noarch

How reproducible:
100%

Steps to Reproduce:
1. check all tooltip boxes for VM values
2.
3.

Actual results:
most of them are too thin

Expected results:
should be eye-candy, not 90ies

screenshot https://bugzilla.redhat.com/attachment.cgi?id=1392753

**Comment by michalskrivanek** [comment]
the link doesn't work, but it should work through the original bz - https://bugzilla.redhat.com/show_bug.cgi?id=1543034

**Comment by bond95** [comment]
Fixed here https://github.com/oVirt/ovirt-web-ui/pull/469
![image](https://user-images.githubusercontent.com/3332176/36264612-7a552182-126d-11e8-9fe3-0263329a211d.png)
