### ISSUE TITLE
clicking on line to get help in VM Edit page does nothing

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#481]
clicking on line to get help in VM Edit page does nothing, see screenshot

Version-Release number of selected component (if applicable):
ovirt-web-ui-1.3.5-1.el7ev.noarch

How reproducible:
100%

Steps to Reproduce:
1. open EDit page of a VM in VM Portal
2. click on Name, Description etc...
3. 

Actual results:
nothing happens

Expected results:
either remove underline which causes a user to feel there's clickable tooltip
or make some help appear in tooltip

screenshot https://bugzilla.redhat.com/attachment.cgi?id=1392767

**Comment by bond95** [comment]
Fixed here https://github.com/oVirt/ovirt-web-ui/pull/469
