### ISSUE TITLE
Adjust min memory while editing memory when necessary

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#499]
If a VM is being edited and memory is decreased below min memory (*Physical Memory Guaranteed*) level, following error message is shown:
![image](https://user-images.githubusercontent.com/5278760/36673727-092d4b70-1b04-11e8-96e6-a742dc66f975.png)

**Comment by sjd78** [comment]
I interpret the issue as the UI requiring validation such that the memory field on edit dialog cannot be reduced below the physical memory guaranteed mark.  Then, if a user does edit below that mark, the form would show an error message and the edit wouldn't be submitted.

Is this correct?

Another interpretation would be that the physical memory guaranteed needs to be adjusted down in step with the min memory set by the user.  In that case, both field need to be updated for the REST call, and the REST edit needs to accept those changes.

@jelkosz, I know you said is it the latter option, but I wanted to put the discussion back online.

**Comment by sjd78** [comment]
Ah, so following the data path with more attention to payloads ... in ovirtapi.js, addNewVm() calls OvirtApi.internalVmToOvirt() which filters fields from the vm state to an API call vm.  The 'memory_policy' bit of the vm isn't passed to the API call.  I'll patch that filter function tomorrow and see if that fixes everything.

**Comment by jelkosz** [comment]
@sjd78 yep, it needs to be adjusted automatically. But I'm afraid it will not work, since in the engine's API code I have not seen that used at all (but maybe I just missed it, it was friday afternoon :) ). If it won't work, please open a bug against ovirt-engine's API to virt team and paste the BZ URL here.

**Comment by jelkosz** [comment]
patch merged, closing
