### ISSUE TITLE
Don't show VM edit button for user that hasn't permission for it

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#504]
User with only UserRole for VM still can go to edit dialog from grid. It shouldn't be allowed.
Error appears after submit of edit form.

![screenshot from 2018-03-01 11-58-09](https://user-images.githubusercontent.com/29575480/36841520-cca96ba6-1d48-11e8-8a4d-8076ce9f7eba.png)

**Comment by leistnerova** [comment]
Notice: User with UserVMManager role on DC with Quota still cannot edit the VM. The user must be also Quota consumer.
Error - VM_DIALOG_EDIT_VM failed [Cannot edit VM. The user is not a consumer of the Quota assigned to the resource.]

**Comment by michalskrivanek** [comment]
we likely won't have such a granularity, but in general at least some basic differentiation should be done as part of  #507
