### ISSUE TITLE
When no SSH key is stored, Options dialog shows 'Loading...'

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#505]
When no SSH key for logged user is saved in the engine, Options dialog shows in SSH key 'Loading...' and that doesn't change.

Tested in FF and Google Chrome on ovirt-web-ui-1.3.6-1

![screenshot from 2018-03-01 13-34-30](https://user-images.githubusercontent.com/29575480/36845052-7bf20fd0-1d55-11e8-9fcc-e6ed1d8f4e68.png)

**Comment by mareklibra** [comment]
Still seen, @leistnerova

**Comment by leistnerova** [comment]
Sorry, I did not see, that it's already reported.
https://github.com/oVirt/ovirt-web-ui/issues/730
