### ISSUE TITLE
Create VM: filter out only relevant entities

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#507]
We have a read-only visibility to everything and typically users do not have access to e.g. all DCs or Templates, we should filter out those which are not relevant. We do not really have a suitable support in API but a rough role-based filtering could be good enough (working for predefined roles only).

- Create button available only if VmCreator/InstanceCreator/PowerUserRole/admin on any Cluster/DC/System
- once we have #489 with SDs filter out relevant SDs - DiskCreator/PowerUserRole/StorageAdmin/SuperUser on any SD/DC/System. For now just check permissions on what's in the template
- Similarly for networks once we have #488

**Comment by michalskrivanek** [comment]
+ a Blank template
when no Template selected?

**Comment by gregsheremeta** [comment]
@lizsurette let's consider this for New VM flow redesign
