### ISSUE TITLE
'failed Not found' error with Connect automatically console option

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#509]
Error shown every time user enters detail of VM for which user opened console automatically.

Steps to reproduce:
1. log to VM portal, select some VM and in detail set Connect automatically to ON
2. start the VM
3. log out from the portal
4. log again, console for the VM is started, open it
5. go to the VMs detail

The same happened when I changed the option for other VM. Then the error appears by both of the VMs.

Error in console:
XML Parsing Error: no root element found
Location: https://engine/ovirt-engine/api/vms/ebbcfa95-8a10-4cde-a884-e588ef7313f4/sessions
Line Number 1, Column 1:

Tested in ovirt-web-ui-1.3.6-1.fc26.noarch
![screenshot from 2018-03-05 12-09-40](https://user-images.githubusercontent.com/29575480/36973444-4f9e91bc-2073-11e8-8d36-ee4e91d84a10.png)

**Comment by sjd78** [comment]
Note to self - doing the steps while logged in as admin works ok.  I need to check logged in as a normal user.

**Comment by sjd78** [comment]
* If the console was previously opened by any user account, the "failed Not Found" message is displayed.
 * If the console was previously opened by an admin account, no error is displayed.

The VMs console just needs to be opened previously for the error to occur (but only on user accounts).

**Comment by bond95** [comment]
In ovirt-web-ui-1.3.8-2.el7ev.noarch everything works fine.

**Comment by sjd78** [comment]
@bond95 - you may want to check again using non-admin accounts.  Everything works just fine with admin accounts.

I can easily reproduce the error on master web-ui attached to master ovirt-engine.

**Comment by michalskrivanek** [comment]
@sjd78,
well that's the thing, we tried yesterday with normal users (confirmed in UI, it's non-admin icon, it only has UserVmManager on the VM - which is a user role too)
can you make the setup available perhaps? or can you try that against other setup?

separate thing is when admin opens a console and then user opens it - that should fail with 403 Forbidden - and it does in our testing

**Comment by bond95** [comment]
@sjd78 I asked @leistnerova to try it again. And she said that everything works fine.

**Comment by sjd78** [comment]
I permissioned my users with "UserRole", not "UserVmManager".  Perhaps that is the difference?

The engine I tested against is running "4.3.0-0.0.master.20180318174139.git9657fd0.el7.centos".  It is an ovirt-node self hosted engine setup.

I compiled the lasted ovirt-engine master and I'm setting the test back up.  I'll let you know how it goes.  I'll also try a user with "UserRole" role vs a user with "UserVmManager" role.  If it is fixed then great!

**Comment by sjd78** [comment]
The user role does make a difference.

With master ovirt-engine and master ovirt-web-ui, if my user is permissioned with **UserRole** role, the "Not Found" error still happens.

If my user is permissioned with **UserVmManager** role, no error happens.

**Comment by sjd78** [comment]
Screen capture demonstrating the issue on my local dev: https://youtu.be/iIcNc8--8gw

**Comment by jelkosz** [comment]
based on ^^^^ reopening

**Comment by michalskrivanek** [comment]
It seems it’s a code-level problem with Console details/access when you only have a UserRole -that’s a major use case for ovirr-web-ui and needs to be fixed ASAP

**Comment by sjd78** [comment]
@michalskrivanek - I'm unclear as to if you are saying it is a code-level problem in web-ui or in the REST api.  Can you elaborate?

Should the web-ui take different steps for a **UserRole** user accessing the console then for an admin or **UserVmManager**?  If that is the case, do you know how to check user role permissions via REST?

**Comment by jelkosz** [comment]
so the bug is indeed on the API layer: https://bugzilla.redhat.com/show_bug.cgi?id=1568669#c3

**Comment by sjd78** [comment]
@leistnerova - Lucie, can you give this another test now the REST API has been updated?

I did some basic testing and it looks better, but I'm not sure if it quite good enough.  Maybe a better error message through better error detection code?

**Comment by gregsheremeta** [comment]
ping @leistnerova

**Comment by gregsheremeta** [comment]
untargeting for now. Once we hear back from Lucie, @sjd78 please scope effort and I'll schedule it

**Comment by leistnerova** [comment]
No error, with UserRole and UserVmManager also.

Tested in ovirt-web-ui-1.4.0-3.fc28.noarch, with ovirt-engine-4.2.5.1-0.1.el7ev.noarch

**Comment by gregsheremeta** [comment]
@leistnerova great thanks! I don't see anything else to do here -- closing

**Comment by sjd78** [comment]
@gregsheremeta - We should note that no change was done on the web-ui side to address this issue.  The change was on the REST api that got released in **ovirt-4.2.4**.
