### ISSUE TITLE
enhance error message for VM console already opened by other user

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#510]
When user wants to open console that was already opened by other user, error appears.

Failed to retrieve VM console details
Forbidden

That's not much informative. It should tell the user that console is opened already by somebody else.

**Comment by sjd78** [comment]
@leistnerova - Is this still an issue?  After #860 / #861 I think this should be all sorted out correctly.

**Comment by gregsheremeta** [comment]
Closing per @sjd78 's comment
