### ISSUE TITLE
bootable disk is not first in disks list

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#511]
In VM's detail with more disks are the disks sorted only by name. So bootable disk could be in the end, but it should be always first no matter what name it has.

Tested in ovirt-web-ui-1.3.6-1.fc26.noarch
![screenshot from 2018-03-05 16-26-22](https://user-images.githubusercontent.com/29575480/36983262-31b085ec-2092-11e8-9918-1cb1f2c21769.png)
![screenshot from 2018-03-05 16-26-08](https://user-images.githubusercontent.com/29575480/36983267-35af20e0-2092-11e8-9618-ea7a5a9a4dc7.png)

**Comment by michalskrivanek** [comment]
well, that's debatable....

**Comment by leistnerova** [comment]
Could be, but it worked like that few version before.

**Comment by jelkosz** [comment]
> Could be, but it worked like that few version before.

probably coincidentally :) But I'd say it should at least be shown in some predictable order and I'm afraid now it is in the same order the API returns it to us which can be considered random.

**Comment by sjd78** [comment]
Also note that the webadmin sorts numeric aware.

![screenshot-engine local dickerson-web com-2018 04 04-23-45-55](https://user-images.githubusercontent.com/3985964/38346357-8c37c3b2-3862-11e8-8eea-5c259f1aa11c.png)

**Comment by mareklibra** [comment]
Fixed by #547
