### ISSUE TITLE
hidden error message when user is logged out

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#513]
When user is logged out error message appears but is not visible.

Steps to reproduce:
1. open two VM potals and log in with one user
2. in one portal log out
3. in the other one click on Reload button in top menu

Tested in ovirt-web-ui-1.3.6-1.fc26.noarch
![screenshot from 2018-03-06 08-20-22](https://user-images.githubusercontent.com/29575480/37019133-6770443a-2117-11e8-86c5-1f9de0ba1d9b.png)

**Comment by gregsheremeta** [comment]
@bond95 Bohdan, is this still an issue on the new main page?
