### ISSUE TITLE
Make VmDetail and VmDialog responsive

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-web-ui#529]
... to be able to dynamically adapt to variable length of translated messages.

This will save us from bugs like [[ja_JP, de_DE] [VM Portal] Text truncation observed on VM details screen](https://bugzilla.redhat.com/show_bug.cgi?id=1526389).

![image](https://user-images.githubusercontent.com/5278760/37516010-166b4424-290d-11e8-8bc4-87179a9d5d00.png)
---
![image](https://user-images.githubusercontent.com/5278760/37516029-241f8e22-290d-11e8-8653-a7e83190508e.png)

**Comment by mareklibra** [comment]
Hot-fixed for DE and JP: https://github.com/oVirt/ovirt-web-ui/pull/527
Needs better solution as described above.

**Comment by mareklibra** [comment]
Shall fix tight spacing even for: https://github.com/oVirt/ovirt-web-ui/pull/517

**Comment by bond95** [comment]
@mareklibra @jniederm What about this solution?
![image](https://user-images.githubusercontent.com/3332176/37900150-ab2c73ca-30ed-11e8-8556-6fa7b055cdf3.png)

**Comment by mareklibra** [comment]
multi-line descriptions would work for me, how how much does it hust @jniederm 's esthetic percpetion?

Anyway, for certain languages, and Genrman might be great example of that, word-splitting might be no option since they really enjoy wholestoryinasinglesenceofpackedasasingleeverevolvingword.

**Comment by bond95** [comment]
@mareklibra yes, but we can use smaller (splited) variants of words, or can't we?

**Comment by jniederm** [comment]
I believe we can easily agree on suggested multi-line layout not being nice and clean (icon is not vertically centered, dotted underline is too long) but it's a welcome enhancement before we get to a proper solution.

**Comment by bond95** [comment]
> icon is not vertically centered
Actually I can centered icon verticaly, but for me a little bit shifted down, looks better then fully centered.

**Comment by gregsheremeta** [comment]
Will be covered in redesign. @mareklibra close?

**Comment by gregsheremeta** [comment]
obsoleted by redesign, closing
