### ISSUE TITLE
Follow-ups to clean the `max-content` width

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#535]
Two PRs setting `width: max-content` were merged with unresolved review comments.
The feature is problematic in IE/Edge.

Folllow-ups are required to address
- [ ] https://github.com/oVirt/ovirt-web-ui/pull/520#discussion_r176662220
- [ ] https://github.com/oVirt/ovirt-web-ui/pull/518#issuecomment-373026076

**Comment by gregsheremeta** [comment]
obsoleted by redesign
