### ISSUE TITLE
do not show vNIC from other cluster by adding new network

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#542]
When I want to add new network to VM, vNIC profiles from other cluster are in select box. When choosing them, error appears and network is not created.

tested in ovirt-web-ui-1.3.7-2.el7ev.noarch with ovirt-engine-4.2.2.4-0.1.el7.noarch

![screenshot from 2018-03-28 13-28-39](https://user-images.githubusercontent.com/29575480/38026315-ffaa7f60-328b-11e8-9b55-3be66dda03ab.png)

**Comment by michalskrivanek** [comment]
they're going to be filtered by #138
