### ISSUE TITLE
error by deleting disk

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#543]
When I delete disk from VM, after a while disk is removed and error in Messages appears - Failed to retrieve disk details Not Found. No error in engine.log.

tested in ovirt-web-ui-1.3.7-2.el7ev.noarch with ovirt-engine-4.2.2.5-0.1.el7.noarch

![screenshot from 2018-03-28 13-11-00](https://user-images.githubusercontent.com/29575480/38026637-20314902-328d-11e8-9487-eeb112ac93dc.png)

console error:
XML Parsing Error: no root element found
Location: https://engine/ovirt-engine/api/disks/0e8a4376-3456-4529-a39b-276c5d20293d
Line Number 1, Column 1:
0e8a4376-3456-4529-a39b-276c5d20293d:1:1
Ajax failed: {"readyState":4,"responseText":"","status":404,"statusText":"Not Found"}
helpers.js:19:6
External action exception: {"readyState":4,"responseText":"","status":404,"statusText":"Not Found"}
helpers.js:19:6
Reducing action:  {"type":"FAILED_EXTERNAL_ACTION","payload":{"message":"Failed to retrieve disk details\nNot Found","shortMessage":"Failed to retrieve disk details","type":404,"action":{"type":"GET_DISK_DETAILS","payload":{"diskId":"0e8a4376-3456-4529-a39b-276c5d20293d"}}}}
helpers.js:19:6
External action diskattachments() starts on {"type":"GET_DISK_ATTACHMENTS","payload":{"vmId":"8a305dfc-579e-4bcb-a444-6040c0403950"}}
helpers.js:19:6
_httpGet start: url="/ovirt-engine/api/vms/8a305dfc-579e-4bcb-a444-6040c0403950/diskattachments"
helpers.js:19:6
_httpGet: url="/ovirt-engine/api/vms/8a305dfc-579e-4bcb-a444-6040c0403950/diskattachments", headers="{"Authorization":"Bearer 9ba_IsbbWN7-eRPVFwGf1iWJoApLEU1dF0mYQelAGEm9bk4eFwy3vPLDdx9uTrUadK06kWbVz6RjF_hEqcCmlw","Accept-Language":"en_US","Accept":"application/json","Filter":false}"

**Comment by jelkosz** [comment]
I have a strong suspicion it is also related to #550

**Comment by sjd78** [comment]
Less #550 and more the __removeDisk()__ function in `src/components/VmDisks/sagas.js` is polling for the disk, waiting for a 404 before updating the VM disk list.
