### ISSUE TITLE
UI Filter does not work as expected [ tag != Server ]

### ISSUE THREAD

**Issue by elemhsb** [oVirt/ovirt-web-ui#548]
Hi,
i have a list of multiple tagged VM’s.

At the UI the filter (Compute >> Virtual Machines >> VMS: [ tag = Server ] works fine.

The opposite like [tag != Server] list ALL VM’s, not only the expected list
of VM **without** tag Server.

I run ovirt 4.2.2-6 with ovirt-web-ui.noarch in version: 1.3.7 release: 2.el7.centos.

**Comment by michalskrivanek** [comment]
Hi, this project only tracks "VM Portal". please file a bugzilla ticket against "Webadmin" component and "infra" oVirt team:
https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine
