### ISSUE TITLE
disable Boot menu switch in edit dialog when VM is running

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#549]
Boot menu switch can't be changed when VM is running. So it should be disabled. Now it seems that the value is changed, but editing VM again shows previous saved value.
In admin portal is showed flag that VM has new configuration for next run. This is other possibility how to fix this issue.

**Comment by leistnerova** [comment]
Adding warning for Boot menu every time VM is running is more confusing than helpful.

I agree with the warning description in help label.
Still when I change the value, VM portal shows the old one. So the proper solution should be that the VM portal remembers the change and shows it by the VM. And also shows that something was changed with warning icon and will be applied after reboot.  The icon could be by the whole VM in detail or grid view, not in the edit dialog.

**Comment by jniederm** [comment]
for future reference: this is about showing *current* x *next run* configuration difference.
