### ISSUE TITLE
Upgrade npm dependencies

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#558]
Upgrade referenced npm dependencies (package.json) to the latest versions.

For safety reasons, this will be done within scope of 1.4, will require manual testing.

**Comment by sjd78** [comment]
Do you plan on upgrading the webpack, eslint, babel versions to latest as well?

**Comment by mareklibra** [comment]
webpack is not a priority, but if reasonably feasible, it would be great.
All other packages are planed (incl. babel and eslint)
