### ISSUE TITLE
InfiniteScroller console warning about unique key

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#562]
Console log shows
```
VM27174 warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `InfiniteScroll`. It was passed a child from Vms. See https://fb.me/react-warning-keys for more information.
    in div (created by Vms)
    in InfiniteScroll (created by Vms)
    in Vms (created by Connect(Vms))
    in Connect(Vms) (created by VmsList)
    in VmsList (created by Connect(VmsList))
```

Works fine anyway, lower priority to make code clean.

**Comment by mohammad-khoddami** [comment]
Add key={0} to the loader fix it. see
https://github.com/oVirt/ovirt-web-ui/pull/616#issue-189719094

**Comment by arhamymr** [comment]
hello, i add key to infinite 

```
 <InfiniteScroll
        hasMore={hasMore}
        loader={<div key={0}/>}
        loadMore={loadFunc}
        pageStart={0}
      >
```

and still have warning in console, someone can help me ?

**Comment by nateg101** [comment]
Yes I too have the same problem - I am using V1.2.4

**Comment by sgratch** [comment]
@nateg101 @arhamymr this is an old issue. Is it reproduced for you on latest version 1.6.4 as well?

**Comment by frodolfo-duclo** [comment]
> Anybody still come out with the same issue? I use version 1.2.6 and there is still the same warning…

I also have this issue with version `1.2.6`, and it's **May 2023** now.

**Comment by Ruffeng** [comment]
If someone is facing this issue, make sure you wrap your component with a div and key:
```ts
loader={
  <div key={0}>
    <MyLoaderComponent />
  </div>
}
````
I was having this warning as well because the key was inside my component, but moving it in the same place as the `loader` prop solved the issue
