### ISSUE TITLE
delete disk on running vm does not show error message

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#564]
1: have a running VM
2: in VM detail press "Delete" on a disk
3: in engine log there is: "Validation of action 'RemoveDisk' failed for user admin@internal-authz. Reasons: VAR__ACTION__REMOVE,VAR__TYPE__DISK,ACTION_TYPE_FAILED_VM_IS_NOT_DOWN" but in UI there is no error message shown

**Comment by gregsheremeta** [comment]
looks like https://bugzilla.redhat.com/show_bug.cgi?id=1578469 is low priority and difficult. @jelkosz is this impossible otherwise?

**Comment by sjd78** [comment]
@gregsheremeta - The ability to delete a disk while a VM is running has been disabled in #838 (new details dashboard) and #849 (on legacy page).  This issue is no longer relevant.
