### ISSUE TITLE
reload on vm detail will drop me to vm list

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#566]
1: open a VM detail of some VM (not the edit, just detail)
2: press F5
3: it will load the list of VMs, not the details of the one in the URL

Please note that if I paste the same url into a new tab, it will properly drop me to the details of the VM which is in url, so it breaks only during refresh

**Comment by bond95** [comment]
Issue already opened. https://github.com/oVirt/ovirt-web-ui/issues/563
