### ISSUE TITLE
NIC hot unplug not work

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#569]
When I try to hot unplug NIC, I get these error:
![image](https://user-images.githubusercontent.com/3332176/38673816-a3bf5a72-3e52-11e8-84d6-2dbd49a65aa8.png)

If we don't support hot unplug, thus we can make `Delete` button disabled, for running VM.

**Comment by michalskrivanek** [comment]
Why is it not supported?

**Comment by bond95** [comment]
If `engine` support hot unplug, then ok, but why, in that case, `engine` returned `The VM Network Interface is plugged to a running VM.` error?
