### ISSUE TITLE
first click on vNIC profile select box item doesn't change the selected value

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#571]
When adding new network interface to VM, first click on vNIC profile select box item doesn't change the selected value <Empty>. Then it works as expected. No error in console.

Tested ovirt-web-ui-1.3.8-2.el7ev.noarch in FF 59.0.2 and Google Chrome 65.0.

**Comment by bond95** [comment]
Everything works fine.
Checked on ovirt-web-ui 1.4.0-pre in Google Chrome 65.0.3325.181 and Firefox 59.0.2
