### ISSUE TITLE
VM Snapshot management

### ISSUE THREAD

**Issue by Brian-Chow** [oVirt/ovirt-web-ui#573]
This functionality was dropped in the VM portal between 4.1 and 4.2.  I would like to see it brought back, as we use(d) it.

Use Case:
  We have created multiple sandbox templates for Developers to use while working on enterprise line of business applications.  Let developers log into the VM portal, create their own VM's, and manage their own VM snapshots from the VM portal, keeping them out of the Administrative Portal.  

Proposed Look/Behavior: Match the snapshot functionality in the Administrative Portal

**Comment by michalskrivanek** [comment]
it's not a reintroduction, this is a different project from the former GWT based User Portal.
The design needs to be done from scratch. If there are no concrete requests for functionality then we'll probably make some assumptions and simplifications.

I believe we can have a list of snapshots in details page(name plus memory status) and allow creating a new snapshot (I'd only support complete snapshots with/without memory) and "revert to" as a single action(with or without memory).

**Comment by gregsheremeta** [comment]
snapshot management is part of the redesign

**Comment by Brian-Chow** [comment]
@michalskrivanek Sorry for the delayed response, your listed assumptions fulfill our need for non-administrator vm users/vm portal users to be able to handle basic snapshot functionality on their own.  Thank you!

**Comment by gregsheremeta** [comment]
cc @jennyhaines @lizsurette
