### ISSUE TITLE
After reload Edit VM page, page become empty

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#574]
1. Open edit page of VM that not in first page (9th+ VMs)
2. Reload page

Result:
Empty page.

Expected:
VM edit page.

![image](https://user-images.githubusercontent.com/3332176/38991424-05ff0422-43de-11e8-81c9-92a117051a9f.png)

**Comment by sjd78** [comment]
The same issue occurs for VM view and Pool view.  If the VM or Pool is in fetch page >1, the view component won't ever be shown.  The main difference is that the VM edit page will sit on a blank page while the VM and Pool view pages will redirect the user back to the card view.

Both ways are incorrect.

For all 3 pages, if the VM or Pool cannot be loaded, an error message should be displayed.  If the VM or Pool isn't in the first fetch page, it should be fetched directly.

**Comment by bond95** [comment]
@sjd78 the problem is in `loadInProgress` flag of VM reducer. When you open VM detail page it try to fetch VM and VMs list, and there is the question, what will be fetched first. If VMs list, thus it set `loadInProgress` flag to `false`,  `VmDetailPage` component look at it, and will think that VM was not found, thus return `null`. Same with pools.

**Comment by sjd78** [comment]
Plus, there currently is no handling for if the **vmId** on the URL is invalid or if it doesn't exists anymore.

**Comment by bond95** [comment]
> VmDetailPage and PoolDetailPage both wait until login has finished (which for some reason is Selectors.isFilterChecked()) before fetching the VM/Pool directly. VmDialogPage didn't so the Filter API headers were not set correctly and the API.getVm got a 404. I updated them to all match and the VM loads (without a 404 since the API Filter headers are set correctly now) and the edit page renders.

Hmm... I never got this error before.

> Initially I thought it was a race between a single VM fetch and the initial data load and who flipped loadInProgress false first. However, this is not the core problem. And really it doesn't matter since the pages are connected to the state.vms and would get re-rendered on update regardless of which one gets merged to the store first.

For prove that problem is in `loadInProgress`, I did this trick in `VmDetailPage`:
```
    /*return <Redirect to='/' />*/
    return null
```
And everything works fine, problem gone, thus problem is in `loadInProgress` and fetch race.

> Starting from the VmDetailPage and PoolDetailPage don't seem to run into that issue simply because the left navigation VM/Pool list will (mostly likely, probably) load most of the pages before the next REFRESH_DATA. The user could see the same disappearing/reappearing trick if the VM was sufficiently deep in the pages and the nav list didn't load that page before the refresh.

Not exactly, because if you look at `fetchByPage` sagas function, you'll see that it fetch VMs page by page, and in the end of page fetching it set `loadInProgress` to `false`, thus even if `VmsListNavigation` component start fetching next page, and selected VM not be in that next page, `fetchByPage` set `loadInProgress` to `false`, and this will cause redirecting to main page.

**Comment by sjd78** [comment]
>> Initially I thought it was a race between a single VM fetch and the initial data load and who flipped loadInProgress false first. However, this is not the core problem. And really it doesn't matter since the pages are connected to the state.vms and would get re-rendered on update regardless of which one gets merged to the store first.
> 
> For prove that problem is in loadInProgress, I did this trick in VmDetailPage:
> 
>     /*return <Redirect to='/' />*/
>     return null
> 
> And everything works fine, problem gone, thus problem is in loadInProgress and fetch race.

Hitting the redirect for `VmDetailPage` and `PoolDetailPage` before the individual VM/Pool is fetched is indeed a fetch race problem.  However, the redirect isn't a good solution.  A user getting redirected to the card page, without an error message, when they've bookmarked a particular VM that has been removed isn't good.

`VmDialogPage` never had a redirect.  So it isn't sensitive to `loadInProgress` fetch race.  But it also makes it sensitive to getting left blank as a VM fails to load and no error is reported.  It is then also sensitive to getting the VM removed on a REFRESH_DATA cycle (which will happen if the VM isn't on a page that has already been loaded).

>> Starting from the VmDetailPage and PoolDetailPage don't seem to run into that issue simply because the left navigation VM/Pool list will (mostly likely, probably) load most of the pages before the next REFRESH_DATA. The user could see the same disappearing/reappearing trick if the VM was sufficiently deep in the pages and the nav list didn't load that page before the refresh.
>
> Not exactly, because if you look at fetchByPage sagas function, you'll see that it fetch VMs page by page, and in the end of page fetching it set loadInProgress to false, thus even if VmsListNavigation component start fetching next page, and selected VM not be in that next page, fetchByPage set loadInProgress to false, and this will cause redirecting to main page.

With redirects to the main page taken out, as I believe they should be, the race is between when `VmsListNavigation` loads a VM's page and when REFRESH_DATA gets fired to remove the VM from **store.vms**.  Even with the redirects in place, it is possible that the single VM fetch wins the `loadInProgress` race, `VmsListNavigation` doesn't get to that page before REFRESH_DATA triggers and the page gets shown initially but then suddenly gets redirected back to the card list.  Not ideal, and we can do better.

I'm planning on:
- Adding explicit VM fetch error handling so a specific message can be displayed
- Updating the REFRESH_DATA / fetchByPage / fetchByCount handlers to be aware of VMs that have been loaded individually so they don't disappear from **store.vms** while a user is viewing/editing it.
- Removing the redirect to card list and have the pages display a "VM 00000-00-00-000 could not be found" type of error

Those changes should provide a clean experience for a user starting the app on a detail or edit page.  Fetch the VM, keep it in the store and if it can't be found say so.
