### ISSUE TITLE
New VM: too small font / overall size

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-web-ui#582]
The 'Add new VM' button opens a dialog which is, at 100% zoom, using small fonts, for no good reason.
![screenshot from 2018-04-30 11-46-28](https://user-images.githubusercontent.com/4655593/39420269-671ae104-4c6c-11e8-9584-29ce459ae921.png)

**Comment by gregsheremeta** [comment]
obsoleted by redesign, closing
