### ISSUE TITLE
field-level help requires clicking instead of hovering

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-web-ui#583]
The bubble help itself should display the help text itself, not a general 'click for help'.

**Comment by gregsheremeta** [comment]
fwiw, we do the same in webadmin -- 'Click for help' -- and when clicked, a new tab with the RHV documentation opens to the correct place.

**Comment by mykaul** [comment]
@gregsheremeta - there's a difference between full documentation and a one-liner help - which I suggest will be visible when hovering, instead of asking to click.

**Comment by gregsheremeta** [comment]
@mykaul got it. Indeed I was thinking of the docs.

In webadmin, we do show the inline help on hover. 

However, PatternFly recommends showing it on click. I'm not sure why, but perhaps to be mobile friendly.

We could do both on click and on hover.

**Comment by gregsheremeta** [comment]
cc @lizsurette something to consider for redesign

**Comment by sgratch** [comment]
This is an old issue and it's not relevant anymore since there is no field-level help supported.
Only tooltips which all of them supports hovering now.
Therefore, closing this issue.
