### ISSUE TITLE
Error message for missing VM name shows REST API code

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-web-ui#584]
Clicking on Create VM without a VM name, you get the error:
VM_DIALOG_ADD_NEW_VM failed VM [name] required for add

Should be something like:
"Failed to add new VM: VM [name] required for add
(VM_DIALOG_ADD_NEW_VM )"

The techie stuff (if any), should be at the bottom. Also, it's missing some event ID (so if someone doesn't know English, they can refer to an ID of an error in question.

**Comment by mykaul** [comment]
The failure message also cannot be dismissed?
![screenshot from 2018-04-30 11-51-51](https://user-images.githubusercontent.com/4655593/39420370-eabb0944-4c6c-11e8-8c57-ace4584d8021.png)

**Comment by gregsheremeta** [comment]
cc @serenamarie125

**Comment by gregsheremeta** [comment]
cc @lizsurette for new vm flow

**Comment by sgratch** [comment]
@sjd78 this is not relevant anymore due to #987, right?

**Comment by sjd78** [comment]
> @sjd78 this is not relevant anymore due to #987, right?

I believe so, with one caveat that any REST errors still have the text error message from the service passed directly through to the user.  It is kinda still ugly in that respect, but there are (or will soon be) a handful of standard checks done on the frontend.  Really the only way to avoid the issue would be to have the REST api return error codes along with the error text and have the UI translate the error code.  That's a much longer term goal.

**Comment by sgratch** [comment]
We surely need to handle REST error msgs. Regarding this specific issue, since you are verifying that VM name field is not empty in frontend then I'm closing this issue.
