### ISSUE TITLE
use modal dialog pattern instead of popover

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#587]
Destructive operations such as shutdown and stop VM should present the user with modal confirmation dialogs. The pattern is under active design by the patternfly team, but we can see what it looks like already: https://github.com/patternfly/patternfly-design/issues/632

So instead of this:
![37150654-c8950d56-22d2-11e8-974e-4079247bf383](https://user-images.githubusercontent.com/2248293/39502346-bb0cfa64-4d8d-11e8-8de7-edf6554f48f8.png)

We need this:
![selection_547](https://user-images.githubusercontent.com/2248293/39502367-daff943a-4d8d-11e8-81bc-772eec2f54f5.png)

**Comment by mareklibra** [comment]
Oh, right. So let's reuse it.

**Comment by gregsheremeta** [comment]
@lizsurette @jennyhaines

**Comment by sjd78** [comment]
@gregsheremeta  - @bond95 did this work in #654, and it was in release 1.4.2

**Comment by bond95** [comment]
Already implemented in redesign.
