### ISSUE TITLE
convert 'force' actions to secondary dropdown pattern

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#588]
~~It would be good to have some checkbox inside of the shutdown window with label like "force" and if checked, it would do poweroff.~~

Force shutdown should be a secondary dropdown action, like github itself / webadmin / cockpit / etc

![selection_550](https://user-images.githubusercontent.com/2248293/39520987-9f11b44c-4dda-11e8-8c90-95a77855c13f.png)

![selection_552](https://user-images.githubusercontent.com/2248293/39520989-a1dd0816-4dda-11e8-8c56-d3ccda5f3309.png)

or

![39382705-6d56fd80-4a34-11e8-9531-5f0a2af60208](https://user-images.githubusercontent.com/2248293/39520999-adf9be0a-4dda-11e8-8fd3-e23d6177de41.png)

**Comment by bond95** [comment]
@gregsheremeta Is it still relevant? According to redesign document toolbar must look like that:
![image](https://user-images.githubusercontent.com/3332176/53428784-b21f3c00-39eb-11e9-9dc4-79a34f8634d4.png)

**Comment by gregsheremeta** [comment]
> @gregsheremeta Is it still relevant? According to redesign document toolbar must look like that:

Console is probably good the way it is. Reboot is still relevant.

**Comment by sgratch** [comment]
Closing since it's not relevant anymore
