### ISSUE TITLE
Edit VM 'Close' without saving fails

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#592]
To reproduce:
- Edit a VM
- Change i.e. Name
- click Close

Behavior:
- nothing hapens, console log:
```
TypeError: Cannot read property 'contains' of undefined
    at contains.js:17
    at t.F.focus (Modal.js:557)
    at t.F.onShow (Modal.js:486)
    at t.value (Modal.js:230)
    at commitLifeCycles (react-dom.production.min.js:149)
```

Expected:
The user is navigated to previous page

Observed on 1.3.9 in Chrome

**Comment by sjd78** [comment]
In summary, `VmDialog` uses `Prompt` from **react-router** to intercept link navigation off of the VM create/edit page.  Changes to fields on the page flag `Prompt` to trigger.  The current code to handle displaying a modal confirmation box in `App.js` is broken.  This code will also handle any other `Link`/`Prompt` pairs in the app.

I'm addressing the code in `App.js` now.

**Comment by sjd78** [comment]
Note: The only use of `Prompt` in the app is in **src/components/VmDialog/index.js**.
