### ISSUE TITLE
VM Portal does not auto refresh

### ISSUE THREAD

**Issue by jmk32889** [oVirt/ovirt-web-ui#593]
It would be nice if the VM Portal would auto-refresh

This would be particularly useful in the case of VM pools. The average end user has trouble already understanding what it is happening when they press the start VM button on a VM pool. Without auto refresh it looks to the user like nothing is happening. If auto refresh is enabled they will at least see the VM from the pool show up.

Ideally, pressing the start VM button on a VM pool would take the VM from the pool and automatically start the console so that the end user wouldn't have to press multiple buttons they don't actually understand the meaning of.

**Comment by mareklibra** [comment]
Thanks for reporting the issue.

There is already auto-refresh, something can be broken in the flow. Maybe related to InfiniteScroller, @bond95 ?

Anyway, the auto-refresh will be replaced by https://github.com/oVirt/ovirt-web-ui/pull/390 , the VM Portal will react without expensive dataset reload. Merge of #390 was blocked by oVirt 4.2 release.
