### ISSUE TITLE
[Epic] VM Detail / Edit page redesign

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#596]
This is an Epic to cover the redesign of Edit VM / View VM Details

VM Portal is focused on standard, non-admin users. A simple easy-to-understand UI is one of the main project goals.

new designs and discussion can be found at https://drive.google.com/drive/folders/1JHhQfi32uZd7V8XpoIcdNIUIZd-tmV9I?usp=sharing

previous designs:

![01](https://user-images.githubusercontent.com/17194943/39816871-d4f10cb2-539c-11e8-8166-f0e5f7975334.png)

---

![02](https://user-images.githubusercontent.com/17194943/39816872-d513f11e-539c-11e8-89a3-9591acae9209.png)

---

![03](https://user-images.githubusercontent.com/17194943/39816874-d534dd98-539c-11e8-90e3-f891d04693fe.png)

**Comment by mareklibra** [comment]
The audience are standard, non-admin, users willing to do simple tasks like start/stop VM, create a new one or basically edit existing.

All VM configuration options are kept intentionally on bare minimum, to both not to overwhelm the user same as and not to mimic the Administration Portal.
In other words, the number of details will grow but definitely not towards complexity of the Administration Portal.

From the beginning, we strived for "light", self-explanatory UI. The newbie user should be not afraid of it. The application is VM-centric, since VMs are the only thing the user is interested in.

Anyway, the number of rendered VM details grows and the views become inconsistently looking and should be reorganized.
Various fields, like the boot sequence or listing of disks can list variable number of items.
There's mixing of ways to edit the data (separate view vs. "inline-edit pencil").

We would like to still differentiate from the Administration Portal, a **non-technical** user should immediately "enjoy" use of the application and be sure how can (s)he operate his/her VMs.

**Comment by gregsheremeta** [comment]
Marek, @serenamarie125 is doing a quick UXD review now for the whole project. I'll share her notes offline.

**Comment by gregsheremeta** [comment]
@serenamarie125 do you mind sharing your doc publicly?

**Comment by mykaul** [comment]
@gregsheremeta , also, I think it should be in https://github.com/oVirt/ovirt-design

**Comment by serenamarie125** [comment]
Re: the details, we are trying to solve a design issue on the OpenShift side first, and then will rework that design into these.  Hoping to have that completed this week.

**Comment by gregsheremeta** [comment]
Unfortunately these RH docs can't be made public :(
![selection_014](https://user-images.githubusercontent.com/2248293/41597298-12b73ea4-739b-11e8-8acc-15bd4a056a92.png)

**Comment by mareklibra** [comment]
oops, thanks for noticing that.
Let's keep it as it is, no matter the document refers upstream only.

**Comment by sjd78** [comment]
@gregsheremeta - Looks like this replaced by #652 and the VM Details Dashboard.
