### ISSUE TITLE
session timeout should follow the patternfly session timeout pattern

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#598]
When session times out, we show an alert:
![session](https://user-images.githubusercontent.com/2248293/39924126-a03bf4ec-54f4-11e8-958a-0e09597008f8.png)

We should instead show a modal popup as the pattern shows:
http://www.patternfly.org/pattern-library/communication/session-timeout/
![pf-sew-01](https://user-images.githubusercontent.com/2248293/39924133-abbfb2f4-54f4-11e8-9ef7-d4a0d9bb19d5.png)

**Comment by jniederm** [comment]
> We should instead show a modal popup as the pattern shows:

Maybe rather *it addition to* the timeout alert right? I'd still prefer to be notified when I missed countdown modal popup.

**Comment by gregsheremeta** [comment]
Ah, sorry for the confusion re: before and after.

1. We should definitely show a message before -- this would be a heavier RFE iiuc.
2. We should show the "you've already timed out" message like we do now, but as a modal.

**Comment by bond95** [comment]
Also would be nice to add some countdown to tab title, because, for example, I always miss this dialog and must re-login.

**Comment by gregsheremeta** [comment]
cc @lizsurette

**Comment by lizsurette** [comment]
@gregsheremeta Using the PatternFly pattern makes sense to me. cc-ing Laura incase any further design recommendations are needed here.

@lwrigh FYI

**Comment by lwrigh** [comment]
@gregsheremeta @lizsurette The PatternFly session timeout modal makes sense to me to use in this scenario.

**Comment by sjd78** [comment]
Essentially the same issue as #955 and resolved by PR #968.
