### ISSUE TITLE
optimize fetching icons

### ISSUE THREAD

**Issue by atiratree** [oVirt/ovirt-web-ui#606]
fetch all icons by calling  `/ovirt-engine/api/icons` endpoint to initialize local storage (when empty)
- should prevent firing many requests when visiting ovirt-web-ui for the first time

**Comment by mareklibra** [comment]
@suomiy , this is exactly what I wanted to prevent.

Please consider following cases:
- the count of icons is large, so the response is large and JavaScript lacks support for large json processing
- the user "has" effectively just a few VMs, but there are tons of custom icons for other users

In addition, size of local storage is limited.

**Comment by suomiy** [comment]
You are right, we would download superfluous amount of icons this way. Anyway, it could be done better. I created RFE for that https://bugzilla.redhat.com/show_bug.cgi?id=1579287.

**Comment by sgratch** [comment]
This was already handled and closed according to  https://bugzilla.redhat.com/show_bug.cgi?id=1579287#c3.
So closing as NOTABUG.
