### ISSUE TITLE
No confirmation after `Esc`

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#613]
To reproduce:
- on the VM detail page, click Edit
- make some change (i.e. update description)
- press the `ESC` key

What happens:
The view is navigated back without any confirmation. Changes are dismissed.

Expected:
Same behavior as for clicking on the `Close` button - modal confirmation dialog appears.

**Comment by sjd78** [comment]
See #610

**Comment by bond95** [comment]
Duplicate.
