### ISSUE TITLE
Handle 404 conditions gracefully

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#631]
There are 2 potential 404 conditions that are not currently handled:
 - If the URL has an invalid path (e.g. `<host>/ovirt-engine/web-ui/fourtytwo`)
 - If the URL path is valid but the item UUID is invalid (e.g. `<host>/ovirt-engine/web-ui/vm/42`)

An invalid path will render either completely blank or a hard browser 404.  Probably should render a message with the app header, or redirect back to the root URL (VM card list).

An invalid UUID currently renders the header, the ID in the bread crumbs and a blank content area.  Probably should render the app header and a specific message about the record/item/vm/pool not being found.

**Comment by mareklibra** [comment]
IMO, it's better to handle 404 on our own with a polite message and possibility to navigate to the main page.

In case of the incorrect UUID (incl. lack of permissions), a context-aware message should be rendered as well.

**Comment by lizsurette** [comment]
@sjd78 @mareklibra How about something like this?

<img width="1166" alt="404" src="https://user-images.githubusercontent.com/208455/42009338-e280127e-7a57-11e8-9d71-a5d3e1c356e5.png">
