### ISSUE TITLE
[RFE] Add ability to use NoVNC console in VM Portal

### ISSUE THREAD

**Issue by tonyjames** [oVirt/ovirt-web-ui#640]
When using the VM Portal I do not see any option to select NoVNC as a console option when connecting to the console of a VM.  I use NoVNC extensively from the Admin Portal so it would be useful to have that same capability in the VM Portal.

**Comment by bond95** [comment]
Yes, we have plan to do this feature, we already working on the component that can bring NoVNC functionality to VmPortal, https://github.com/patternfly/patternfly-react/pull/288

**Comment by mareklibra** [comment]
Right, once https://github.com/patternfly/patternfly-react/pull/288 gets merged, it will be added here.

**Comment by gregsheremeta** [comment]
duplicate of #490
