### ISSUE TITLE
Redesign main page

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#641]
![image](https://user-images.githubusercontent.com/3332176/41592763-ffd20b34-73bd-11e8-84e6-3b2d16484a01.png)

**Comment by mareklibra** [comment]
Part of #596

**Comment by bond95** [comment]
Latest design version:
![image](https://user-images.githubusercontent.com/3332176/42272928-ef0584a4-7f87-11e8-99a9-4176bbce6b78.png)
