### ISSUE TITLE
cloud-init switch has no function

### ISSUE THREAD

**Issue by gematik-fue** [oVirt/ovirt-web-ui#642]
## description
Cloud-init doesn't work. Enabling this setting does not pass down the settings to virtual machine

## Expected results
Virtual machine should have an additional cdrom drive attached with config-2 labeled cd containing the given cloud-init user settings, so cloud-init service would pick up that data and perfom required steps.

## Actual results:
Vm is started without the emulated config-2 drive, so cloud-init can't find user specified settings. (check `blkid` command

## Steps to reproduce:
1. in Administration portal
 1.1. create a linux based (cloud-init enabled but not yet run) vm
 1.2. create a template based on this vm (seal template enabled)
 1.3. enable cloud-init (with empty hostname, prefill custom-script) on this template
2. in user portal
 2.1. create a new vm based on the given template
 2.2. checke cloud-init is enabled an a proper hostname (copied from vm-name) is set
 2.3. start vm by clicking "run"

## Affected Version
- oVirt 4.2.3.5-1.el7.centos
- VM Portal 1.3.9-1

## Remarks
This may be a engine problem too, as cloud-init config drive isn't created when started "run" instead of "run once" even if cloud-init/sysprep is enabled in vm settings

**Comment by bond95** [comment]
Thank you for report. This bug doesn't depends on templates, thus even if create new VM with empty template and start it with VmPortal it still gonna not work. Created bug on Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1593239

**Comment by leistnerova** [comment]
cloud init script (some write_files) ran successfully for new VM created in the VM portal

tested in ovirt-engine-4.3.0-0.0.master.20180802141038.gitd9dc74f.el7.noarch
ovirt-web-ui-1.3.6-1.el7.centos.noarch

**Comment by gregsheremeta** [comment]
Thanks @leistnerova!

I think ovirt-web-ui-1.3.6-1.el7.centos.noarch is the latest in the repo (due to a bug), but it's best to test with the latest version, which is 1.4.1. Until we fix the repo issue, you can grab the latest rpms from https://github.com/oVirt/ovirt-web-ui/releases

currently 1.4.1 = https://github.com/oVirt/ovirt-web-ui/releases/tag/1.4.1

Would you mind retesting with the latest? :)

**Comment by leistnerova** [comment]
No problem, file on new VM created with cloud-init also in ovirt-web-ui-1.4.1-1.fc28.noarch

**Comment by gregsheremeta** [comment]
awesome, thanks @leistnerova!
