### ISSUE TITLE
web-ui about windows7 display？

### ISSUE THREAD

**Issue by Michael754267513** [oVirt/ovirt-web-ui#644]
###  authorize  user  is access to windows7 (AD user)
WEB-UI--> login user with roles is  UserRole-->  WEB-UI  not found windows7 --> logout user and login admin--> check this windows7-->setting autoconnection on --> logout admin --> login user --> WEB-UI found this windows7 --> use the other browser -->login user --> WEB-UI not found windows7. --> ctrl+F5--> WEB-UI not found.

**Comment by michalskrivanek** [comment]
see #460, do you have at least 4.2.2 and newer?

**Comment by Michael754267513** [comment]
[root@ovirt-engine log]# cat yum.log  | grep engine
Apr 04 10:28:55 Installed: python-ovirt-engine-sdk4-4.2.4-2.el7.centos.x86_64
Apr 04 10:28:56 Installed: ovirt-engine-extensions-api-impl-4.2.1.7-1.el7.centos.noarch
Apr 04 10:28:56 Installed: ovirt-engine-extension-aaa-jdbc-1.1.6-1.el7.centos.noarch
Apr 04 10:28:56 Installed: ovirt-engine-sdk-python-3.6.9.1-1.el7.noarch
Apr 04 10:29:04 Installed: ovirt-engine-lib-4.2.1.7-1.el7.centos.noarch
Apr 04 10:29:29 Installed: ovirt-engine-wildfly-11.0.0-1.el7.centos.x86_64
Apr 04 10:29:29 Installed: ovirt-engine-wildfly-overlay-11.0.1-1.el7.centos.noarch
Apr 04 10:29:32 Installed: ovirt-engine-cli-3.6.9.2-1.el7.centos.noarch
Apr 04 10:29:38 Installed: ovirt-ansible-engine-setup-1.1.0-1.el7.centos.noarch
Apr 04 10:29:39 Installed: ovirt-engine-metrics-1.1.2.2-1.el7.centos.noarch
Apr 04 10:30:38 Installed: ovirt-engine-setup-base-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:49 Installed: ovirt-engine-setup-plugin-ovirt-engine-common-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:49 Installed: ovirt-engine-dwh-4.2.1.2-1.el7.centos.noarch
Apr 04 10:30:50 Installed: ovirt-engine-dwh-setup-4.2.1.2-1.el7.centos.noarch
Apr 04 10:30:50 Installed: ovirt-engine-setup-plugin-websocket-proxy-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:50 Installed: ovirt-engine-websocket-proxy-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:50 Installed: ovirt-engine-tools-backup-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:51 Installed: ovirt-engine-vmconsole-proxy-helper-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:51 Installed: ovirt-engine-setup-plugin-vmconsole-proxy-helper-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:51 Installed: ovirt-engine-setup-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:51 Installed: ovirt-engine-setup-plugin-ovirt-engine-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:51 Installed: ovirt-engine-tools-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:52 Installed: ovirt-engine-dbscripts-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:53 Installed: ovirt-engine-backend-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:55 Installed: ovirt-engine-dashboard-1.2.1-1.el7.centos.noarch
Apr 04 10:31:09 Installed: ovirt-engine-webadmin-portal-4.2.1.7-1.el7.centos.noarch
Apr 04 10:31:10 Installed: ovirt-engine-restapi-4.2.1.7-1.el7.centos.noarch
Apr 04 10:31:10 Installed: ovirt-engine-api-explorer-0.0.2-1.el7.centos.noarch
Apr 04 10:31:10 Installed: ovirt-engine-4.2.1.7-1.el7.centos.noarch
Jun 19 13:32:39 Installed: ovirt-engine-extension-aaa-ldap-1.3.7-1.el7.centos.noarch
Jun 19 13:32:40 Installed: ovirt-engine-extension-aaa-ldap-setup-1.3.7-1.el7.centos.noarch
[root@ovirt-engine log]# cat yum.log  | grep web
Apr 04 10:28:48 Installed: python-webob-1.2.3-7.el7.noarch
Apr 04 10:29:30 Installed: python-websockify-0.8.0-1.el7.noarch
Apr 04 10:29:46 Installed: ovirt-web-ui-1.3.5-1.el7.centos.noarch
Apr 04 10:30:42 Installed: objectweb-asm-3.3.1-9.el7.noarch
Apr 04 10:30:50 Installed: ovirt-engine-setup-plugin-websocket-proxy-4.2.1.7-1.el7.centos.noarch
Apr 04 10:30:50 Installed: ovirt-engine-websocket-proxy-4.2.1.7-1.el7.centos.noarch
Apr 04 10:31:09 Installed: ovirt-engine-webadmin-portal-4.2.1.7-1.el7.centos.noarch

**Comment by Michael754267513** [comment]
Apr 04 10:31:10 Installed: ovirt-engine-4.2.1.7-1.el7.centos.noarch
Apr 04 10:29:46 Installed: ovirt-web-ui-1.3.5-1.el7.centos.noarch

**Comment by jelkosz** [comment]
so it is 4.2.1, it has been fixed in 4.2.2.
Can you please try to update?

**Comment by Michael754267513** [comment]
TKS
