### ISSUE TITLE
Redesign notifications

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#647]
![image](https://user-images.githubusercontent.com/3332176/41908599-cd8a3a70-7944-11e8-9a9c-0486538589aa.png)

**Comment by mareklibra** [comment]
Let's not group the events for now, just list them chronologically

**Comment by mareklibra** [comment]
Part of https://github.com/oVirt/ovirt-web-ui/issues/596

**Comment by gregsheremeta** [comment]
I'm building a notification drawer for admin portal that has 'dismiss all' and 'snooze for ...' buttons.
https://gerrit.ovirt.org/#/c/92443/

**Comment by lizsurette** [comment]
@bond95 
Minor nitpick from the demo today:
The Clear All button and footer area should not be shown when there are no notifications.
