### ISSUE TITLE
add support for SSO when connecting to VM

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#65]
Before connecting to the VM, if the guest agent is present, the VmLogon will need to be called on the VM.

**Comment by jelkosz** [comment]
If the guest agent is not present, the user needs to be warned that the GA is not there and ask him if he really wants to connect.

**Comment by jelkosz** [comment]
The support in API is there, only the POST /ovirt-engine/api/vms/<vm id>/logon needs to be called with <action/> as the body.

- maybe it would be good to have this optionally enabled/disabled in the console options dialog because you don't always need this.

**Comment by michalskrivanek** [comment]
not sure how many people use this, but it's a gap from the old UP

**Comment by jmk32889** [comment]
What's the estimated time for this to be implemented now that it has been moved out of the v1.4.0 milestone?

**Comment by gregsheremeta** [comment]
unfortunately no ETA since it's not a current priority. We're currently focused on the UI redesign.

**Comment by gregsheremeta** [comment]
@michalskrivanek ^

**Comment by michalskrivanek** [comment]
@gregsheremeta it shouldn't be too large of a task though, API supposedly works ok, and it probably could be optional just on a per-user basis. Actually, adding it to the Options and explaining what that lonely "SSH Key" actually means would be wonderful:)

**Comment by michalskrivanek** [comment]
....plus functional gaps from the GWT User Portal should be high prio anyway

**Comment by gregsheremeta** [comment]
@michalskrivanek ack, I'll schedule it then.

@jmk32889 how soon do you need it? do you have a deadline or anything like that?

**Comment by gregsheremeta** [comment]
> that lonely "SSH Key" actually means

we did address that dialog in redesign

**Comment by jmk32889** [comment]
@gregsheremeta  not a firm deadline, but if it were available by October that would be great. I appreciate you considering my input. Thank you

**Comment by gregsheremeta** [comment]
> I appreciate you considering my input

of course! we definitely want to increase our user base, so thank you for letting me know that this was a show stopper.
