### ISSUE TITLE
[Epic] Redesign VM Edit page

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#652]
Redesign the VM detail / dashboard page
![ovirt user portal - patternfly gaps 2](https://user-images.githubusercontent.com/3985964/42242353-92141154-7edb-11e8-9eb0-a65cd37e1c51.png)

See https://github.com/oVirt/ovirt-design/pull/8 ([design document](https://github.com/lizsurette/ovirt-design/blob/8807b0140032e7e848b3cdb0cdb952e917088b88/user-portal/virtual-machine-details.md#virtual-machine-details)) and https://github.com/oVirt/ovirt-design/pull/12 ([design document](https://github.com/lizsurette/ovirt-design/blob/336ca947842408b866bdf1538a8567bc7b701ad9/user-portal/edit-virtual-machine.md)) for the UXD consideration.

Breadcrumbs and Toolbars can track under different issues.

**Comment by sjd78** [comment]
Part of #596

**Comment by sjd78** [comment]
(previous layout)
![ovirt user portal - patternfly gaps](https://user-images.githubusercontent.com/3985964/41995668-93c9893a-7a20-11e8-91cf-36ac48d15a01.png)

**Comment by gregsheremeta** [comment]
I'm confused. Is this issue referring to just the Details box, or the entire page?

**Comment by gregsheremeta** [comment]
> I'm confused. Is this issue referring to just the Details box, or the entire page?

assuming just the details box for now, but lmk

**Comment by sjd78** [comment]
Originally I assumed a base state where the page would be usable as a replacement for the current read-only `VmDetail` component.  At that point, there were not many designs in progress for edit states.

**Comment by sjd78** [comment]
See:
  - (Issue #750, PR #700) &rarr; Utilization Card
  - (Issue #753, PR #691) &rarr; Snapshots Card

**Comment by sjd78** [comment]
See Issue #776, PR #701 &rarr; Details Card

**Comment by sjd78** [comment]
See:
 - Nics Card &rarr; Issue #757 &rarr; PR #756 (view), #796 (edit)
 - Disks Card &rarr; Issue #775 &rarr; PR #780 (view), #838 (edit)

**Comment by sjd78** [comment]
As of Nov-18, all 6 of the cards have been developed, reviewed and tested as per the initial designs.  Followup design changes are being tracked in their own issues.
