### ISSUE TITLE
Manual VM Pool visibility when user limit reached

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#655]
If someone reaches the maximum number of VMs he/she can take from the pool, he/she should not see the pools, only the VMs.
That's the case for automatic VM Pool Type, in a case of manual type, it doesn't work as expected. 

Steps to Reproduce:
 
With a manual type of pool, a pool is created (named for example Pool-Win7-manual-??) composed of the VMs and a maximum attribution of 2 VM per user. When VMs are running, there are no issues. However, once the VM Pool-Win7-manual-01 is stopped, there is the following situation :
- Pool-Win7-manual-01 stopped but still visible, because it's still attributed to the user (principle of a manual pool) 
- Pool-Win7-manual-02 is running, therefore visible 
- Pool-Win7-manual-?? which reappears (and which remains visible if we refresh the page), while we already reached the maximum number of VM that the user can take 

https://bugzilla.redhat.com/show_bug.cgi?id=1596178

**Comment by gregsheremeta** [comment]
Actually, this behavior may change in redesign -- we may want to always show a pool card. Currently under discussion. Setting needinfo until we make a decision.

cc @lwrigh 

See #195 and [VM Portal UI Redesign - Pools - Google Docs](https://docs.google.com/document/d/1ZQm56a539CPUYHa6fCkvtqD_Sx0iLIKWCk7VuCVLqU0/edit)

**Comment by sgratch** [comment]
@bond95 is this bug still relevant after pools redesign?

**Comment by bond95** [comment]
@sgratch yes, fixing of this bug lay in pool allocation mechanism and fixing of that mechanism is not part of redesign.
