### ISSUE TITLE
snapshots: after restoring a snapshot the list of snapshots randomly disappear/reappear

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-web-ui#665]
have a list of snapshots. Restore any of them.
Result:
after refresh, the list of snapshots disappear. After other refresh they all re-appear. And than they alternate randomly

**Comment by sjd78** [comment]
Could be resolved by PR #679 plus commit c1b3e6b88fffa5a57f30c56c6e89661dd193cbe5 in PR #658.  

The snapshots array in the vms redux store would get overridden to `[]` on a shallow refresh (the background refresh does a shallow fetch) if the VM had already been loaded either in the first page of VMs or in the list card view.

**Comment by sjd78** [comment]
> Does it need to 'hijack' another PR (#679) or can it be its own?

#679 is untouched, and #690 builds on it to include all the relevant parts of c1b3e6b.

@bond95, #690 will probably solve this issue.

**Comment by gregsheremeta** [comment]
@sjd78 does #690 (closed) indeed fix this (i.e. can we close)?

**Comment by sjd78** [comment]
@gregsheremeta - I have not been able to reproduce the issue as Tomas described.  The issue can be closed.

**Comment by gregsheremeta** [comment]
thanks!
