### ISSUE TITLE
add user permissions tab

### ISSUE THREAD

**Issue by cnagarka** [oVirt/ovirt-web-ui#672]
Currently, VM Portal is not showing User Permissions. So If a user wants to delegate permissions to another user they have to log in with admin portal to add another user with an expected role.

This feature was available in RHV User Portal till RHV 4.1 and I understand VM Portal is purely designed for end consumers. Some customers who want to use VM Portal as User Portal might feel this is a regression.

--
cnagarkar

**Comment by michalskrivanek** [comment]
It should be relatively easy to display permissions for each VM. But delegation or any manipulation with them is far more difficult and doesn't sound like a priority.
Feel free to pick it up and post a patch, but I expect it's going to be challenging.

**Comment by sgratch** [comment]
We are not going to fix it since too complicated to implement, then closing this issue.
