### ISSUE TITLE
When VM fails to run from pool, it generates large message

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#675]
Trying to start VM from a pool where are many not started VMs and host doesn't satisfy VM conditions. Error message contains:

Cannot attach VM to VM-Pool. There is no host that satisfies current scheduling constraints. See below for details:, The host vhost07 did not satisfy internal filter Memory because its available memory is too low (534 MB) to run the VM.

repeated for every try to start another VM from the pool.

**Comment by michalskrivanek** [comment]
backend returns individual errors for each VM it tries to acquire. We should filter that out as it's not really useful, and replace that with a short "No VM can be acquired" message. Or just lump the same class of errors together so it's not that many to display.

**Comment by sgratch** [comment]
Opened for a long time so closing this.
