### ISSUE TITLE
improvements in displaying snapshots

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#676]
- missing information about creation time, state of the snapshot (creating, deleting, restoring)
- When snapshot is deleting, no buttons should be displayed by it.
- When restoring, no other Restore buttons.
- When creating new one, no New snapshot button.
- Align buttons

**Comment by gregsheremeta** [comment]
@leistnerova Lucie, we are in the process of redesigning this.
https://github.com/lizsurette/ovirt-design/blob/16e04ada39b971beec59c5a1e3dedf2354fcbe36/user-portal/snapshots.md

@lizsurette ^^

**Comment by sjd78** [comment]
Fixed by #783

**Comment by sjd78** [comment]
Shows things disabled when creating a new snapshot, snapshot name wrapping, and button alignment
![screenshot-localhost-3000-2018 09 25-09-58-54](https://user-images.githubusercontent.com/3985964/46019240-a086e080-c0a9-11e8-83a6-fb7e7bb4914c.png)

Example of tooltips on buttons:
![screenshot-localhost-3000-2018 09 25-10-00-01](https://user-images.githubusercontent.com/3985964/46019380-eba0f380-c0a9-11e8-97fa-6ec88b3c3d22.png)
