### ISSUE TITLE
deleted snapshot is not removed from the list

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#677]
See video.

tested in ovirt-web-ui-1.4.0-3.fc28.noarch
FF 61.0, Google Chrome 67.0

[snapshot_delete.zip](https://github.com/oVirt/ovirt-web-ui/files/2227443/snapshot_delete.zip)

**Comment by bond95** [comment]
Could you, please, send browser logs?

**Comment by leistnerova** [comment]
console log
[soscleaner-1860680069843410.tar.gz](https://github.com/oVirt/ovirt-web-ui/files/2227548/soscleaner-1860680069843410.tar.gz)

**Comment by bond95** [comment]
It seems problem is in checking snapshot. Web-ui send `get snapshot` request on engine a few times in different time interval. And if engine still return snapshot, web-ui just do nothing. Thus if engine will deleting snapshot longer than one minute, web-ui don't remove it from the list.

**Comment by gregsheremeta** [comment]
@bond95 let's make sure this works on the new edit page. I think we can get the snapshots card done by 1.4.2 / August 10.

**Comment by gregsheremeta** [comment]
@bond95 is this one in the snapshot PR, #691 ?

**Comment by bond95** [comment]
@leistnerova could you, please, test it on latest master?

**Comment by gregsheremeta** [comment]
@leistnerova can we test on both 1.4.5 and 1.5.0?

**Comment by leistnerova** [comment]
In ovirt-web-ui-1.5.2-0 snapshot is removed properly.
In ovirt-web-ui-1.4.5-1 problem still persist, but only sometimes.

Steps to reproduce:
1. have VM with more disks
2. create two new snapshots
3. delete first one
4. quickly right after the snapshot disappears, delete the second one

**Comment by gregsheremeta** [comment]
@leistnerova thanks. Since we're not doing any 1.4 updates, closing.
