### ISSUE TITLE
all VMs in VM Pool are listed regardless of actual VM ownership

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#680]
If VM is taken from a pool by another user it is still listed for all other users with a UserRole permission on the pool .
Normally permissions are inherited but VM Pool is a special case, user can have a permission for the pool but that user doesn't own a VM from that pool allocated by another user.

This is a backend bug

**Comment by michalskrivanek** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1609147

**Comment by gregsheremeta** [comment]
@michalskrivanek shouldn't need any updates in web-ui? (So this is a tracking bug)

**Comment by michalskrivanek** [comment]
correct. that was the intention of "bugzilla" label I guess (not sure, i haven't created it:)
The resolution of this issue solely depends on fixing that bug in ovirt-engine.

**Comment by michalskrivanek** [comment]
verified the alternative fix in that bug. Seems to work fine now, except for issue #719 which should be fixed in ovirt-web-ui

**Comment by leistnerova** [comment]
LGTM
tested in ovirt-engine-4.2.6.4-0.1.el7ev.noarch and in ovirt-engine-4.3.0-0.0.master.20180827115940.git6cf4cb7.el7.noarch
with ovirt-web-ui-1.4.2-1.el7.noarch

4.3 still except of #719 (4.2.6 works all fine)

**Comment by gregsheremeta** [comment]
thanks @leistnerova!
