### ISSUE TITLE
Setting Connect automatically to console removes this setting for other user

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#685]
When I log as other user and set Connect automatically by Console, it removes this setting for previous user I logged in and set it.

See video
[connect_automatically.zip](https://github.com/oVirt/ovirt-web-ui/files/2244449/connect_automatically.zip)

Tested in ovirt-web-ui-1.4.0-3.fc28.noarch, with ovirt-engine-4.2.5.1-0.1.el7ev.noarch

**Comment by bond95** [comment]
Old detail page no longer exists. Bug will be fixed in https://github.com/oVirt/ovirt-web-ui/pull/1088

**Comment by sgratch** [comment]
This isn't reproduced anymore with new connect automatically implementation for user settings: https://github.com/oVirt/ovirt-web-ui/issues/1459 and therefore I'm closing this issue as Done
