### ISSUE TITLE
RDP button sends 'console.rdp' to the user at render time instead of onClick event time

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#686]
When a Windows VM is opened in the "legacy" VM Detail screen, the `WindowsRdpButton` is rendered to allow the user to connect to the RDP session.  Unfortunately, the `onClick` event handler is being fired immediately at render time and not when the user clicks the button.   This causes web-ui to send the user a **console.rdp** connection file.

Also, since the background refresh triggers a re-render and the refresh happens every minute, the user is sent a new **console.rdp** file every minute.

Caused by PR #651

**Comment by gregsheremeta** [comment]
is this a recent regression?

what's the symptom?

**Comment by gregsheremeta** [comment]
@michalskrivanek do you want to release 1.4.1 asap (without this) or wait for it?

**Comment by sjd78** [comment]
Closing since the issue is resolved with the merge of #687.
