### ISSUE TITLE
dev server doesn't work without redux dev tools installed

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#688]
dev server doesn't work without redux dev tools installed

![selection_108](https://user-images.githubusercontent.com/2248293/43493840-08780912-94fe-11e8-8f41-a9e275f8ce8b.png)

**Comment by sjd78** [comment]
Why would you want to run the dev server without the redux dev tool?  ;-)

**Comment by gregsheremeta** [comment]
yeah fair point. I wouldn't personally, but other developers might not have it installed. UXD might want to work on branding, and they wouldn't have it installed.

Something better then a white screen crash would be nice.
