### ISSUE TITLE
toast notifications when VM is created, starting, or shutting down

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#695]
As a VM Portal user, I want to see toast notifications when a VM is starting or shutting down, like in the Admin Portal, so that I can be certain the action is occurring [feedback].
![image](https://user-images.githubusercontent.com/3332176/43579795-8c63682e-9653-11e8-9cd2-d3adf532a36b.png)

**Comment by michalskrivanek** [comment]
consider VM creation action as well

**Comment by sgratch** [comment]
@sjd78 @yodem what about VM creation? Should we open a new issue for that or can we handle that as part of this issue or issue #923.

@yodem Please open a new issue to handle the notificaitons for the async finished operations. See  
https://github.com/oVirt/ovirt-web-ui/pull/1110#issuecomment-527105992

**Comment by sjd78** [comment]
> @sjd78 @yodem what about VM creation? Should we open a new issue for that or can we handle that as part of this issue or issue #923.

VM creation doesn't need a toast notification since the review step has a progress indicator built in.

**Comment by sgratch** [comment]
> VM creation doesn't need a toast notification since the review step has a progress indicator built in.

Don't we need a notification of something like: "VM xxx was created by user@internal-authz at time..." regardless to the progress indicator?
