### ISSUE TITLE
A VM's CD can be changed, but the currently loaded CD is never displayed

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#698]
On entering the VM details or edit screen, the VM's full data is fetched.  To reduce the number of calls needed to get a complete picture of the VM, the _follow_ parameter is used.  Unfortunately, in the case of __cdroms__, an extra matrix parameter is required on its fetch (current=true) to get the correct information and it is not currently possible to specify the matrix parameter within the __folllow__ parameter.

The "Change CD" function on webadmin and the CD select box on web-ui both change the current configuration and not the saved configuration.

As a result, on web-ui, a VM's CD can be changed, but it currently never displays correctly.

Either a second fetch with the extra matrix param needs to be done, or the REST api needs an update to allow sending matrix params along with the __follow__ param.

![screenshot from 2018-08-03 08-42-19](https://user-images.githubusercontent.com/3985964/43643419-3aaca7a6-96f9-11e8-9cde-39ad5601c2f7.png)

**Comment by gregsheremeta** [comment]
> As a result, on web-ui, a VM's CD can be changed, but it currently never displays correctly.

Seems like we need a place to hold intermediate states

**Comment by sjd78** [comment]
> Either a second fetch with the extra matrix param needs to be done, or the REST api needs an update to allow sending matrix params along with the follow param.

#742 adds a second fetch for the cdrom info when the VM is "up"

**Comment by sjd78** [comment]
@gregsheremeta ...
> Seems like we need a place to hold intermediate states

The cd-rom API has it and makes the distinction based on the `current` parameter.  Just need to adjust the code so when the VM is running, the `current` cdrom info is grabbed (and pushed to), and when the VM is not running, the `not current` cdrom info is grabbed (and pushed to).

With the latest updates to #742, that is how it'll work.
