### ISSUE TITLE
Replace remaining ocurrences of "userportal" with "ovirt-web-ui"

### ISSUE THREAD

**Issue by matobet** [oVirt/ovirt-web-ui#70]
Some string constants and configuration values still contain references to "userportal". In order to complete the renaming these should be cleaned up.

**Comment by mareklibra** [comment]
https://github.com/oVirt/ovirt-web-ui/pull/78

**Comment by mareklibra** [comment]
src/index.js
src/config.js
userportal.config
config/webpack.config.prod.js
config/webpack.config.dev.js
Makefile.am
