### ISSUE TITLE
create a production docker container that uses nginx

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#703]
We want two containers -- one for production + releases, and one for dev + snapshots.

The dev one can be the current one -- it should install the nodejs stuff, build from source, trim down the container if possible, and start the webpack hmr dev server.

The prod one can grab only the compiled outputs and serve them in a static site, via nginx. I think in this case doing a git clone of master or a release tag and simply starting nginx will do the trick. This method will need to handle asking for an API URL and credentials too.

**Comment by bond95** [comment]
@gregsheremeta Does this issue still relevant? https://hub.docker.com/r/ovirtwebui/ovirt-web-ui/

**Comment by gregsheremeta** [comment]
no longer relevant, closing
