### ISSUE TITLE
ISO images from Data domain do not show up in VM Portal

### ISSUE THREAD

**Issue by tristam** [oVirt/ovirt-web-ui#704]
ISO Domain images do show up, data domain isos do not show up in the VM Portal.  Data domain Isos do show up in the Admin Portal.

**Comment by michalskrivanek** [comment]
there's no suitable API to get iso list anymore. it would need to iterate through all SDs which doesn't scale

**Comment by gregsheremeta** [comment]
> there's no suitable API to get iso list anymore

Seems like we need engine to cache the list of ISOs then. @michalskrivanek thoughts on that?

**Comment by sjd78** [comment]
FWIW, this REST query on 4.3 does seem to pull all ISO disk imagess from every non-ISO storage domain in a single fetch:
````
https://engine/ovirt-engine/api/disks?search=disk_type%3Dimage%20and%20disk_content_type%3Diso
````
Same thing as a query of `disk_type=image and disk_content_type=iso` on the Disks tab in webadmin.

#876 uses that fetch at the core of the change

**Comment by sjd78** [comment]
Opened [BZ1659121](https://bugzilla.redhat.com/show_bug.cgi?id=1659121) to deal with @leistnerova 's findings about how the REST query listed above works fine with "Filter: false" but when "Filter: true" the `disk_content_type` search terms seems to be ignored.

**Comment by sjd78** [comment]
Unblocked.  BZ1659121 is fixed in ovirt-engine master.
