### ISSUE TITLE
ux-redesign: VM Details > Overview Card  > icon upload

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#714]
As a VM Portal user, I want to be able to upload a new icon for my virtual machines.

![selection_125](https://user-images.githubusercontent.com/2248293/44000978-742f11bc-9df7-11e8-8948-afb47f9b887a.png)

**Comment by sjd78** [comment]
See the [VM Portal- Overview Card_Image Upload](https://docs.google.com/document/d/1GtCMUnTMik38SaXuhZGzhUm01GRJ9BSSMDgFF8C3rJE/edit?ts=5b859719#heading=h.1g9dthwstb11) design doc.

**Comment by sgratch** [comment]
Since this issue is opened for more than 2 years and no user complained about it then closing as WONTFIX.
Please re-open if you think it's still required.
