### ISSUE TITLE
wrap InfiniteScroll in a 'overflow: auto' div

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#716]
Per discussion at https://github.com/oVirt/ovirt-web-ui/pull/715#discussion_r209967208

It may make sense to wrap InfiniteScroll in a `overflow: auto` div so that it's self-contained and guaranteed to work.

A potential issue is two nested `overflow: auto` divs could cause duplicate scrollbars. (Is that accurate? @bond95 @sjd78 please comment. @bond95 it would be helpful if you can demonstrate the duplicate scroll issue -- otherwise I tend to lean towards self-contained component guaranteed to work.

**Comment by gregsheremeta** [comment]
needinfo @sjd78 and @bond95 to discuss and decide if we should move forward with this

**Comment by sjd78** [comment]
No longer relevant since #1242
