### ISSUE TITLE
Enable access to the legacy VM detail page for access to Console, Disks, Nics and Snapshot functions

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#718]
With incremental releases planned (after each agile sprint), not all of the previous functionality will be available immediately.  By enabling access to the legacy view, all the functionality will still be available.

Once the new VM Details page is functionally complete, the legacy VMDetail page (and supporting components) may be removed.

**Comment by gregsheremeta** [comment]
thanks for the quick fix on this
