### ISSUE TITLE
VM list (main page) is filtered for admin users

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#720]
Admin user on main page see only those VMs for which has permissions, because header `Filter` set to `true`. But it must be `false` for admin.

**Comment by sjd78** [comment]
https://github.com/oVirt/ovirt-web-ui/blob/4437ee5d4d659cd47da91a3daf162dd85d488157/src/saga/login.js#L198-L217

@bond95 - If the admin user is being filtered, it is because the options to do so has been setup.  On my dev engine, the option isn't set and `Filter: false` is always sent for my admin user.

**Comment by gregsheremeta** [comment]
> it is because the options to do so has been setup

where does that happen?

**Comment by sjd78** [comment]
> where does that happen?

Wherever this rest endpoint pulls it from:
http://ovirt.github.io/ovirt-engine-api-model/4.3/#services/system_option

**Comment by michalskrivanek** [comment]
> Admin user on main page see only those VMs for which has permissions, because header Filter set to true. But it must be false for admin.

?
yes, and? It doesn't have to be false for admin. It's configurable. I'm surprised you're asking...it's been intentionally done like that long time ago.
Default is true, btw

**Comment by gregsheremeta** [comment]
For posterity, on which screen is it configured? (screenshot please)

**Comment by michalskrivanek** [comment]
Oh, not in GUI. It’s a system-wide engine-config setting. A policy admin would set, enable filter=on for admins to not see other VMs to mimic the previous(universally hated) UP behavior
