### ISSUE TITLE
Loading text in the Options

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#730]
There is a "Loading…" text in the options card. (It made me feel like I have to wait for something to appear or happen until I realized it’s just a text.)

Tested in: ovirt-web-ui-1.4.2.0.20180814git2ec0a1e-1.fc28.noarch.rpm, Mozilla Firefox for Fedora 

![screenshot from 2018-08-16 13-12-49](https://user-images.githubusercontent.com/39263962/44266551-3b7ad800-a22b-11e8-954c-dbdcb02005bb.png)

**Comment by michalskrivanek** [comment]
And nothing happened? 
it's not supposed to be a text,  there should be the key loaded async. Or made empty, I guess, if none is set

**Comment by isaranova** [comment]
@michalskrivanek Nothing happened, it's just a text.

**Comment by gregsheremeta** [comment]
regression of #505
