### ISSUE TITLE
Console button changes to Suspend or Shutdown

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#733]
When I want to see a console of running VM for the first time (no console in use dialog), the button changes to suspend or shutdown button for a moment and then changes back to console button. Console runs without problems.

Tested in: ovirt-web-ui-1.4.2.0.20180814git2ec0a1e-1.fc28.noarch.rpm, Mozilla Firefox for Fedora

(Sorry for low quality pic)
![screenshot from 2018-08-20 13-11-06](https://user-images.githubusercontent.com/39263962/44337385-cdc4eb00-a47a-11e8-8d73-6918214f1275.png)

**Comment by gregsheremeta** [comment]
@sjd78 @bond95 thoughts on this one?

**Comment by bond95** [comment]
@gregsheremeta @sjd78 problem is in action filtering. Because disabled actions are filtered. And console action is disabled for a moment. 
```actionDisabled: isPool || !canConsole(status) || vm.getIn(['actionInProgress', 'getConsole']),```
As you can see console action is disabled when `actionInProgress`, this was done to prevent more clicking on button.

**Comment by bond95** [comment]
Actually, problem was in filtering and now it fixed. In any case, with console page patch, first button will be `Suspend`. So I think this issue is not relevant and can be closed.
WDYT? @gregsheremeta @sjd78

**Comment by gregsheremeta** [comment]
> Actually, problem was in filtering and now it fixed. In any case, with console page patch, first button will be `Suspend`. So I think this issue is not relevant and can be closed.
> WDYT? @gregsheremeta @sjd78

works for me, closing. thanks!
