### ISSUE TITLE
No upper shadow on selected card in first line of VMs in VM grid

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#734]
When hovering over the cards of VMs in the main VM grid, there is no upper shadow around the VM cards from the first line.

Tested in: ovirt-web-ui-1.4.2.0.20180814git2ec0a1e-1.fc28.noarch.rpm, Mozilla Firefox for Fedora

![screenshot from 2018-08-20 13-15-37](https://user-images.githubusercontent.com/39263962/44337743-f5688300-a47b-11e8-9f02-d9d75dd7b0ee.png)
![screenshot from 2018-08-20 13-15-40](https://user-images.githubusercontent.com/39263962/44337745-f5688300-a47b-11e8-8ab2-99dde528baf7.png)

**Comment by bond95** [comment]
@gregsheremeta @sjd78 checked on master, everything work fine, thus close this issue.
![image](https://user-images.githubusercontent.com/3332176/50000429-e01ee380-ff99-11e8-96ba-5450851ec7ba.png)
