### ISSUE TITLE
Clusters should be filtered by user permission on creating and editing VM pages

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#737]
Clusters must be filtered by user permission on creating and editing VM pages. Also if user has no permissions for creating VM on Cluster, then hide `Create Virtual Machine` button. For creating VM user must have `VmCreator` or `PowerUserRole` permissions for cluster.

Related issues: https://github.com/oVirt/ovirt-web-ui/issues/258 https://github.com/oVirt/ovirt-web-ui/issues/286 https://github.com/oVirt/ovirt-web-ui/issues/507

**Comment by gregsheremeta** [comment]
originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1599617

**Comment by gregsheremeta** [comment]
@michalskrivanek @lizsurette @lwrigh "then hide Create Virtual Machine" -- we need to decide on hide vs. disable with tooltip

**Comment by lwrigh** [comment]
In a situation like that I would lean towards hiding the item if the user doesn't have the permissions to access it.

**Comment by michalskrivanek** [comment]
in end-user focused portal I agree. 
I wouldn't agree in webadmin where we need to show why is it not possible at the moment and what can be done about it.

**Comment by lwrigh** [comment]
Good point, I agree. In the web admin portal it doesn't seem appropriate to hide it.
