### ISSUE TITLE
allow creating vm from blank template when datacenter is enforcing quota

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#744]
Description of problem:
RFE: allow creating vm from blank template when datacenter is enforcing quota

Version-Release number of selected component (if applicable):
rhv 4.2.+

How reproducible:
everytime

Steps to Reproduce:
1. make sure dc is enforcing quota
2. try to create vm in vm portal with user with enough permission from blank template

Actual results:
vm creation will fail with error below:

ERROR [org.ovirt.engine.api.restapi.resource.AbstractBackendResource] (default task-5) [] Operation Failed: [Cannot add VM. The user is not a consumer of the Quota assigned to the resource.]

Expected results:
vm will be created

Quota is rarely used, and it's a pending gap in functionality

**Comment by gregsheremeta** [comment]
originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1619154

**Comment by gvasilopulos** [comment]
This is essentialy the same bug as #682. So I think you can remove #682..
I saw in redhat bug report that quota is rarely used, but in fact this is a very useful feature for organizations who have hierarchical administration. E.g. in a university where I have the central management of virtualisation, and I would like to give certain resources to the sysadm of mathematics department (or any other dept) without allowing him to enter the admin portal. So I grant him a quota of X disk space Y cpu cores and Z Ram amount and he is independent to act as he sees fit with his resources, without poking around in the admin portal..
It would be really nice to have a fix for this

**Comment by bond95** [comment]
@gregsheremeta patch was merged and verified, can we close it?

**Comment by gregsheremeta** [comment]
yes
