### ISSUE TITLE
error box in VM detail shown over notification drawer

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#761]
![screenshot from 2018-09-06 14-25-53](https://user-images.githubusercontent.com/29575480/45157340-3208de00-b1e1-11e8-8a3c-5d1abf85b14c.png)

tested in ovirt-web-ui-1.4.3-1.el7.noarch

**Comment by gregsheremeta** [comment]
since we'll delete this page, it's not worth a fix. But we should be on the lookout for similar problems in dashboard view. cc @bond95 @sjd78

**Comment by sjd78** [comment]
It's any box that has the `.alert` css class....

![screenshot-localhost-3000-2018 09 17-09-30-21](https://user-images.githubusercontent.com/3985964/45626013-558f1c80-ba5c-11e8-881a-0c65115e9a8b.png)
