### ISSUE TITLE
ux-redesign: snapshots: updating status icon after creating a snapshot

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#763]
While creating a new snapshot, locked status icon is displayed. Locked icon still persists even after snapshot was successfully created unless whole page is refreshed.

![selection_010](https://user-images.githubusercontent.com/16017126/45373767-869cc680-b5f0-11e8-9c3a-0096916baed6.png)

![selection_011](https://user-images.githubusercontent.com/16017126/45373790-961c0f80-b5f0-11e8-827b-33e62ffcc115.png)

**Comment by bond95** [comment]
@samuelmacko Could you, please, check it again on newest master? Because for me everything work fine.

**Comment by samuelmacko** [comment]
Tested on ovirt-web-ui-1.4.4-0.20181001git2b2ee57.fc28.noarch.rpm.
Issue is no longer relevant, status icon works as it should.
