### ISSUE TITLE
can't create or restore a snapshot with UserRole but can delete it

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#767]
User with 'UserRole' role is authorized to delete snapshots.

**Comment by gregsheremeta** [comment]
Is this a bug or an RFE?

**Comment by xmacko10** [comment]
I would say bug, user with UserRole can't create or restore a snapshot but can delete it.

**Comment by bond95** [comment]
Not relevant. Issue was already fixed in https://github.com/oVirt/ovirt-web-ui/pull/905
