### ISSUE TITLE
Any plan to refactor webadmin ui?

### ISSUE THREAD

**Issue by imjoey** [oVirt/ovirt-web-ui#769]
hi, thanks for great work! I am wondering that if there has any plan to refactor the GWT-based webadmin ui via the modern patternfly framework? Thanks.

**Comment by gregsheremeta** [comment]
It already uses patternfly, so I'm not sure what you mean. Is there something specific you're looking for?

**Comment by imjoey** [comment]
hi, thanks for you reply. It seems that currently the weadmin ui along with oVirt 4.2 still use GWT framework to generate JS/CSS files from Java codes. I mean does the community has any plan to use pure JS/CSS to implement the webadmin, like this web-ui project. Thanks.

**Comment by imjoey** [comment]
@gregsheremeta ok, thanks very much. 😄
