### ISSUE TITLE
ux-redesign: VM Details > Details Card (advanced options)

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#777]
![image3](https://user-images.githubusercontent.com/3985964/45703176-89903d80-bb41-11e8-96ca-d3d8de2bdf44.png)

The "Advanced Options" fold on the details card in edit mode.

See the [Edit VM- Basic and Advanced Options](https://docs.google.com/document/d/1PuaaeEsPbUlFaFoh9lCvxkw3gOh8-wQ7vHhdYBFFVfI/edit#heading=h.zh2twut5rkij) design doc.

**Comment by samuelmacko** [comment]
ci build please
