### ISSUE TITLE
Pool does not appear for user in group until refresh

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#785]
[BZ1624219](https://bugzilla.redhat.com/show_bug.cgi?id=1624219)

Upon login to VM Portal, a user cannot see a Pool if the permission was given to the user's Group and not directly to the user. The user only sees it after a refresh.

Steps to reproduce:
 - Add a user
 - Add a group
 - Make the user a member of the group
 - Create a pool on the Administration portal (webadmin)
 - On the pool itself, assign role **UserRole** to the new group
 - Login to web-ui with the new user

The pool that was permissioned will not show up when the user first logs in to web-ui.  However, it will show up after a refresh.

**Comment by sjd78** [comment]
Currently blocked on BZ1624219.

There is an issue with the stored procedures underpinning the pagination queries used by the REST api.  Those queries need to be updated to check both user and group assigned permissions.

**Comment by bond95** [comment]
Looks like bug was fixed, so I close this issue https://bugzilla.redhat.com/show_bug.cgi?id=1624219
