### ISSUE TITLE
Address login saga initial data load concurrency issues

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#789]
When loading and populating the initial redux store at login time, everything is currently done in parallel with async dispatches.

At the very least, the app's initial data load needs to be gated such that ALL of the user's data is loaded in the redux store BEFORE permissions are calculated on clusters and VMs (and other entities in the future).

Beyond the base gating that needs to be done, the flag used to load the App's routes and pages should be re-evaluated.  Often time a page is rendered basic and then re-rendered when the base data finally arrives and is loaded in the store.  Gating the app to start page render after a minimum set of data is loaded to minimize this behavior would be ideal.

Proposed flow (left most bullets happen sequentially):
  - Login and User data (as a set of actions)
    - verify SSO token
    - verify API version
    - fetch and store user data (group membership, admin/default filtering, etc?)
  - Base non-VM redux store loading (fetch, transform and store each concurrently since they don't depend on each other)
    - Clusters
    - Hosts
    - Operating Systems (and icons)
    - Templates
    - Storage Domains, ISO Storage Domains and ISO files
    - VNIC Profiles
  - Load the first page of VMs and Pools
  - Start the background data refresh scheduler

Note: May need a quick UX design for an "Initial App State is loading" design to display to users after login and user data is verified and fetched but before the redux store is ready for page render.

**Comment by gregsheremeta** [comment]
:+1: Nice write up.

Roughly, do you have an idea for the gating mechanism at the code level? I suppose my redux-saga knowledge is lacking here. I'm guessing it won't be as simple as chaining some .then()'s together :smile:

**Comment by sjd78** [comment]
This article [Common patterns with Redux-Saga](https://engineering.universe.com/common-patterns-with-redux-saga-ed68f89dfecf) has concepts that are very close to what I'd adopt.  Perhaps mix in a bit of [concurrent task queue](https://medium.freecodecamp.org/how-to-use-a-concurrent-task-queue-in-your-redux-sagas-39e598c4fcae) for good measure.

In summary, need to do something similar to a Barrier in java (which is inherently multi-threaded) but with the event/message driven concurrency in redux/saga on js (which is single threaded with promises).  Plus the whole process is a bit more complicated when the sagas have chained dispatches (a saga function that does a `put()` -- a non-blocking async operation).
