### ISSUE TITLE
disable all action buttons when removing snapshot

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#792]
When VM is performing an operation on a Snapshot, you can't do snapshot creating or restoring, but you can delete snapshots. Thus it would be nice to disabling create and restore button if there is some pending actions (now all buttons are disabled only for restore pending action). 
![image](https://user-images.githubusercontent.com/3332176/46346962-24147480-c64a-11e8-9ab9-3c9e7e29027b.png)

**Comment by leistnerova** [comment]
When the actions are done in VM portal, disabling buttons works as expected. But problem is, when the action is performed in admin portal.
The VM snapshots are not actualized in detail, even when pressing reload button. I have to go to VM grid and back to VMs detail to see the changes and there were not disabled buttons.

Steps to reproduce:
1. create 2 snapshots for one VM
2. log into VM portal, go to VMs detail to see 2 snapshots
3. in admin portal delete one of them
4. snapshots is locked in admin portal
5. look into VM portal - 2 snaphots both OK and actions buttons enabled, even when automatic reload was done
6. click on reload button in top menu
7. snapshots are not changed
8. go to VM grid and back to VM's detail
9. one snapshot is locked with disabled action buttons, second is OK with enabled actions buttons

tested in ovirt-web-ui-1.5.0-0.20181011git9437c14.el7.noarch with ovirt-engine-4.3.0-0.0.master.20181016132820.gite60d148.el7.noarch 

![screenshot from 2018-10-18 13-07-11](https://user-images.githubusercontent.com/29575480/47158445-f5ee9000-d2eb-11e8-9df7-61873d00ae0e.png)
