### ISSUE TITLE
Overview Card > change VM name validation and set cloud-init hostname change

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#803]
In the legacy VM edit page, changing a VM's name also includes a valid name check and updates cloud-init hostname depending on how it is set in the VM's template:

https://github.com/oVirt/ovirt-web-ui/blob/aff035eff23496834d34a7402497212459f86458/src/components/VmDialog/index.js#L241-L258

The current VM Details Overview card will change the VM name, but does not include the name check and does not update the cloud-init hostname.  I assume both of these behaviors should be added to the Overview card.

**Comment by gregsheremeta** [comment]
@sjd78 is this still relevant?
