### ISSUE TITLE
web-ui - dummy data only

### ISSUE THREAD

**Issue by gematik-fue** [oVirt/ovirt-web-ui#833]
Hi, 
i've updated ovirt from 4.2.5.3-el7 to 4.2.6.4-1.el7 (web-ui 1.4.2) recently, which brought the new, but unfunctional web-ui to our users.
Is this a bug or intentional behavour?

![ovirt4 2 6](https://user-images.githubusercontent.com/34300220/47089508-4816af00-d221-11e8-8a06-280366908561.PNG)

**Comment by gregsheremeta** [comment]
> Is this a bug or intentional behavour?

somewhere in between :)

ovirt 4.2.7 includes the latest ovirt-web-ui release 1.4.4 [https://github.com/oVirt/ovirt-web-ui/releases], which removes this.

**Comment by gematik-fue** [comment]
Can I force "Legacy view" as default for now, somehow?
