### ISSUE TITLE
When renaming a NIC, an error occours.

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#840]
After an attempt to rename a NIC, error is displayed:
![selection_030](https://user-images.githubusercontent.com/16017126/47222158-50542300-d3b6-11e8-81a2-752dc941eb74.png)
engine.log:

[log_snippet.txt](https://github.com/oVirt/ovirt-web-ui/files/2496072/log_snippet.txt)

**Comment by sjd78** [comment]
Fixed in #796, commit 6cd7161.
See #796 for RPMs with the fix.
