### ISSUE TITLE
Wrong option in 'Type' dropdown in NICs edit menu

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#841]
Option 'VirtIO' is always displayed in a 'Type' drop down menu regardless of an actual type of a NIC.
![selection_032](https://user-images.githubusercontent.com/16017126/47222574-66161800-d3b7-11e8-8ee5-a2398330efb1.png)
In web admin:
![selection_033](https://user-images.githubusercontent.com/16017126/47222576-67dfdb80-d3b7-11e8-9952-b9e57529d4ad.png)

**Comment by sjd78** [comment]
Fixed in #796, commit 6cd7161.
See #796 for RPMs with the fix.
