### ISSUE TITLE
VM Details > Disks Card > Editor Dialog - Add tooltip for size editing

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#846]
Note: After a lot of discussion in #1104, we determined the best solution was to leave the fields as-is but add a tooltip to the "increase by" size field.  See: https://github.com/oVirt/ovirt-web-ui/pull/1104#issuecomment-533160675.

----

The #838 implementation of disk edit includes 2 size fields, the first displays the current size while the second specifies how much to expand the disk size:
![screenshot-localhost-3000-2018 11 01-18-28-44](https://user-images.githubusercontent.com/3985964/47883593-fadf3380-de03-11e8-9897-9423303a73ba.png)

The proposed change is to combine the display and expand size, with an initial and minimum value of the current disk size:

> For the 'Edit Disk' modal:
> 
> * I would get rid of the 'Extend size by' field and only have the 'Size' field. The 'Size' field could feature the same info tip that I noted in the comment above about 'Once you have created a disk, you can only extend the size of the disk if you make any edits to it.' The 'Size' field in edit mode could feature the up and down value adding buttons but have the down arrow disabled so the user could only increase the value. An error message could also appear below the field if they enter a value that is below the current size.

**Comment by gregsheremeta** [comment]
> but have the down arrow disabled

only issue here is if user clicks up a few too many times and actually wants to go back down -- e.g. extend by 11, oops I meant 10

**Comment by sgratch** [comment]
@sjd78 @yodem @lwrigh Not sure why we need to combine those 2 fields since in webadmin it looks the same for editing a VM's disk. The "Size" field is greyed out and only the "extend size by" is editable.
This way it's easy to see current value and desired extended value at the same time. In addition, we want to consider adding a tool-tip only to 2nd field for extending the disk size (issue #1006)

Webadmin:
![](https://screenshotscdn.firefoxusercontent.com/images/efcc4e96-1d25-41c7-892e-49d2593f7f38.png)

**Comment by lwrigh** [comment]
@sgratch I think it could be useful to see the total number for the size so the user could see something like: 

<img width="1098" alt="Screen Shot 2019-08-20 at 10 31 16 AM" src="https://user-images.githubusercontent.com/20227374/63356384-ab87d680-c335-11e9-9071-dd9a7238f78d.png">

I think the fields could be a bit more clear however. I think if we had some sort of number slider it would be visually more clear what's going on. I'm not sure if there's a PatternFly component for it though.

**Comment by yodem** [comment]
I don't think its necessary to have 3 fields that emphasizing the same thing.
If the field would combine the user will be able to specify a new size, and not an expanding size, and by that he could know what is the new size.

**Comment by sgratch** [comment]
This "extended size by" field is relevant only for editing an **existing** disk and not for creating a new one and since we can only extend the size of the disk and not reduce it then I can't see any issue with leaving those 2 fields while the "size" field is a non-editable one

**Comment by yodem** [comment]
I think we can close this issue, I mean we didn't get a decision and the current state is fine, right?

**Comment by sjd78** [comment]
> I think we can close this issue, I mean we didn't get a decision and the current state is fine, right?

I was never really convinced that combining the fields was all that useful.  At this point I don't remember where the bullet point quoted in the issue description came from.  Leaving the dialog the way it is works for me.

@sgratch - Thoughts?

**Comment by sjd78** [comment]
@sgratch - The work for this issue morphed via discussion in #1104, with the net result in https://github.com/oVirt/ovirt-web-ui/pull/1104#issuecomment-533160675.  I'll adjust the title and initial description for this issue.

I'm reopening the issue so the tooltip work can get tested and merged.

**Comment by sjd78** [comment]
> @sgratch - The work for this issue morphed via discussion in #1104, with the net result in [#1104 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1104#issuecomment-533160675). I'll adjust the title and initial description for this issue.
> 
> I'm reopening the issue so the tooltip work can get tested and merged.

Sigh.  The PR for this got moved to issue #1006.  Closing this issue again.
