### ISSUE TITLE
GET_ALL_CLUSTERS internal server error

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#851]
After refreshing a page in VM portal, GET_ALL_CLUSTERS failed Internal Server Error is displayed.

![selection_001](https://user-images.githubusercontent.com/16017126/48137753-079bd580-e2a3-11e8-8326-dbf2a46fca56.jpg)

engine log snippet if needed:
[engine.log](https://github.com/oVirt/ovirt-web-ui/files/2557868/engine.log)

**Comment by sjd78** [comment]
Fixed in the current rpm build of #838
