### ISSUE TITLE
Can't see storage domain while creating a disk

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#852]
There is no storage domain to choose in a create new disk popup even though there is storage domain displayed in Webadmin.
In VM portal:
![selection_003](https://user-images.githubusercontent.com/16017126/48139788-a0cceb00-e2a7-11e8-89f3-93fa1c699d88.jpg)

In Webadmin:
![selection_002](https://user-images.githubusercontent.com/16017126/48139806-aa565300-e2a7-11e8-9818-2342e4a0b2b2.jpg)

**Comment by bond95** [comment]
@samuelmacko Does user has right permissions?

**Comment by sjd78** [comment]
Fixed in the current rpm build of #838
