### ISSUE TITLE
"Console In Use" dialog shows for users who have already opened the VM's console

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#861]
The check used to determine if a VM's console is in use by another user is backwards.

Steps
 1. Click the console button on a VM and open the console.
 2. Click the console button again.

Results
 - **Expected**: No "Console In Use" dialog is displayed on the second Console button click and the console is immediately opened
 - **Actual**: "Console In Use" dialog is displayed each time

Seems related to #477

**Comment by samuelmacko** [comment]
Tested on ovirt-web-ui-1.5.0-0.20181120git0bc43cc.el7.noarch
Original issue is fixed, if user1 opens the console, user2 gets the "Console in use, continue?" popup, but new issue has arised, even after user1 closes the console, user2 still gets the "Console in use, continue?" popup.
