### ISSUE TITLE
Edit Disks > visual artifact when editing many disks / small window size

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#875]
We noticed that
1. the Ok and Cancel buttons appear in their own mini-box below the main box
2. with a really long disk name, the icons didn't stay aligned in a column

![selection_206](https://user-images.githubusercontent.com/2248293/48789012-0498e000-ecba-11e8-92d7-feb97dcb8216.png)

I'm not sure if this happens with many disks (3 or 4+) or a certain window size.

**Comment by bond95** [comment]
Similar bug
![image](https://user-images.githubusercontent.com/3332176/49799753-ff253780-fd45-11e8-95eb-84ad4d72f3ea.png)

**Comment by bond95** [comment]
![image](https://user-images.githubusercontent.com/3332176/49801244-f8002880-fd49-11e8-886c-871af5d1858c.png)

But

![image](https://user-images.githubusercontent.com/3332176/49801262-01899080-fd4a-11e8-9f2b-2243c2743ef4.png)

:laughing:
