### ISSUE TITLE
VM Details - remove Status field from Details Card and move uptime to Overview Card

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#893]
![screenshot-localhost-3000-2018 12 13-12-31-36](https://user-images.githubusercontent.com/3985964/49956401-134a6f80-fed3-11e8-9cce-5c32f003d678.png)

~~On the details card, the **Status** field shows the VM's status and the VM uptime.  Currently the formatted uptime follows the output of the unix `uptime` command.  A more user friendly formatting is preferred.~~

The Details Card duplicates the **Status** field from the Overview Card.  The field should be removed and the uptime should be added to Overview's **Status** field.  A more user friendly formatting is preferred (as discussed in the comments below).

For reference, the formatting is done by the [`moment-duration-format` package](https://github.com/jsmreese/moment-duration-format).  Currently the format is (`src/utils/format.js`):

````js
  const formatted = moment.duration(durationInMS).format('d [days], h:mm')
````

**Comment by lwrigh** [comment]
After looking at the reference document I think it makes sense to go with a format that features the duration of the elapsed time fully spelled out so it follows a format of: 

_(up for 0 days, 0 hours, 1 minute, 37 seconds)_  

Using the significant digits option looks like a possibility as well for showing the uptime. We can omit seconds if we think if it's too nit picky. 

@sjd78 @gregsheremeta @bond95

**Comment by gregsheremeta** [comment]
+1.

Seconds are slightly helpful initially, but after it's been up for a few hours or days, could probably drop seconds.

**Comment by lwrigh** [comment]
Agreed, that makes sense to me.

**Comment by gregsheremeta** [comment]
@sjd78 you ok with the `if` and toggling the seconds? Maybe shut off seconds after 2 minutes.

**Comment by lwrigh** [comment]
@sjd78 Is the uptime font the same size as the status font?

**Comment by lwrigh** [comment]
@sjd78 We could possibly change the uptime font to 10px, that's the smallest sized font that PF recommends using.

**Comment by sjd78** [comment]
> @sjd78 We could possibly change the uptime font to 10px, that's the smallest sized font that PF recommends using.

I tried the 10px and doesn't really give much more horizontal space, and it is for sure the smallest we should go!
