### ISSUE TITLE
add unsupported browser warning for IE11 on ovirt-web-ui 1.5+

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#895]
add 'unsupported browser warning' for IE11 on ovirt-web-ui 1.5+

From ovirt-web-ui 1.5+, IE support is dropped. Add a warning advising user to use Edge, Chrome, Firefox, etc.

@lwrigh @lizsurette does PatternFly have anything? Google found me: https://github.com/cockpit-project/cockpit/issues/9438#issuecomment-407384005

**Comment by lwrigh** [comment]
@gregsheremeta PatternFly doesn't have anything too specific for situations like that as far as I know. There are inline notifications that could work in this scenario: https://www.patternfly.org/pattern-library/communication/inline-notifications/#overview

**Comment by gregsheremeta** [comment]
@bond95 @lwrigh they ended up with https://github.com/cockpit-project/cockpit/pull/9781 all text, no logos.

we do not support GNOME Web, but we do try to support Safari, so let's replace GNOME Web with Safari and otherwise try to make it look similar.

**Comment by lwrigh** [comment]
@gregsheremeta @bond95 That sounds like a good solution to me with going with all text. I can do a quick mockup that features Safari instead of GNOME Web.

**Comment by bond95** [comment]
@gregsheremeta @lwrigh yeah, with all text is better.

**Comment by lwrigh** [comment]
Here's the mock up featuring the unsupported browser message and the supported browser options: 
![ie unsupported](https://user-images.githubusercontent.com/20227374/50611992-672eef80-0ea6-11e9-817f-b532e2fa00ff.png)

**Comment by lwrigh** [comment]
Updated mock up: 
![ie unsupported 2](https://user-images.githubusercontent.com/20227374/50655242-85a3f200-0f5d-11e9-86b5-b7f327b6cd5a.png)

**Comment by gregsheremeta** [comment]
@lwrigh +1 nice.

**Comment by michalskrivanek** [comment]
@bond95 the second one is nicer though;)
