### ISSUE TITLE
Add branding

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#90]
Nothing complex, just possibility to override app name, icons, about dialog.
Use RHV to test for sufficient extensibility.

**Comment by jniederm** [comment]
Current favicon `/src/favicon.ico` is most probably branding specific.

**Comment by jniederm** [comment]
Wiki page [Branding][1] (WIP).

Please comment/edit.

[1]: https://github.com/oVirt/ovirt-web-ui/wiki/Branding

**Comment by mareklibra** [comment]
https://github.com/oVirt/ovirt-web-ui/pull/287
