### ISSUE TITLE
VM Console single sign on modal enhancements

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#900]
RFE: VM Console SSO modal enhancements

(1) When demoing the new console single sign on modal, we found it too intrusive. Every time a user accesses a console, the popup shows (if the guest agent isn't installed, for example [and not every vm will get a guest agent]). There is nothing a user can really do except install the guest agent, or if it's already installed, contact an admin. So it should not show every time the user clicks the `Console` button.

(2) The language is currently:
`SSO logon to the VM's console failed. Do you want to continue without SSO?`
(2a) `SSO` isn't user-friendly language.
(2b) The only user impact is that user now has to log in to vm with username and password. The primary action is Connect, and not getting single sign on is probably minor, so the modal shouldn't ask -- it should simply inform with a secondary to action to back out, although user probably never would.

So:

1. Show the modal only once per VM (maybe per VM per session) -- so use local storage or session-scoped variable or something. (@michalskrivanek preference on once per VM ever or per VM per login session?)

2. Tweak the language a bit. `Single sign on failed. Please make sure the guest agent is installed on your virtual machine. Contact your administrator if the problem persists.`  and buttons would be `Connect` (primary) and `Cancel` (secondary).

**Comment by gregsheremeta** [comment]
@lwrigh what do you think?

**Comment by lwrigh** [comment]
![sso error](https://user-images.githubusercontent.com/20227374/50786295-23126500-1281-11e9-9d24-99899413b1e4.png)
Is this in alignment with what you were thinking of? @gregsheremeta

**Comment by gregsheremeta** [comment]
@lwrigh oops I was unclear -- this language replaces the language in the dialog from #844 (but that screenshot is old -- the dialog currently says  
```
cantLogonToConsole: 'SSO logon to the VM\'s console failed. Do you want to continue without SSO?',
```
)

We noticed it during the demo that it was a bit off, experience wise.

So, this dialog appears when user clicks console. It's a different single sign on than you're thinking. Homonyms are terrible lol :) This one is "single sign me on into my vm console when i click the console button" (vs. sso me into the instance of ovirt)

**Comment by gregsheremeta** [comment]
(in other words, I wouldn't have to give a windows vm my password on the windows login screen in the vm console)

**Comment by lwrigh** [comment]
Ah okay that makes sense to me. I think the text for that modal and button names work for me then.
