### ISSUE TITLE
show unsupported browser message for older Firefox and Chrome

### ISSUE THREAD

**Issue by Ninroot** [oVirt/ovirt-web-ui#918]
Hi,

Alert the user when an unsupported (old) version of browser is used.

Tested version: `ovirt-web-ui-1.4.4-2.el7.noarch`
Related [thread](https://lists.ovirt.org/archives/list/users@ovirt.org/thread/OGAK4BCLMNSECGACT3UC7NVHSQ7Y3ROY/#T5Z2PBBBSHK5J2XANKHQEDOGIQ243XQR) for details.

Possible solution: https://github.com/oVirt/ovirt-web-ui/pull/904

**Comment by gregsheremeta** [comment]
We need a matrix.

IE everything is not supported.
All Edges are supported - ?
Firefox "at least 47" according to @bond95 (from [users list post](https://lists.ovirt.org/archives/list/users@ovirt.org/thread/OGAK4BCLMNSECGACT3UC7NVHSQ7Y3ROY/#T5Z2PBBBSHK5J2XANKHQEDOGIQ243XQR) )
Chrome - ?
Safari - ?

**Comment by Ninroot** [comment]
Working with Chromium 68.0.3440.106

**Comment by sjd78** [comment]
#904 and #1014 adds a place to do browser support checking and a component to render when a browser is not supported.

This is the function to update with the supported browser matrix:
https://github.com/oVirt/ovirt-web-ui/blob/0d42de783cf19bfb514964a199e05b769f51bdcc/src/App.js#L77-L79

**Comment by sgratch** [comment]
This is an old issue and since not handled up til now then I guess we can close this as WontDo.
Please re-open if you think it's important.
