### ISSUE TITLE
confirmation message on Edit VM save

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#921]
50% of participants in UXD testing for improving the user experience expected a confirmation message to confirm that edits have been saved after the user is done making edits to a card from the VM dashboard view.

**Comment by gregsheremeta** [comment]
The real root issue is that REST API calls take a while, and the save can take 5 or more seconds. So it's an issue of immediate feedback ("why is this thing taking so long?")

Adding a "Saving, please wait..." spinner or something makes more sense to me than a "Saved" notification 5 seconds later, but I'm not opposed to doing both. Although I do get concerned about spamming with toasts.

**Comment by sgratch** [comment]
We didn't get to it yet and since it's opened for long time then closing.
