### ISSUE TITLE
Consired moving Create VM to bottom

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#922]
When creating new VM in the user portal the 'Create VM' button should be in the bottom (next/under to the upload/default button)

Version-Release number of selected component (if applicable):
4.2.7

Additional info:
50% of participants in UXD testing for improving the user experience, expected the 'Create VM' button to be closer to the bottom of the page when creating a VM.

**Comment by michalskrivanek** [comment]
50% doesn't sound to me important enough though. @lwrigh any further thoughts on that?

**Comment by lwrigh** [comment]
@michalskrivanek I would say from a percentage stand point I would consider 50% to be a significant amount of users who made similar comments so I would push to move the button still. Smaller details like this really helpful to improve the UX :)

**Comment by michalskrivanek** [comment]
okay

**Comment by gregsheremeta** [comment]
@lwrigh It's on the bottom in the New VM design, right?

**Comment by lwrigh** [comment]
@gregsheremeta Yes the suggestion is to move it to the bottom for the design updates for it. Did Liz work on New VM design work earlier last year? I can't seem to find it in the drive.

**Comment by gregsheremeta** [comment]
> @gregsheremeta Yes the suggestion is to move it to the bottom for the design updates for it. Did Liz work on New VM design work earlier last year? I can't seem to find it in the drive.

https://docs.google.com/document/d/1UtFhNa_1byMV5mLEJ1MbdvZj-uMpmsD-_bJ37JDcyjU/edit
