### ISSUE TITLE
Redesign Create VM

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#923]
redesign Create VM flow

design document:
https://docs.google.com/document/d/1UtFhNa_1byMV5mLEJ1MbdvZj-uMpmsD-_bJ37JDcyjU/edit

![screenshot from 2019-02-13 11-43-34](https://user-images.githubusercontent.com/2248293/52728137-bcb9ea00-2f84-11e9-9535-6d3302c22b49.png)

![screenshot from 2019-02-13 11-43-40](https://user-images.githubusercontent.com/2248293/52728146-c04d7100-2f84-11e9-9ad9-4fd19a33aa24.png)

See also: #695

**Comment by lwrigh** [comment]
@sjd78 Let me know if you would rather do an in person or recorded design review of the wizard. I'd be happy to do either.
