### ISSUE TITLE
Cant edit VMs with more than 16 "Number of CPU Cores"

### ISSUE THREAD

**Issue by mathrock74** [oVirt/ovirt-web-ui#924]
Users can't edit VMs in VM Portal that have been configured with more than 16 "Number of CPU Cores" in Admin Portal, error message is "[Cannot edit VM. Maximum number of sockets exceeded.]​". The user doesn't want to edit CPUs, just wants to insert a CD image and gets that message. This happens eg. for a VM with "Number of CPU Cores: 24 (12:2:1)". This VM has clearly 12 virtual sockets, but gets the "Maximum number of sockets exceeded" message when edited by a user. "engine-config -g MaxNumOfVmSockets" gives "MaxNumOfVmSockets: 16 version: 4.2". Therefore I consider this a bug in ovirt-web-ui, I suspect it is looking at the wrong number.

oVirt version is 4.2.7
ovirt-web-ui is 1.4.4-2.el7

**Comment by michalskrivanek** [comment]
I'd at first honor the topology in template. Currently the editing always assumes 1 even when existing VM uses different topology. Tehre are some TODOs in the code about that.
And as a next step provide full topology editing capabilities

**Comment by bond95** [comment]
> Users can't edit VMs in VM Portal that have been configured with more than 16 "Number of CPU Cores" in Admin Portal, error message is "[Cannot edit VM. Maximum number of sockets exceeded.]​". The user doesn't want to edit CPUs, just wants to insert a CD image and gets that message.

This bug was already fixed in new Dashboard view. But still exists problem if user want to change number of CPUs, it automatically set topology (number of CPUs:1:1). To fix it, need to get `MaxNumOfVmSockets` value, but RestAPI for now doesn't support this. Thus second solution is to allow user edit topology directly in VM Portal, as was mentioned in previous comment.

@michalskrivanek @gregsheremeta @sjd78 WDYT?

**Comment by gregsheremeta** [comment]
> @michalskrivanek @gregsheremeta @sjd78 WDYT?

Let's "first honor the topology in template", so we need the REST API enhancement for `MaxNumOfVmSockets`

**Comment by gregsheremeta** [comment]
1. Take a look at how to display this -- user should understand for example why user could only enter 2 / 4 / 6 etc (sockets, cores, threads)

2. full blown editing capabilities of these?

Admin Portal:
![selection_334](https://user-images.githubusercontent.com/2248293/51985869-efd08980-246c-11e9-8a60-78b111fa036c.png)
