### ISSUE TITLE
legacy New VM view sometimes truncates the left column

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#930]
legacy New VM view sometimes truncates the left column:

Chromium 71 Fedora 29, 1920x1080, no zoom:

![selection_314](https://user-images.githubusercontent.com/2248293/51616517-42072d00-1ef8-11e9-8fd6-689ed05478a6.png)

It works fine for me in Chrome 66 / Fedora 28

(the fix is probably to not hardcode that column width to 200px. It should use a grid instead.)

**Comment by sjd78** [comment]
This issue will become moot when #923 is implemented by #987

**Comment by sgratch** [comment]
This was fixed by #923 and therefore should be closed
