### ISSUE TITLE
Running VM has Host 'N/A' in Details for non-admin user

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#933]
Running VM has Host N/A in Details for non-admin user. Admin user can see there name of the host where VM is running.

**Comment by michalskrivanek** [comment]
That’s infra stuff, I wouldn’t think a regular user is supposed to know/care

**Comment by leistnerova** [comment]
@michalskrivanek  OK, that make sense. So it could be removed completely for users that can't see it.

**Comment by michalskrivanek** [comment]
+1
