### ISSUE TITLE
VM action buttons are partially hidden with only one row of VMs in grid

### ISSUE THREAD

**Issue by pnovotny** [oVirt/ovirt-web-ui#936]
When there is only one row of VMs in the grid,
VM action buttons Shutdown/Reboot/Console from the dropdown list are partially hidden
and vertical scrollbar is shown.

Screenshot: https://imgur.com/a/0HExxsj

**Comment by pnovotny** [comment]
Reproduced only in ovirt-web-ui-1.4.5-1 (oVirt 4.2), in ovirt-web-ui-1.5 (oVirt 4.3), all the buttons from dropdown are visible.

**Comment by gregsheremeta** [comment]
Thanks for reporting. Closing fixed-current-release since 4.2 is done.
