### ISSUE TITLE
VM list page needs static ID on Suspend button

### ISSUE THREAD

**Issue by pnovotny** [oVirt/ovirt-web-ui#937]
Version: ovirt-web-ui-1.4.5-1

In previous builds, Suspend, Shutdown and Reboot buttons in the VM grid have had static IDs
named *vmaction-{vm_name}-button-suspend*, *vmaction-{vm_name}-button-shutdown* and *vmaction-{vm_name}-button-reboot*.

In version 1.4.5-1 (the latest ATM), these IDs are missing, which makes Selenium testing problematic.

**Comment by pnovotny** [comment]
> In version 1.4.5-1 (the latest ATM), these IDs are missing, which makes Selenium testing problematic.

`ovirt-web-ui-1.4.5-1` is actually the latest build for oVirt 4.2, not for 4.3+.

**Comment by gregsheremeta** [comment]
Did we ever actually backport this?

Does it still exist in 1.5?

**Comment by pnovotny** [comment]
In ovirt-web-ui-1.5.0-0.20181122git967b89b there are static IDs for buttons Run, Shutdown, Reboot and Console, but not for Suspend.

**Comment by gregsheremeta** [comment]
> In ovirt-web-ui-1.5.0-0.20181122git967b89b there are static IDs for buttons Run, Shutdown, Reboot and Console, but not for Suspend.

Thanks!

Ok, 1.4.z is done -- we won't release another 1.4 unless there is a critical security issue someday.

So, we just need to fix suspend in 1.5.

**Comment by bond95** [comment]
Is this still relevant? Because with https://github.com/oVirt/ovirt-web-ui/pull/956 `Suspend` will be first button and as I said earlier `Unfortunately button near dropdown can't have ID, so need to get it in other way.`
@pnovotny @gregsheremeta

**Comment by gregsheremeta** [comment]
@bond95 do you mean that the top item in the list can't have an ID, but all of the others in the list can?

**Comment by pnovotny** [comment]
@bond95 yes, it's still relevant, we need to test all the VM action "buttons".

**Comment by bond95** [comment]
@gregsheremeta @pnovotny I mean that this action can't have id, only possible solution is to fully copy `SplitButton` component from Bootstrap. But do we really need this?
![console-red-square](https://user-images.githubusercontent.com/3332176/53030851-f77fbe80-346b-11e9-9bed-53e2bbbe0291.jpeg)

**Comment by gregsheremeta** [comment]
we're certainly not making a custom copy for an ID :)
We can file an issue to bootstrap, but it's not really worth the time.
@pnovotny so ... it's a huge pain to add an ID to the first one. Can you grab it another way?

**Comment by pnovotny** [comment]
@gregsheremeta OK, if it's difficult to make ID for it, I am sure we can use some crazy XPath for it as a workaround. Won't be pretty, but it will work.

**Comment by bond95** [comment]
Great. In this case I'll close issue.
