### ISSUE TITLE
snapshot creation elapsed time should not abbreviate the units

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#945]
snapshot creation elapsed time should not abbreviate the units

It would be good to remove these 6 strings from the i18n file:
y, M, d, h, m, s 
those caused confusion for translators. 
If we could do year, month, day, hour, minute, second  - those would be more clear. But, then we have to deal with plurality, which makes me wonder if the moment library can do this for us.

![selection_338](https://user-images.githubusercontent.com/2248293/52022520-3226b480-24c7-11e9-9d1b-38769e304f9b.png)

**Comment by gregsheremeta** [comment]
@lwrigh @sjd78 @bond95 I'm not 100% sure on this one. I opened it because it caused confusion for translators. We have a bit of design work if we want the full VM uptime style formatting in the snapshot card -- it's much longer.

Perhaps if the snapshots card only ever shows one time unit at a time, we could leave it but maybe spell out the unit for translation. So "2 hours ago" instead of "2h ago"

**Comment by gregsheremeta** [comment]
Yuko tells me the Japanese doesn't have singular vs. plural, but our other languages do. So let's definitely try to get this from moment.

**Comment by lwrigh** [comment]
Would including the creation time as a time stamp be an option?

**Comment by sjd78** [comment]
@gregsheremeta, @lwrigh - The uptime format function's important logic is here:
https://github.com/oVirt/ovirt-web-ui/blob/3b70b675f4b89692bc70ec80c5902bd99895c80b/src/utils/format.js#L31-L36

Basically `moment-duration-format` handles the i18n of the string.  Shouldn't be an issue and the confusing keys can be removed from our messages file.

I should also note, we may need to do some work to push the current locale into momentjs at login time similar to how it is push to react-intl.  I looked quickly and didn't see moment get setup like that.  If it doesn't get setup, probably will default to English.  See https://github.com/jsmreese/moment-duration-format#localization.

**Comment by sgratch** [comment]
Opened for more than a year and no user complained so closing.
Please re-open if you think it's still important.
