### ISSUE TITLE
Make dashboard more responsive

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#946]
It looks like the VM name and status get lost once the screen reaches a certain size however and that seems like important information to still have available. My one question is would it make sense to put the action buttons into a kebab menu if the screen size reaches a certain, narrow size?
https://github.com/oVirt/ovirt-web-ui/pull/934#pullrequestreview-198140711

@gregsheremeta @michalskrivanek @sjd78 @lwrigh

**Comment by gregsheremeta** [comment]
The action button row gets chopped pretty good, too.

**Comment by sjd78** [comment]
We never did a design of dashboard on a narrow screen.  A stopgap would be to set a minimum width on the screen and do horizontal scrolling (yuck) if the browser window gets too narrow.  

Although, a lot of the cards could have min-widths set to make a decent accommodation for narrow screens.  They're based purely on percentages right now.

**Comment by lwrigh** [comment]
@bond95 @gregsheremeta @michalskrivanek @sjd78 I can take a pass at a narrower dashboard view if you like. I can also see what a mobile dashboard might look like.

**Comment by lwrigh** [comment]
Here's the link design doc that I put together with some design suggestions for making the dashboard more responsive: https://docs.google.com/document/d/1p_MKG55VBWHPzxYl383nf5mU9Sj5Af11Naj6UXtRJ-4/edit?usp=sharing
