### ISSUE TITLE
Change hover texts in masthead

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#949]
Hover text over bell icon is 'Messages' but drawer head contains 'Notifications'.
Hover text over user icon doesn't contain profile like in admin portal (e.g. admin X admin@internal-authz)
And refresh icon doesn't have any hover text.

![screenshot from 2019-02-05 09-48-33](https://user-images.githubusercontent.com/29575480/52262126-d6778380-292b-11e9-89b0-89ffe2e60614.png)

**Comment by yodem** [comment]
@bond95 @sjd78 What do you think we should do? I mean, the problem is clear, but what is supposed to be the solution? To add hover text? And what text?

**Comment by sgratch** [comment]
This issue is depended on issue #1095

**Comment by yodem** [comment]
> This issue is depended on issue #1095

I solved it using patternfly 4 conventions as laura said

**Comment by yodem** [comment]
> This issue is depended on issue #1095

So i'll wait for the merge of this issue and then i'll change the commit
