### ISSUE TITLE
vmware provider

### ISSUE THREAD

**Issue by hetzbh** [oVirt/ovirt-web-ui#951]
I'm using 4.3.0, and here are some UI thoughts:
* In Virtual machines, when selecting import, and selecting "vmware", it shows "custom" (and empty fields). instead of showing the first vmware provider previously configured.
* In the vmware provider pop-up page, it asks for username and password but doesn't mention in the UI what user/pass (IMHO it should mention "vCenter/VCSA username" "vCenter/VCSA password"
* In the same page, "cluster" should IMHO be "cluster (optional)"

**Comment by gregsheremeta** [comment]
Hey :) This tracker is for the VM Portal, but sounds like this is an Admin Portal issue. The tracker for that is https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine  (Component = Frontend.Webadmin)

Would you mind opening this there? Thank you!

**Comment by hetzbh** [comment]
Opened. 1673208
