### ISSUE TITLE
Support sysprep for Windows VMs

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#972]
Feature enhancement request:
Windows VMs don’t have cloud-init but sysprep. So is no use for Cloud-init section in editing VM details.

**Comment by gregsheremeta** [comment]
@michalskrivanek 

During grooming, we identified that we need a design / spec for what sysprep would look like, and how it's different than cloud-init. We opened admin portal and saw that the primary difference there is that sysprep is a plain textbox. That isn't the user-friendliest thing -- is there a better way we can approach that in VM Portal? Let us know your thoughts.

**Comment by michalskrivanek** [comment]
it's not a plain text box, it has few dedicated options(say, the most common ones) and then a text box for custom copy&paste complete sysprep xml if you'd rather use the one generated by the ms tooling

**Comment by lwrigh** [comment]
Here's the design doc for adding sysprep options to the create new VM flow and the details card in the VM dashboard: https://docs.google.com/document/d/1oEzFcfulZnK6VxPtANrx6-GgMX9vd3CrH4ofvWzxrOc/edit?usp=sharing

**Comment by lwrigh** [comment]
I updated the doc to include wireframes that feature 'Custom Script' as the label instead of 'Sysprep Key'. I also added a draggable corner tab so the user knows that they can expand the field if their script is really long.

**Comment by isaranova** [comment]
ci build please
