### ISSUE TITLE
Disable editing VM template

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#973]
Description of problem [include screenshots and browser console logs]:
Template can't be changed for created VM. But in VM detail it could be and then is error returned.

VM Portal version number: master

oVirt version number:
ovirt-engine-4.3.1.2-0.0.master.20190222171227.gita00fd1d.el7.noarch

Browser and version: FF 65.0.1

![screenshot from 2019-02-27 09-05-43](https://user-images.githubusercontent.com/29575480/53474951-eb4cc000-3a6e-11e9-92f7-1f0c70ce1bac.png)

**Comment by sjd78** [comment]
From my trail-and-error testing:
  - Cannot change a VM's template
  - Cannot change a Pool VM's template
  - CAN change a Pool VM definition's template

It isn't allowed in webadmin and throws a rest error in web-ui.

To fix right now, I'll disable the UI from showing an editor on VMs.  I may leave some of the change code in the file (maybe a comment?) in case that Pool definition editing is implemented.  The code can be reused then.
