### ISSUE TITLE
New VM memory is in other units than in edit box

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#974]
Description of problem [include screenshots and browser console logs]:
New VM memory is in other units than in edit box. So user can create VM with memory in MB but then can change only in GB.

VM Portal version number:
master
oVirt version number:
ovirt-engine-4.3.1.2-0.0.master.20190222171227.gita00fd1d.el7.noarch
Browser and version: FF 65.0.1

Actual results: editing memory for VM is in GB

Expected results: editing memory for VM is in MB

**Comment by sjd78** [comment]
Same as #999

**Comment by sgratch** [comment]
Fixed in #999 and therefore we can close this issue
