### ISSUE TITLE
Disabled delete button on disks is not gray enough

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#977]
Description of problem [include screenshots and browser console logs]:
Disabled delete button on disks is not gray as in snapshots (on running VM). So the difference is bad visible.

VM Portal version number:
master
oVirt version number:
ovirt-engine-4.3.1.2-0.0.master.20190222171227.gita00fd1d.el7.noarch
Browser and version: FF 65.0.1

![screenshot from 2019-02-27 09-23-17](https://user-images.githubusercontent.com/29575480/53475884-63b48080-3a71-11e9-8eae-57888601c395.png)
![screenshot from 2019-02-27 09-23-28](https://user-images.githubusercontent.com/29575480/53475888-67480780-3a71-11e9-88c7-afcc144e36a3.png)

**Comment by yodem** [comment]
@lwrigh Would you like the trash icon in the disks section to be as gray as the snapshots' color?

**Comment by lwrigh** [comment]
> @lwrigh Would you like the trash icon in the disks section to be as gray as the snapshots' color?

I would recommend using the grey featured in snapshots card action buttons since that's the correct grey to use if an action is disabled.
