### ISSUE TITLE
vNIC profile is mandatory, but can stay <Empty>

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#980]
Description of problem [include screenshots and browser console logs]:
VNIC Profile is mandatory, but can stay <Empty>. Check by saving should be added that profile is other than that.

VM Portal version number:
master
oVirt version number:
ovirt-engine-4.3.1.2-0.0.master.20190222171227.gita00fd1d.el7.noarch
Browser and version: FF 65.0.1

Steps to Reproduce:
1. add new vNIC for VM
2. let profile stay <Empty>
3. save

Actual results: dialog is closed, error appears in notification

Expected results: can't save dialog with &lt;Empty&gt; profile

**Comment by sjd78** [comment]
@leistnerova , @bond95 - In webadmin it is perfectly valid to create a nic without a VNIC profile (it shows as "<Empty>".

**Comment by sjd78** [comment]
Here is the actual error from the REST api:

![screenshot-chopper local dickerson-web com-2019 05 16-19-40-14](https://user-images.githubusercontent.com/3985964/57893858-7b9ad580-7812-11e9-9000-11307d3ddf49.png)

So when `<Empty>` is selected, somehow something is getting the the API where it thinks a `vnicProfile` should be valid but isn't.  From my comment https://github.com/oVirt/ovirt-web-ui/pull/1017#issuecomment-493266050, web-ui is sending an empty string for the vnicProfile id, and that doesn't exist.  The empty string shouldn't be sent at all in this case.
