### ISSUE TITLE
Change ordering in notification drawer

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#982]
Description of problem [include screenshots and browser console logs]:
Notifications are ordered from oldest to newest, should be the other way around like in admin portal.

VM Portal version number:
master
oVirt version number:
ovirt-engine-4.3.1.2-0.0.master.20190222171227.gita00fd1d.el7.noarch
Browser and version: FF 65.0.1

![screenshot from 2019-02-27 17-42-07](https://user-images.githubusercontent.com/29575480/53506915-3be80b80-3ab7-11e9-98d2-2326a8f8efef.png)

**Comment by sgratch** [comment]
@bond95 @leistnerova seems like this is not reproduced anymore. Can you please approve it?

**Comment by bond95** [comment]
@sgratch @leistnerova yes, now notifications are ordered from newest to oldest. 
![image](https://user-images.githubusercontent.com/3332176/62622555-e8f46900-b91e-11e9-8fd4-4afd2f841b89.png)

**Comment by sgratch** [comment]
@bond95 @leistnerova Great, then can I close this issue as resolved?

**Comment by bond95** [comment]
@sgratch yes.
