### ISSUE TITLE
Template and Cluster is not displayed in VM pool

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#989]
Description of problem [include screenshots and browser console logs]:
Template and cluster is not displayed in VM pool detail. Same for admin and non-admin user.

VM Portal version number:
master
oVirt version number:
ovirt-engine-4.4.0-0.0.master.20190318180517.git576124b.el7.noarch
Browser and version:
FF 65.0.1

![Screenshot from 2019-03-20 16-39-43](https://user-images.githubusercontent.com/29575480/54698269-4da95580-4b2f-11e9-9ea2-67bb81d137ad.png)

**Comment by gregsheremeta** [comment]
We will just fix this in the redesign for #195

**Comment by sgratch** [comment]
@bond95 not sure if it's still reproduced and if it's relevant for the pool's VM or the pool itself so please check and if it's not reproduced anymore then let's close this

**Comment by bond95** [comment]
> @bond95 not sure if it's still reproduced and if it's relevant for the pool's VM or the pool itself so please check and if it's not reproduced anymore then let's close this

Yes, this bug will be fixed in redesign
