### ISSUE TITLE
Add CODING STYLE guide

### ISSUE THREAD

**Issue by matobet** [oVirt/ovirt-web-ui#99]
It would be useful to have a single document explaining the guidelines how to name components, files, structure package directories and in general develop code in this repository.

As the basis I would probably use the practices developed in https://github.com/oVirt/ovirt-engine-dashboard e.g. naming multi-word files files with `"-"` (`main-tab.js`, `vm-dialog.js`, .etc...), and standard react best practices from http://reactpatterns.com/

**Comment by gregsheremeta** [comment]
test comment - delete me
