### ISSUE TITLE
Better handling for token expiration

### ISSUE THREAD

**Issue by bond95** [oVirt/ovirt-web-ui#991]
The app needs much better robust handling for when the token expires on the backend to detect that, stop future refresh updates (to prevent additional errors warning), show the notification (or maybe not) and then push the user to the SSO login page.  In dev mode, there is no SSO login page, so an error component or page would be nice (like `TokenExpired` :wink:).

_Originally posted by @sjd78 in https://github.com/oVirt/ovirt-web-ui/pull/968#issuecomment-469367125_

**Comment by sgratch** [comment]
@bond95 @sjd78 do we still have work to do here?

**Comment by bond95** [comment]
@sgratch yes, we still don't have robust token expiration handling.

**Comment by lwrigh** [comment]
![Logged out empty state](https://user-images.githubusercontent.com/20227374/64281045-4ed51000-cf20-11e9-8f7c-ee152ceecee3.png)

Here's a PatternFly 4 pass at an improved logged out empty state.
