### ISSUE TITLE
When editing the amount of memory for a VM, memory units are automatically changed from MiB to GiB 

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#999]
When editing the amount of memory for a VM, memory units are automatically changed from MiB to GiB, which may lead to a VM which is not able to be scheduled

Version-Release number of selected component (if applicable):
4.3

How reproducible:
100%

Steps to Reproduce:
1. Provision a VM and edit the memory amount
2. Change 384 MiB (for example) to 512 MiB

Actual results:
MiB is changed to GiB

Expected results:
Units stay the same unless it's >1000 and makes sense to scale
——
Found here:

https://github.com/oVirt/ovirt-web-ui/commit/7f39063f#diff-1ed030b4b0f12b219c73b9e938e03286R363

Did we document this anywhere/ Assuming it's GB for templates is probably ok, but I'm not seeing a tooltip or anything. It's probably better to just assume it's MiB for 'normal' VMs, or we could put a little more effort into it and change:

if (isNumber(value) && ...) {
...
}
// Addition
else if (isParsableByte(value)) {
...
}

function isParsableByte(input) {
    types = {
        "MiB":
          ["MiB", "MB"],
        "GiB":
          ["GiB", "GB"]
    }
    matched = false

    Object.keys(types).forEach(function (size) {
        types[size].some(function(x) {
          if (input.match(x)) {
              matched = size
              return true
          }   
        }) 
    }) 
    console.log(matched)
    return matched 
}

Or, y'know, just default to MiB ;) Or document it

**Comment by sjd78** [comment]
![screenshot-chopper local dickerson-web com-2019 06 05-11-11-41](https://user-images.githubusercontent.com/3985964/58967778-cf9a3980-8782-11e9-819e-c9e26c6c5c5c.png)

The label to the right of the memory edit box has always indicated "GiB".  I'm fairly certain that we never discussed display/edit of memory in "MiB" during the design stages of the VM dashboard redesign.

Maybe it makes sense to make the GiB into a drop down to change the units ("TiB", "GiB", "MiB") and scale the initial display accordingly.  There is similar functionality in the labels on the charts.

**Comment by sgratch** [comment]
In webAdmin the default memory units are MB, and it's also MiB for current/old "Create vm" dialog. 
I think that the default for creating vm should stays MiB.

Now need to decide on changing units on "Edit vm" and anyway avoid skipping from one to the other without requiring which is the current behaviour.

**Comment by sjd78** [comment]
Same as #974
